import sys

import numpy as np

import openmdao.api as om

import pycycle.api as pyc

from pycycle.elements.cooling import CoolingCalcs

from physics_combustor import PhysicsCombustor, calc_CdA_liner

# Fixed-geometry CFM56 HPT map (3 alpha slices, 0.9/1.0/1.1 — no VGT scheduling).
# Generated by CFM56_HPT_map_generator.py.
from CFM56_HPT_map_fixed import CFM56HPTMapFixed


class HBTF(pyc.Cycle):

    def initialize(self):
        self.options.declare('throttle_mode', default='T4', values=['T4', 'percent_thrust'])
        self.options.declare('hpt_map', default=CFM56HPTMapFixed, recordable=False)

        super().initialize()


    def setup(self):
        #Setup the problem by including all the relavant components here - comp, burner, turbine etc

        #Create any relavent short hands here:
        design = self.options['design']

        USE_TABULAR = True
        if USE_TABULAR:
            self.options['thermo_method'] = 'TABULAR'
            self.options['thermo_data'] = pyc.AIR_JETA_TAB_SPEC
            FUEL_TYPE = 'FAR'
        else:
            self.options['thermo_method'] = 'CEA'
            self.options['thermo_data'] = pyc.species_data.janaf
            FUEL_TYPE = 'Jet-A(g)'


        #Add subsystems to build the engine deck:
        self.add_subsystem('fc', pyc.FlightConditions())
        self.add_subsystem('inlet', pyc.Inlet())

        # Note variable promotion for the fan --
        # the LP spool speed and the fan speed are INPUTS that are promoted:
        # Note here that promotion aliases are used. Here Nmech is being aliased to LP_Nmech
        # check out: https://openmdao.org/newdocs/versions/latest/features/core_features/working_with_groups/add_subsystem.html?highlight=alias
        self.add_subsystem('fan', pyc.Compressor(map_data=pyc.FanMap,
                                        bleed_names=[], map_extrap=True), promotes_inputs=[('Nmech','LP_Nmech')])
        self.add_subsystem('splitter', pyc.Splitter())
        self.add_subsystem('duct4', pyc.Duct())
        self.add_subsystem('lpc', pyc.Compressor(map_data=pyc.LPCMap,
                                        map_extrap=True),promotes_inputs=[('Nmech','LP_Nmech')])
        self.add_subsystem('duct6', pyc.Duct())
        self.add_subsystem('hpc', pyc.Compressor(map_data=pyc.HPCMap,
                                        bleed_names=['cool1','cool2','cust'], map_extrap=True),promotes_inputs=[('Nmech','HP_Nmech')])
        self.add_subsystem('bld3', pyc.BleedOut(bleed_names=['cool3','cool4']))
        self.add_subsystem('burner', pyc.Combustor(fuel_type=FUEL_TYPE))

        hpt_map = self.options['hpt_map']
        self.add_subsystem('hpt', pyc.Turbine(map_data=hpt_map,
                                        bleed_names=['cool3','cool4'], map_extrap=True),promotes_inputs=[('Nmech','HP_Nmech')])

        self.add_subsystem('ngv_calcs', CoolingCalcs(n_stages=1, i_row=0,
                                        T_metal=2210.0, T_safety=150.0))   # NGV stator, °R

        self.add_subsystem('bld_calcs', CoolingCalcs(n_stages=1, i_row=1,
                                        T_metal=2110.0, T_safety=150.0))   # rotor blade, °R

        self.add_subsystem('cool_fracs', om.ExecComp(
            ['frac_ngv = W_ngv / W_in', 'frac_bld = W_bld / W_in'],
            W_ngv={'val': 5.0, 'units': 'lbm/s'},
            W_bld={'val': 3.0, 'units': 'lbm/s'},
            W_in ={'val': 100.0, 'units': 'lbm/s'},
        ))

        self.add_subsystem('duct11', pyc.Duct())
        self.add_subsystem('lpt', pyc.Turbine(map_data=pyc.LPTMap,
                                        bleed_names=['cool1','cool2'], map_extrap=True),promotes_inputs=[('Nmech','LP_Nmech')])
        self.add_subsystem('duct13', pyc.Duct())
        self.add_subsystem('core_nozz', pyc.Nozzle(nozzType='CV', lossCoef='Cv'))

        self.add_subsystem('byp_bld', pyc.BleedOut(bleed_names=['bypBld']))
        self.add_subsystem('duct15', pyc.Duct())
        self.add_subsystem('byp_nozz', pyc.Nozzle(nozzType='CV', lossCoef='Cv'))

        # Mechanical transmission efficiency: loss = (1 - eta) * turbine_power → HPX
        self.add_subsystem('hp_mech_loss', om.ExecComp(
            'HPX_mech = (1.0 - mech_eff) * pwr_turb',
            HPX_mech={'val': 320., 'units': 'hp'},
            pwr_turb ={'val': 10000., 'units': 'hp'},
            mech_eff ={'val': 0.97}))
        self.add_subsystem('lp_mech_loss', om.ExecComp(
            'HPX_mech = (1.0 - mech_eff) * pwr_turb',
            HPX_mech={'val': 316., 'units': 'hp'},
            pwr_turb ={'val': 10000., 'units': 'hp'},
            mech_eff ={'val': 0.97}))

        #Create shaft instances. Note that LP shaft has 3 ports! => no gearbox
        self.add_subsystem('lp_shaft', pyc.Shaft(num_ports=3),promotes_inputs=[('Nmech','LP_Nmech')])
        self.add_subsystem('hp_shaft', pyc.Shaft(num_ports=2),promotes_inputs=[('Nmech','HP_Nmech')])
        self.add_subsystem('perf', pyc.Performance(num_nozzles=2, num_burners=1))

        # Now use the explicit connect method to make connections -- connect(<from>, <to>)

        #Connect the inputs to perf group
        self.connect('inlet.Fl_O:tot:P', 'perf.Pt2')
        self.connect('hpc.Fl_O:tot:P', 'perf.Pt3')
        self.connect('burner.Wfuel', 'perf.Wfuel_0')
        self.connect('inlet.F_ram', 'perf.ram_drag')
        self.connect('core_nozz.Fg', 'perf.Fg_0')
        self.connect('byp_nozz.Fg', 'perf.Fg_1')

        #LP-shaft connections
        self.connect('fan.trq', 'lp_shaft.trq_0')
        self.connect('lpc.trq', 'lp_shaft.trq_1')
        self.connect('lpt.trq', 'lp_shaft.trq_2')
        #HP-shaft connections
        self.connect('hpc.trq', 'hp_shaft.trq_0')
        self.connect('hpt.trq', 'hp_shaft.trq_1')
        # Mechanical losses → HPX (replaces fixed 250 hp, York η_HP = η_LP = 0.97)
        self.connect('hpt.power', 'hp_mech_loss.pwr_turb')
        self.connect('hp_mech_loss.HPX_mech', 'hp_shaft.HPX')
        self.connect('lpt.power', 'lp_mech_loss.pwr_turb')
        self.connect('lp_mech_loss.HPX_mech', 'lp_shaft.HPX')
        #Ideally expanding flow by conneting flight condition static pressure to nozzle exhaust pressure
        self.connect('fc.Fl_O:stat:P', 'core_nozz.Ps_exhaust')
        self.connect('fc.Fl_O:stat:P', 'byp_nozz.Ps_exhaust')

        for calc in ('ngv_calcs', 'bld_calcs'):
            self.connect('burner.Fl_O:tot:T',  f'{calc}.Tt_primary')
            self.connect('burner.Fl_O:tot:h',  f'{calc}.ht_primary')
            self.connect('burner.Fl_O:stat:W', f'{calc}.W_primary')
            self.connect('burner.Fl_O:tot:P',  f'{calc}.Pt_in')
            self.connect('hpt.Fl_O:tot:P',     f'{calc}.Pt_out')
            self.connect('bld3.Fl_O:tot:T',    f'{calc}.Tt_cool')
            self.connect('bld3.Fl_O:tot:h',    f'{calc}.ht_cool')
            self.connect('hpt.power',          f'{calc}.turb_pwr')

        self.connect('ngv_calcs.W_cool', 'cool_fracs.W_ngv')
        self.connect('bld_calcs.W_cool', 'cool_fracs.W_bld')
        self.connect('hpc.Fl_O:stat:W',  'cool_fracs.W_in')
        # cool_fracs outputs are NOT connected to bld3 inside Newton —
        # the outer loop in main sets bld3.cool3/4:frac_W externally each iteration

        #Create a balance component
        # Balances can be a bit confusing, here's some explanation -
        #   State Variables:
        #           (W)        Inlet mass flow rate to implictly balance thrust
        #                      LHS: perf.Fn  == RHS: Thrust requirement (set when TF is instantiated)
        #
        #           (FAR)      Fuel-air ratio to balance Tt4
        #                      LHS: burner.Fl_O:tot:T  == RHS: Tt4 target (set when TF is instantiated)
        #
        #           (lpt_PR)   LPT press ratio to balance shaft power on the low spool
        #           (hpt_PR)   HPT press ratio to balance shaft power on the high spool
        # Ref: look at the XDSM diagrams in the pyCycle paper and this:
        # http://openmdao.org/newdocs/versions/latest/features/building_blocks/components/balance_comp.html

        balance = self.add_subsystem('balance', om.BalanceComp())
        if design:
            balance.add_balance('W', units='lbm/s', eq_units='lbf')
            #Here balance.W is implicit state variable that is the OUTPUT of balance object
            self.connect('balance.W', 'fc.W') #Connect the output of balance to the relevant input
            self.connect('perf.Fn', 'balance.lhs:W')       #This statement makes perf.Fn the LHS of the balance eqn.
            self.promotes('balance', inputs=[('rhs:W', 'Fn_DES')])

            balance.add_balance('FAR', eq_units='degR', lower=1e-4, val=.017)
            self.connect('balance.FAR', 'burner.Fl_I:FAR')
            self.connect('burner.Fl_O:tot:T', 'balance.lhs:FAR')
            self.promotes('balance', inputs=[('rhs:FAR', 'T4_MAX')])

            # Note that for the following two balances the mult val is set to -1 so that the NET torque is zero
            balance.add_balance('lpt_PR', val=1.5, lower=1.001, upper=8,
                                eq_units='hp', use_mult=True, mult_val=-1)
            self.connect('balance.lpt_PR', 'lpt.PR')
            self.connect('lp_shaft.pwr_in_real', 'balance.lhs:lpt_PR')
            self.connect('lp_shaft.pwr_out_real', 'balance.rhs:lpt_PR')

            balance.add_balance('hpt_PR', val=1.5, lower=1.001, upper=8,
                                eq_units='hp', use_mult=True, mult_val=-1)
            self.connect('balance.hpt_PR', 'hpt.PR')
            self.connect('hp_shaft.pwr_in_real', 'balance.lhs:hpt_PR')
            self.connect('hp_shaft.pwr_out_real', 'balance.rhs:hpt_PR')


        else:

            #In OFF-DESIGN mode we need to redefine the balances:
            #   State Variables:
            #           (W)        Inlet mass flow rate to balance core flow area
            #                      LHS: core_nozz.Throat:stat:area == Area from DESIGN calculation
            #
            #           (FAR)      Fuel-air ratio to balance Thrust req.
            #                      LHS: perf.Fn  == RHS: Thrust requirement (set when TF is instantiated)
            #
            #           (BPR)      Bypass ratio to balance byp. noz. area
            #                      LHS: byp_nozz.Throat:stat:area == Area from DESIGN calculation
            #
            #           (lp_Nmech)   LP spool speed to balance shaft power on the low spool
            #           (hp_Nmech)   HP spool speed to balance shaft power on the high spool

            if self.options['throttle_mode'] == 'T4':
                balance.add_balance('FAR', val=0.017, lower=1e-4, eq_units='degR')
                self.connect('balance.FAR', 'burner.Fl_I:FAR')
                self.connect('burner.Fl_O:tot:T', 'balance.lhs:FAR')
                self.promotes('balance', inputs=[('rhs:FAR', 'T4_MAX')])

            elif self.options['throttle_mode'] == 'percent_thrust':
                balance.add_balance('FAR', val=0.017, lower=1e-4, eq_units='lbf', use_mult=True)
                self.connect('balance.FAR', 'burner.Fl_I:FAR')
                self.connect('perf.Fn', 'balance.rhs:FAR')
                self.promotes('balance', inputs=[('mult:FAR', 'PC'), ('lhs:FAR', 'Fn_max')])


            balance.add_balance('W', units='lbm/s', lower=10., upper=1000., eq_units='inch**2')
            self.connect('balance.W', 'fc.W')
            self.connect('core_nozz.Throat:stat:area', 'balance.lhs:W')

            balance.add_balance('BPR', lower=2., upper=10., eq_units='inch**2')
            self.connect('balance.BPR', 'splitter.BPR')
            self.connect('byp_nozz.Throat:stat:area', 'balance.lhs:BPR')

            # Again for the following two balances the mult val is set to -1 so that the NET torque is zero
            balance.add_balance('lp_Nmech', val=1.5, units='rpm', lower=500., eq_units='hp', use_mult=True, mult_val=-1)
            self.connect('balance.lp_Nmech', 'LP_Nmech')
            self.connect('lp_shaft.pwr_in_real', 'balance.lhs:lp_Nmech')
            self.connect('lp_shaft.pwr_out_real', 'balance.rhs:lp_Nmech')

            balance.add_balance('hp_Nmech', val=1.5, units='rpm', lower=500., eq_units='hp', use_mult=True, mult_val=-1)
            self.connect('balance.hp_Nmech', 'HP_Nmech')
            self.connect('hp_shaft.pwr_in_real', 'balance.lhs:hp_Nmech')
            self.connect('hp_shaft.pwr_out_real', 'balance.rhs:hp_Nmech')

            self.add_subsystem('orifice', PhysicsCombustor())
            self.connect('hpc.Fl_O:tot:T',  'orifice.Tt3')
            self.connect('hpc.Fl_O:tot:P',  'orifice.Pt3')
            self.connect('hpc.Fl_O:stat:W', 'orifice.W')
            self.connect('orifice.dPqP',    'burner.dPqP')

        # Set up all the flow connections:
        self.pyc_connect_flow('fc.Fl_O', 'inlet.Fl_I')
        self.pyc_connect_flow('inlet.Fl_O', 'fan.Fl_I')
        self.pyc_connect_flow('fan.Fl_O', 'splitter.Fl_I')
        self.pyc_connect_flow('splitter.Fl_O1', 'duct4.Fl_I')
        self.pyc_connect_flow('duct4.Fl_O', 'lpc.Fl_I')
        self.pyc_connect_flow('lpc.Fl_O', 'duct6.Fl_I')
        self.pyc_connect_flow('duct6.Fl_O', 'hpc.Fl_I')
        self.pyc_connect_flow('hpc.Fl_O', 'bld3.Fl_I')
        self.pyc_connect_flow('bld3.Fl_O', 'burner.Fl_I')
        self.pyc_connect_flow('burner.Fl_O', 'hpt.Fl_I')
        self.pyc_connect_flow('hpt.Fl_O', 'duct11.Fl_I')
        self.pyc_connect_flow('duct11.Fl_O', 'lpt.Fl_I')
        self.pyc_connect_flow('lpt.Fl_O', 'duct13.Fl_I')
        self.pyc_connect_flow('duct13.Fl_O','core_nozz.Fl_I')
        self.pyc_connect_flow('splitter.Fl_O2', 'byp_bld.Fl_I')
        self.pyc_connect_flow('byp_bld.Fl_O', 'duct15.Fl_I')
        self.pyc_connect_flow('duct15.Fl_O', 'byp_nozz.Fl_I')

        #Bleed flows:
        self.pyc_connect_flow('hpc.cool1', 'lpt.cool1', connect_stat=False)
        self.pyc_connect_flow('hpc.cool2', 'lpt.cool2', connect_stat=False)
        self.pyc_connect_flow('bld3.cool3', 'hpt.cool3', connect_stat=False)
        self.pyc_connect_flow('bld3.cool4', 'hpt.cool4', connect_stat=False)

        #Specify solver settings:
        newton = self.nonlinear_solver = om.NewtonSolver()
        newton.options['atol'] = 1e-8

        # set this very small, so it never activates and we rely on atol
        newton.options['rtol'] = 1e-99
        newton.options['iprint'] = 2
        newton.options['maxiter'] = 50
        newton.options['solve_subsystems'] = True
        newton.options['max_sub_solves'] = 1000
        newton.options['reraise_child_analysiserror'] = False
        ls = newton.linesearch = om.ArmijoGoldsteinLS()
        ls.options['maxiter'] = 3
        ls.options['rho'] = 0.75

        self.linear_solver = om.DirectSolver()

        super().setup()


def viewer(prob, pt, file=sys.stdout):
    """
    print a report of all the relevant cycle properties
    """

    if pt == 'DESIGN':
        MN = prob['DESIGN.fc.Fl_O:stat:MN']
        LPT_PR = prob['DESIGN.balance.lpt_PR']
        HPT_PR = prob['DESIGN.balance.hpt_PR']
        FAR = prob['DESIGN.balance.FAR']
    else:
        MN = prob[pt+'.fc.Fl_O:stat:MN']
        LPT_PR = prob[pt+'.lpt.PR']
        HPT_PR = prob[pt+'.hpt.PR']
        FAR = prob[pt+'.balance.FAR']

    summary_data = (MN[0], prob[pt+'.fc.alt'][0], prob[pt+'.inlet.Fl_O:stat:W'][0], prob[pt+'.perf.Fn'][0],
                        prob[pt+'.perf.Fg'][0], prob[pt+'.inlet.F_ram'][0], prob[pt+'.perf.OPR'][0],
                        prob[pt+'.perf.TSFC'][0], prob[pt+'.splitter.BPR'][0])

    print(file=file, flush=True)
    print(file=file, flush=True)
    print(file=file, flush=True)
    print("----------------------------------------------------------------------------", file=file, flush=True)
    print("                              POINT:", pt, file=file, flush=True)
    print("----------------------------------------------------------------------------", file=file, flush=True)
    print("                       PERFORMANCE CHARACTERISTICS", file=file, flush=True)
    print("    Mach      Alt       W      Fn      Fg    Fram     OPR     TSFC      BPR ", file=file, flush=True)
    print(" %7.5f  %7.1f %7.3f %7.1f %7.1f %7.1f %7.3f  %7.5f  %7.3f" %summary_data, file=file, flush=True)


    fs_names = ['fc.Fl_O', 'inlet.Fl_O', 'fan.Fl_O', 'splitter.Fl_O1', 'splitter.Fl_O2',
                'duct4.Fl_O', 'lpc.Fl_O', 'duct6.Fl_O', 'hpc.Fl_O', 'bld3.Fl_O', 'burner.Fl_O',
                'hpt.Fl_O', 'duct11.Fl_O', 'lpt.Fl_O', 'duct13.Fl_O', 'core_nozz.Fl_O', 'byp_bld.Fl_O',
                'duct15.Fl_O', 'byp_nozz.Fl_O']
    fs_full_names = [f'{pt}.{fs}' for fs in fs_names]
    pyc.print_flow_station(prob, fs_full_names, file=file)

    comp_names = ['fan', 'lpc', 'hpc']
    comp_full_names = [f'{pt}.{c}' for c in comp_names]
    pyc.print_compressor(prob, comp_full_names, file=file)

    pyc.print_burner(prob, [f'{pt}.burner'], file=file)

    turb_names = ['hpt', 'lpt']
    turb_full_names = [f'{pt}.{t}' for t in turb_names]
    pyc.print_turbine(prob, turb_full_names, file=file)

    noz_names = ['core_nozz', 'byp_nozz']
    noz_full_names = [f'{pt}.{n}' for n in noz_names]
    pyc.print_nozzle(prob, noz_full_names, file=file)

    shaft_names = ['hp_shaft', 'lp_shaft']
    shaft_full_names = [f'{pt}.{s}' for s in shaft_names]
    pyc.print_shaft(prob, shaft_full_names, file=file)

    bleed_names = ['hpc', 'bld3', 'byp_bld']
    bleed_full_names = [f'{pt}.{b}' for b in bleed_names]
    pyc.print_bleed(prob, bleed_full_names, file=file)


def _make_mphbtf(cfg):

    class MPhbtf(pyc.MPCycle):

        def setup(self):

            self.pyc_add_pnt('DESIGN', HBTF(thermo_method='CEA', hpt_map=cfg['hpt_map']))

            self.set_input_defaults('DESIGN.inlet.MN', 0.751)
            self.set_input_defaults('DESIGN.fan.MN', 0.4578)
            self.set_input_defaults('DESIGN.splitter.BPR', cfg['BPR'])
            self.set_input_defaults('DESIGN.splitter.MN1', 0.3104)
            self.set_input_defaults('DESIGN.splitter.MN2', 0.4518)
            self.set_input_defaults('DESIGN.duct4.MN', 0.3121)
            self.set_input_defaults('DESIGN.lpc.MN', 0.3059)
            self.set_input_defaults('DESIGN.duct6.MN', 0.3563)
            self.set_input_defaults('DESIGN.hpc.MN', 0.2442)
            self.set_input_defaults('DESIGN.bld3.MN', 0.3000)
            self.set_input_defaults('DESIGN.burner.MN', 0.1025)
            self.set_input_defaults('DESIGN.hpt.MN', 0.3650)
            self.set_input_defaults('DESIGN.duct11.MN', 0.3063)
            self.set_input_defaults('DESIGN.lpt.MN', 0.4127)
            self.set_input_defaults('DESIGN.duct13.MN', 0.4463)
            self.set_input_defaults('DESIGN.byp_bld.MN', 0.4489)
            self.set_input_defaults('DESIGN.duct15.MN', 0.4589)
            self.set_input_defaults('DESIGN.LP_Nmech', cfg['LP_Nmech'], units='rpm')
            self.set_input_defaults('DESIGN.HP_Nmech', cfg['HP_Nmech'], units='rpm')

            self.pyc_add_cycle_param('inlet.ram_recovery', cfg['ram_recovery'])
            self.pyc_add_cycle_param('duct4.dPqP', 0.0048)
            self.pyc_add_cycle_param('duct6.dPqP', 0.0101)
            # burner.dPqP is NOT a cycle param — DESIGN uses set_val, OD driven by orifice
            self.pyc_add_cycle_param('duct11.dPqP', 0.0051)
            self.pyc_add_cycle_param('duct13.dPqP', 0.0107)
            self.pyc_add_cycle_param('duct15.dPqP', 0.0149)
            self.pyc_add_cycle_param('core_nozz.Cv', 0.9933)
            self.pyc_add_cycle_param('byp_bld.bypBld:frac_W', 0.005)
            self.pyc_add_cycle_param('byp_nozz.Cv', 0.9939)
            self.pyc_add_cycle_param('hpc.cool1:frac_W', 0.0)
            self.pyc_add_cycle_param('hpc.cool1:frac_P', 0.5)
            self.pyc_add_cycle_param('hpc.cool1:frac_work', 0.5)
            self.pyc_add_cycle_param('hpc.cool2:frac_W', 0.0)
            self.pyc_add_cycle_param('hpc.cool2:frac_P', 0.55)
            self.pyc_add_cycle_param('hpc.cool2:frac_work', 0.5)
            self.pyc_add_cycle_param('hpc.cust:frac_P', 0.5)
            self.pyc_add_cycle_param('hpc.cust:frac_work', 0.5)
            self.pyc_add_cycle_param('hpc.cust:frac_W', 0.0445)
            self.pyc_add_cycle_param('hpt.cool3:frac_P', 1.0)
            self.pyc_add_cycle_param('hpt.cool4:frac_P', 0.0)
            self.pyc_add_cycle_param('lpt.cool1:frac_P', 1.0)
            self.pyc_add_cycle_param('lpt.cool2:frac_P', 0.0)

            self.od_pts = ['OD_full_pwr', 'OD_part_pwr']

            self.od_MNs = [0.8, 0.8]
            self.od_alts = [35000.0, 35000.0]
            self.od_dTs = [0.0, 0.0]

            self.pyc_add_pnt('OD_full_pwr', HBTF(design=False, thermo_method='CEA',
                                                  throttle_mode='T4', hpt_map=cfg['hpt_map']))

            self.set_input_defaults('OD_full_pwr.fc.MN', 0.8)
            self.set_input_defaults('OD_full_pwr.fc.alt', 35000, units='ft')
            self.set_input_defaults('OD_full_pwr.fc.dTs', 0., units='degR')

            self.pyc_add_pnt('OD_part_pwr', HBTF(design=False, thermo_method='CEA',
                                                   throttle_mode='percent_thrust', hpt_map=cfg['hpt_map']))

            self.set_input_defaults('OD_part_pwr.fc.MN', 0.8)
            self.set_input_defaults('OD_part_pwr.fc.alt', 35000, units='ft')
            self.set_input_defaults('OD_part_pwr.fc.dTs', 0., units='degR')

            self.connect('OD_full_pwr.perf.Fn', 'OD_part_pwr.Fn_max')

            # No VGT/A4 sweep — fixed NGV geometry throughout, so ALL turbine
            # scalars (including hpt.s_Wp/s_eff) connect DESIGN -> OD normally.
            for comp in ['fan', 'lpc', 'hpc']:
                for sc in ['s_Wc', 's_PR', 's_eff', 's_Nc']:
                    self.pyc_connect_des_od(f'{comp}.{sc}', f'{comp}.{sc}')
                self.pyc_connect_des_od(f'{comp}.Fl_O:stat:area', f'{comp}.area')

            for sc in ['s_Wp', 's_PR', 's_eff', 's_Np']:
                self.pyc_connect_des_od(f'hpt.{sc}', f'hpt.{sc}')
            self.pyc_connect_des_od('hpt.Fl_O:stat:area', 'hpt.area')

            for sc in ['s_Wp', 's_PR', 's_eff', 's_Np']:
                self.pyc_connect_des_od(f'lpt.{sc}', f'lpt.{sc}')
            self.pyc_connect_des_od('lpt.Fl_O:stat:area', 'lpt.area')

            self.pyc_connect_des_od('core_nozz.Throat:stat:area', 'balance.rhs:W')
            self.pyc_connect_des_od('byp_nozz.Throat:stat:area',  'balance.rhs:BPR')

            super().setup()

    return MPhbtf


def _interp_eff_at_design(map_obj):
    """Interpolate map efficiency at design point (alpha_des, Np_des, PR_des)."""
    from scipy.interpolate import RegularGridInterpolator
    ei = RegularGridInterpolator(
        (np.array(map_obj.alphaMap), np.array(map_obj.NpMap), np.array(map_obj.PRmap)),
        np.array(map_obj.effMap), method='linear', bounds_error=False, fill_value=None)
    return float(ei([[map_obj.defaults['alphaMap'],
                      map_obj.defaults['NpMap'],
                      map_obj.defaults['PRmap']]])[0])


def run_toc_cruise(CFG):
    """Run the fixed-geometry CFM56 study: design (TOC) -> TOC readout -> Cruise readout.

    No VGT / A4 sweep — this is the fixed-NGV baseline only.
    """
    import time

    ureg = None  # placeholder kept for signature parity with cfm56_cycle.py

    print(f'\n{"="*60}')
    print(f'  Scenario: {CFG["label"]}')
    print(f'  hpt_eff={CFG["hpt_eff"]:.4f}')
    print(f'{"="*60}')

    # Validation targets — York (2017) Table 3.5 (hf = 40.8 MJ/kg)
    TSFC_TOC_TARGET  = 0.6941    # /hr
    TSFC_CRSE_TARGET = 0.6793    # /hr

    prob = om.Problem()
    prob.model = mp_hbtf = _make_mphbtf(CFG)()
    prob.setup()

    # ── Component design parameters ───────────────────────────────────────────
    # burner.dPqP: DESIGN only — OD points are driven by the orifice component
    prob.set_val('DESIGN.burner.dPqP', CFG['burner_dPqP'])

    prob.set_val('DESIGN.fan.PR',  CFG['fan_PR'])
    prob.set_val('DESIGN.fan.eff', CFG['fan_eff'])

    prob.set_val('DESIGN.lpc.PR',  CFG['lpc_PR'])
    prob.set_val('DESIGN.lpc.eff', CFG['lpc_eff'])

    prob.set_val('DESIGN.hpc.PR',  CFG['hpc_PR'])
    prob.set_val('DESIGN.hpc.eff', CFG['hpc_eff'])

    prob.set_val('DESIGN.hpt.eff', CFG['hpt_eff'])
    prob.set_val('DESIGN.lpt.eff', CFG['lpt_eff'])

    # ── Design flight condition: TOC ──────────────────────────────────────────
    prob.set_val('DESIGN.fc.alt',  35000., units='ft')
    prob.set_val('DESIGN.fc.MN',   0.8)
    prob.set_val('DESIGN.T4_MAX',  CFG['T4_MAX'],  units='degR')
    prob.set_val('DESIGN.Fn_DES',  CFG['Fn_TOC'],  units='lbf')

    # OD_full_pwr = TOC: same T4, alt, MN as design → reproduces TOC condition
    prob.set_val('OD_full_pwr.T4_MAX', CFG['T4_MAX'], units='degR')

    # OD_part_pwr = cruise: PC fraction of TOC thrust
    prob.set_val('OD_part_pwr.PC', CFG['Fn_crse'] / CFG['Fn_TOC'])

    # ── Initial guesses — DESIGN ──────────────────────────────────────────────
    prob['DESIGN.balance.FAR']    = CFG['FAR_guess']
    prob['DESIGN.balance.W']      = CFG['W_guess']
    prob['DESIGN.balance.lpt_PR'] = CFG['lpt_PR_guess']
    prob['DESIGN.balance.hpt_PR'] = CFG['hpt_PR_guess']
    prob['DESIGN.fc.balance.Pt']  = 5.2
    prob['DESIGN.fc.balance.Tt']  = 440.0

    # ── Initial guesses — OD (maxiter=0 disables OD for the design-only solve) ─
    for pt in ['OD_full_pwr', 'OD_part_pwr']:
        prob[pt+'.balance.FAR']      = CFG['FAR_guess']
        prob[pt+'.balance.W']        = CFG['W_guess']
        prob[pt+'.balance.BPR']      = CFG['BPR']
        prob[pt+'.balance.lp_Nmech'] = CFG['LP_Nmech']
        prob[pt+'.balance.hp_Nmech'] = CFG['HP_Nmech']
        prob[pt+'.hpt.PR']           = CFG['hpt_PR_guess']
        prob[pt+'.lpt.PR']           = CFG['lpt_PR_guess']
        prob[pt+'.fan.map.RlineMap'] = 2.0
        prob[pt+'.lpc.map.RlineMap'] = 2.0
        prob[pt+'.hpc.map.RlineMap'] = 2.0
        prob.model._get_subsystem(pt).nonlinear_solver.options['maxiter'] = 0

    prob.set_solver_print(level=-1)
    prob.set_solver_print(level=2, depth=1)

    # ── HPT cooling fractions ─────────────────────────────────────────────────
    prob.set_val('DESIGN.bld3.cool3:frac_W', CFG['frac_ngv'])
    prob.set_val('DESIGN.bld3.cool4:frac_W', CFG['frac_bld'])

    print('\n── Design solve (TOC) ──')
    t0 = time.time()
    prob.run_model()
    print(f'Design solved in {time.time()-t0:.1f}s')

    viewer_file = open('cfm56_fixed_toc_cruise_view.out', 'w')
    viewer(prob, 'DESIGN', file=viewer_file)
    viewer(prob, 'DESIGN')

    # ── Calibrate orifice CdA from converged design-point combustor inlet ─────
    W_des   = float(prob.get_val('DESIGN.hpc.Fl_O:stat:W', units='lbm/s')[0])
    Tt3_des = float(prob.get_val('DESIGN.hpc.Fl_O:tot:T',  units='degR')[0])
    Pt3_des = float(prob.get_val('DESIGN.hpc.Fl_O:tot:P',  units='psi')[0])

    import pint
    _ureg = pint.UnitRegistry()
    _Q_   = _ureg.Quantity
    W_si   = _Q_(W_des,   'lb/s').to('kg/s').magnitude
    Tt3_K  = _Q_(Tt3_des, 'degR').to('K').magnitude
    Pt3_Pa = _Q_(Pt3_des, 'psi').to('Pa').magnitude

    CdA = calc_CdA_liner(Tt3_K, Pt3_Pa, W_si, dPqP_ref=CFG['burner_dPqP'])
    print(f'\nCalibrated CdA = {CdA:.6f} m²')

    # ── Seed OD state from converged design solution ──────────────────────────
    des_FAR       = float(prob.get_val('DESIGN.balance.FAR')[0])
    des_W         = float(prob.get_val('DESIGN.balance.W')[0])
    des_BPR       = float(prob.get_val('DESIGN.splitter.BPR')[0])
    des_hpt_PR    = float(prob.get_val('DESIGN.balance.hpt_PR')[0])
    des_lpt_PR    = float(prob.get_val('DESIGN.balance.lpt_PR')[0])
    des_fan_Rline = float(prob.get_val('DESIGN.fan.map.RlineMap')[0])
    des_lpc_Rline = float(prob.get_val('DESIGN.lpc.map.RlineMap')[0])
    des_hpc_Rline = float(prob.get_val('DESIGN.hpc.map.RlineMap')[0])

    for pt in ['OD_full_pwr', 'OD_part_pwr']:
        prob[f'{pt}.balance.FAR']      = des_FAR
        prob[f'{pt}.balance.W']        = des_W
        prob[f'{pt}.balance.BPR']      = des_BPR
        prob[f'{pt}.balance.hp_Nmech'] = CFG['HP_Nmech']
        prob[f'{pt}.balance.lp_Nmech'] = CFG['LP_Nmech']
        prob[f'{pt}.hpt.PR']           = des_hpt_PR
        prob[f'{pt}.lpt.PR']           = des_lpt_PR
        prob[f'{pt}.fan.map.RlineMap'] = des_fan_Rline
        prob[f'{pt}.lpc.map.RlineMap'] = des_lpc_Rline
        prob[f'{pt}.hpc.map.RlineMap'] = des_hpc_Rline

    # ── Solve OD: TOC (full power) and Cruise (part power) ────────────────────
    for pt in ['OD_full_pwr', 'OD_part_pwr']:
        prob.model._get_subsystem(pt).nonlinear_solver.options['maxiter'] = 50
        prob.set_val(f'{pt}.orifice.CdA', CdA)
        prob.set_val(f'{pt}.bld3.cool3:frac_W', CFG['frac_ngv'])
        prob.set_val(f'{pt}.bld3.cool4:frac_W', CFG['frac_bld'])

    print('\n── OD solve (TOC + Cruise) ──')
    t1 = time.time()
    prob.run_model()
    print(f'OD solved in {time.time()-t1:.1f}s')

    viewer(prob, 'OD_full_pwr', file=viewer_file)
    viewer(prob, 'OD_part_pwr', file=viewer_file)
    viewer_file.close()

    # ── Validation summary vs York (2017) Table 3.5 ───────────────────────────
    tsfc_toc  = float(prob.get_val('OD_full_pwr.perf.TSFC')[0])
    tsfc_crse = float(prob.get_val('OD_part_pwr.perf.TSFC')[0])
    fn_toc    = float(prob.get_val('OD_full_pwr.perf.Fn', units='lbf')[0])
    fn_crse   = float(prob.get_val('OD_part_pwr.perf.Fn', units='lbf')[0])

    print('\n' + '='*60)
    print('  Validation vs York (2017) Table 3.5')
    print('='*60)
    print(f'  {"Point":<10} {"Fn (lbf)":>10} {"TSFC (/hr)":>12} '
          f'{"Target":>10} {"Error (%)":>10}')
    print(f'  {"-"*54}')
    print(f'  {"TOC":<10} {fn_toc:10.1f} {tsfc_toc:12.4f} '
          f'{TSFC_TOC_TARGET:10.4f} '
          f'{(tsfc_toc - TSFC_TOC_TARGET)/TSFC_TOC_TARGET*100:+10.2f}')
    print(f'  {"Cruise":<10} {fn_crse:10.1f} {tsfc_crse:12.4f} '
          f'{TSFC_CRSE_TARGET:10.4f} '
          f'{(tsfc_crse - TSFC_CRSE_TARGET)/TSFC_CRSE_TARGET*100:+10.2f}')
    print('='*60)

    return {
        'label': CFG['label'],
        'toc':    {'Fn': fn_toc,  'TSFC': tsfc_toc,  'target': TSFC_TOC_TARGET},
        'cruise': {'Fn': fn_crse, 'TSFC': tsfc_crse, 'target': TSFC_CRSE_TARGET},
    }


if __name__ == "__main__":

    import time

    eff_fixed = _interp_eff_at_design(CFM56HPTMapFixed)
    print(f'Design η — Fixed NGV map: {eff_fixed*100:.3f}%')

    CFG = dict(
        hpt_map      = CFM56HPTMapFixed,
        hpt_eff      = eff_fixed,
        label        = 'Fixed NGV — TOC / Cruise',
        fan_PR       = 1.685,
        fan_eff      = 0.9005,
        lpc_PR       = 1.935,
        lpc_eff      = 0.9306,
        hpc_PR       = 9.369,
        hpc_eff      = 0.9030,
        lpt_eff      = 0.8851,
        burner_dPqP  = 0.06,
        ram_recovery = 0.98,
        T4_MAX       = 2857.0,
        Fn_TOC       = 5961.9,
        Fn_crse      = 5496.4,
        LP_Nmech     = 4666.1,
        HP_Nmech     = 14705.7,
        BPR          = 5.105,
        frac_ngv     = 0.07,
        frac_bld     = 0.12,
        FAR_guess    = 0.025,
        W_guess      = 300.,
        hpt_PR_guess = 3.0,
        lpt_PR_guess = 4.0,
    )

    t_wall = time.time()
    result = run_toc_cruise(CFG)
    print(f'\nTotal wall time: {time.time()-t_wall:.1f}s')
