import sys

import numpy as np

import openmdao.api as om

import pycycle.api as pyc

from pycycle.elements.cooling import CoolingCalcs

from physics_combustor import PhysicsCombustor, calc_CdA_liner

# Custom HPT maps generated by CFM56_HPT_map_generator.py.
# CFM56HPTMapFixed — 3 alpha slices (0.9/1.0/1.1), fixed-stator baseline validation.
# CFM56HPTMapVGT   — 8 alpha slices (0.75–1.10), for VGT A4-scheduling study.
from CFM56_HPT_map_fixed import CFM56HPTMapFixed
from CFM56_HPT_map       import CFM56HPTMapVGT      # noqa: F401 (available for VGT study)


class HBTF(pyc.Cycle):

    def initialize(self):
        self.options.declare('throttle_mode', default='T4', values=['T4', 'percent_thrust', 'fn_target'])
        self.options.declare('hpt_map', default=CFM56HPTMapFixed, recordable=False)

        super().initialize()


    def setup(self):
        #Setup the problem by including all the relavant components here - comp, burner, turbine etc

        #Create any relavent short hands here:
        design = self.options['design']

        USE_TABULAR = True
        if USE_TABULAR:
            self.options['thermo_method'] = 'TABULAR'
            self.options['thermo_data'] = pyc.AIR_JETA_TAB_SPEC
            FUEL_TYPE = 'FAR'
        else:
            self.options['thermo_method'] = 'CEA'
            self.options['thermo_data'] = pyc.species_data.janaf
            FUEL_TYPE = 'Jet-A(g)'


        #Add subsystems to build the engine deck:
        self.add_subsystem('fc', pyc.FlightConditions())
        self.add_subsystem('inlet', pyc.Inlet())

        # Note variable promotion for the fan --
        # the LP spool speed and the fan speed are INPUTS that are promoted:
        # Note here that promotion aliases are used. Here Nmech is being aliased to LP_Nmech
        # check out: https://openmdao.org/newdocs/versions/latest/features/core_features/working_with_groups/add_subsystem.html?highlight=alias
        self.add_subsystem('fan', pyc.Compressor(map_data=pyc.FanMap,
                                        bleed_names=[], map_extrap=True), promotes_inputs=[('Nmech','LP_Nmech')])
        self.add_subsystem('splitter', pyc.Splitter())
        self.add_subsystem('duct4', pyc.Duct())
        self.add_subsystem('lpc', pyc.Compressor(map_data=pyc.LPCMap,
                                        map_extrap=True),promotes_inputs=[('Nmech','LP_Nmech')])
        self.add_subsystem('duct6', pyc.Duct())
        self.add_subsystem('hpc', pyc.Compressor(map_data=pyc.HPCMap,
                                        bleed_names=['cool1','cool2','cust'], map_extrap=True),promotes_inputs=[('Nmech','HP_Nmech')])
        self.add_subsystem('bld3', pyc.BleedOut(bleed_names=['cool3','cool4']))
        self.add_subsystem('burner', pyc.Combustor(fuel_type=FUEL_TYPE))
        
        hpt_map = self.options['hpt_map']
        self.add_subsystem('hpt', pyc.Turbine(map_data=hpt_map,
                                        bleed_names=['cool3','cool4'], map_extrap=True),promotes_inputs=[('Nmech','HP_Nmech')])
        
        self.add_subsystem('ngv_calcs', CoolingCalcs(n_stages=1, i_row=0,
                                        T_metal=2210.0, T_safety=150.0))   # NGV stator, °R
        
        self.add_subsystem('bld_calcs', CoolingCalcs(n_stages=1, i_row=1,
                                        T_metal=2110.0, T_safety=150.0))   # rotor blade, °R
        
        self.add_subsystem('cool_fracs', om.ExecComp(
            ['frac_ngv = W_ngv / W_in', 'frac_bld = W_bld / W_in'],
            W_ngv={'val': 5.0, 'units': 'lbm/s'},
            W_bld={'val': 3.0, 'units': 'lbm/s'},
            W_in ={'val': 100.0, 'units': 'lbm/s'},
        ))
        
        self.add_subsystem('duct11', pyc.Duct())
        self.add_subsystem('lpt', pyc.Turbine(map_data=pyc.LPTMap,
                                        bleed_names=['cool1','cool2'], map_extrap=True),promotes_inputs=[('Nmech','LP_Nmech')])
        self.add_subsystem('duct13', pyc.Duct())
        self.add_subsystem('core_nozz', pyc.Nozzle(nozzType='CV', lossCoef='Cv'))

        self.add_subsystem('byp_bld', pyc.BleedOut(bleed_names=['bypBld']))
        self.add_subsystem('duct15', pyc.Duct())
        self.add_subsystem('byp_nozz', pyc.Nozzle(nozzType='CV', lossCoef='Cv'))

        # Mechanical transmission efficiency: loss = (1 - eta) * turbine_power → HPX
        self.add_subsystem('hp_mech_loss', om.ExecComp(
            'HPX_mech = (1.0 - mech_eff) * pwr_turb',
            HPX_mech={'val': 320., 'units': 'hp'},
            pwr_turb ={'val': 10000., 'units': 'hp'},
            mech_eff ={'val': 0.97}))
        self.add_subsystem('lp_mech_loss', om.ExecComp(
            'HPX_mech = (1.0 - mech_eff) * pwr_turb',
            HPX_mech={'val': 316., 'units': 'hp'},
            pwr_turb ={'val': 10000., 'units': 'hp'},
            mech_eff ={'val': 0.97}))

        #Create shaft instances. Note that LP shaft has 3 ports! => no gearbox
        self.add_subsystem('lp_shaft', pyc.Shaft(num_ports=3),promotes_inputs=[('Nmech','LP_Nmech')])
        self.add_subsystem('hp_shaft', pyc.Shaft(num_ports=2),promotes_inputs=[('Nmech','HP_Nmech')])
        self.add_subsystem('perf', pyc.Performance(num_nozzles=2, num_burners=1))

        # Now use the explicit connect method to make connections -- connect(<from>, <to>)

        #Connect the inputs to perf group
        self.connect('inlet.Fl_O:tot:P', 'perf.Pt2')
        self.connect('hpc.Fl_O:tot:P', 'perf.Pt3')
        self.connect('burner.Wfuel', 'perf.Wfuel_0')
        self.connect('inlet.F_ram', 'perf.ram_drag')
        self.connect('core_nozz.Fg', 'perf.Fg_0')
        self.connect('byp_nozz.Fg', 'perf.Fg_1')

        #LP-shaft connections
        self.connect('fan.trq', 'lp_shaft.trq_0')
        self.connect('lpc.trq', 'lp_shaft.trq_1')
        self.connect('lpt.trq', 'lp_shaft.trq_2')
        #HP-shaft connections
        self.connect('hpc.trq', 'hp_shaft.trq_0')
        self.connect('hpt.trq', 'hp_shaft.trq_1')
        # Mechanical losses → HPX (replaces fixed 250 hp, York η_HP = η_LP = 0.97)
        self.connect('hpt.power', 'hp_mech_loss.pwr_turb')
        self.connect('hp_mech_loss.HPX_mech', 'hp_shaft.HPX')
        self.connect('lpt.power', 'lp_mech_loss.pwr_turb')
        self.connect('lp_mech_loss.HPX_mech', 'lp_shaft.HPX')
        #Ideally expanding flow by conneting flight condition static pressure to nozzle exhaust pressure
        self.connect('fc.Fl_O:stat:P', 'core_nozz.Ps_exhaust')
        self.connect('fc.Fl_O:stat:P', 'byp_nozz.Ps_exhaust')
        
        for calc in ('ngv_calcs', 'bld_calcs'):
            self.connect('burner.Fl_O:tot:T',  f'{calc}.Tt_primary')
            self.connect('burner.Fl_O:tot:h',  f'{calc}.ht_primary')
            self.connect('burner.Fl_O:stat:W', f'{calc}.W_primary')
            self.connect('burner.Fl_O:tot:P',  f'{calc}.Pt_in')
            self.connect('hpt.Fl_O:tot:P',     f'{calc}.Pt_out')
            self.connect('bld3.Fl_O:tot:T',    f'{calc}.Tt_cool')
            self.connect('bld3.Fl_O:tot:h',    f'{calc}.ht_cool')
            self.connect('hpt.power',          f'{calc}.turb_pwr')

        self.connect('ngv_calcs.W_cool', 'cool_fracs.W_ngv')
        self.connect('bld_calcs.W_cool', 'cool_fracs.W_bld')
        self.connect('hpc.Fl_O:stat:W',  'cool_fracs.W_in')
        # cool_fracs outputs are NOT connected to bld3 inside Newton —
        # the outer loop in main sets bld3.cool3/4:frac_W externally each iteration

        #Create a balance component
        # Balances can be a bit confusing, here's some explanation -
        #   State Variables:
        #           (W)        Inlet mass flow rate to implictly balance thrust
        #                      LHS: perf.Fn  == RHS: Thrust requirement (set when TF is instantiated)
        #
        #           (FAR)      Fuel-air ratio to balance Tt4
        #                      LHS: burner.Fl_O:tot:T  == RHS: Tt4 target (set when TF is instantiated)
        #
        #           (lpt_PR)   LPT press ratio to balance shaft power on the low spool
        #           (hpt_PR)   HPT press ratio to balance shaft power on the high spool
        # Ref: look at the XDSM diagrams in the pyCycle paper and this:
        # http://openmdao.org/newdocs/versions/latest/features/building_blocks/components/balance_comp.html

        balance = self.add_subsystem('balance', om.BalanceComp())
        if design:
            balance.add_balance('W', units='lbm/s', eq_units='lbf')
            #Here balance.W is implicit state variable that is the OUTPUT of balance object
            self.connect('balance.W', 'fc.W') #Connect the output of balance to the relevant input
            self.connect('perf.Fn', 'balance.lhs:W')       #This statement makes perf.Fn the LHS of the balance eqn.
            self.promotes('balance', inputs=[('rhs:W', 'Fn_DES')])

            balance.add_balance('FAR', eq_units='degR', lower=1e-4, val=.017)
            self.connect('balance.FAR', 'burner.Fl_I:FAR')
            self.connect('burner.Fl_O:tot:T', 'balance.lhs:FAR')
            self.promotes('balance', inputs=[('rhs:FAR', 'T4_MAX')])

            # Note that for the following two balances the mult val is set to -1 so that the NET torque is zero
            balance.add_balance('lpt_PR', val=1.5, lower=1.001, upper=8,
                                eq_units='hp', use_mult=True, mult_val=-1)
            self.connect('balance.lpt_PR', 'lpt.PR')
            self.connect('lp_shaft.pwr_in_real', 'balance.lhs:lpt_PR')
            self.connect('lp_shaft.pwr_out_real', 'balance.rhs:lpt_PR')

            balance.add_balance('hpt_PR', val=1.5, lower=1.001, upper=8,
                                eq_units='hp', use_mult=True, mult_val=-1)
            self.connect('balance.hpt_PR', 'hpt.PR')
            self.connect('hp_shaft.pwr_in_real', 'balance.lhs:hpt_PR')
            self.connect('hp_shaft.pwr_out_real', 'balance.rhs:hpt_PR')


        else:

            #In OFF-DESIGN mode we need to redefine the balances:
            #   State Variables:
            #           (W)        Inlet mass flow rate to balance core flow area
            #                      LHS: core_nozz.Throat:stat:area == Area from DESIGN calculation
            #
            #           (FAR)      Fuel-air ratio to balance Thrust req.
            #                      LHS: perf.Fn  == RHS: Thrust requirement (set when TF is instantiated)
            #
            #           (BPR)      Bypass ratio to balance byp. noz. area
            #                      LHS: byp_nozz.Throat:stat:area == Area from DESIGN calculation
            #
            #           (lp_Nmech)   LP spool speed to balance shaft power on the low spool
            #           (hp_Nmech)   HP spool speed to balance shaft power on the high spool

            if self.options['throttle_mode'] == 'T4':
                balance.add_balance('FAR', val=0.017, lower=1e-4, eq_units='degR')
                self.connect('balance.FAR', 'burner.Fl_I:FAR')
                self.connect('burner.Fl_O:tot:T', 'balance.lhs:FAR')
                self.promotes('balance', inputs=[('rhs:FAR', 'T4_MAX')])

            elif self.options['throttle_mode'] == 'percent_thrust':
                balance.add_balance('FAR', val=0.017, lower=1e-4, eq_units='lbf', use_mult=True)
                self.connect('balance.FAR', 'burner.Fl_I:FAR')
                self.connect('perf.Fn', 'balance.rhs:FAR')
                self.promotes('balance', inputs=[('mult:FAR', 'PC'), ('lhs:FAR', 'Fn_max')])

            elif self.options['throttle_mode'] == 'fn_target':
                balance.add_balance('FAR', val=0.017, lower=1e-4, eq_units='lbf')
                self.connect('balance.FAR', 'burner.Fl_I:FAR')
                self.connect('perf.Fn', 'balance.lhs:FAR')
                self.promotes('balance', inputs=[('rhs:FAR', 'Fn_target')])


            balance.add_balance('W', units='lbm/s', lower=10., upper=1000., eq_units='inch**2')
            self.connect('balance.W', 'fc.W')
            self.connect('core_nozz.Throat:stat:area', 'balance.lhs:W')

            balance.add_balance('BPR', lower=2., upper=10., eq_units='inch**2')
            self.connect('balance.BPR', 'splitter.BPR')
            self.connect('byp_nozz.Throat:stat:area', 'balance.lhs:BPR')

            # Again for the following two balances the mult val is set to -1 so that the NET torque is zero
            balance.add_balance('lp_Nmech', val=1.5, units='rpm', lower=500., eq_units='hp', use_mult=True, mult_val=-1)
            self.connect('balance.lp_Nmech', 'LP_Nmech')
            self.connect('lp_shaft.pwr_in_real', 'balance.lhs:lp_Nmech')
            self.connect('lp_shaft.pwr_out_real', 'balance.rhs:lp_Nmech')

            balance.add_balance('hp_Nmech', val=1.5, units='rpm', lower=500., eq_units='hp', use_mult=True, mult_val=-1)
            self.connect('balance.hp_Nmech', 'HP_Nmech')
            self.connect('hp_shaft.pwr_in_real', 'balance.lhs:hp_Nmech')
            self.connect('hp_shaft.pwr_out_real', 'balance.rhs:hp_Nmech')
            
            self.add_subsystem('orifice', PhysicsCombustor())
            self.connect('hpc.Fl_O:tot:T',  'orifice.Tt3')
            self.connect('hpc.Fl_O:tot:P',  'orifice.Pt3')
            self.connect('hpc.Fl_O:stat:W', 'orifice.W')
            self.connect('orifice.dPqP',    'burner.dPqP')

            # Specify the order in which the subsystems are executed:

            # self.set_order(['balance', 'fc', 'inlet', 'fan', 'splitter', 'duct4', 'lpc', 'duct6', 'hpc', 'bld3', 'burner', 'hpt', 'duct11',
            #                 'lpt', 'duct13', 'core_nozz', 'byp_bld', 'duct15', 'byp_nozz', 'lp_shaft', 'hp_shaft', 'perf'])

        # Set up all the flow connections:
        self.pyc_connect_flow('fc.Fl_O', 'inlet.Fl_I')
        self.pyc_connect_flow('inlet.Fl_O', 'fan.Fl_I')
        self.pyc_connect_flow('fan.Fl_O', 'splitter.Fl_I')
        self.pyc_connect_flow('splitter.Fl_O1', 'duct4.Fl_I')
        self.pyc_connect_flow('duct4.Fl_O', 'lpc.Fl_I')
        self.pyc_connect_flow('lpc.Fl_O', 'duct6.Fl_I')
        self.pyc_connect_flow('duct6.Fl_O', 'hpc.Fl_I')
        self.pyc_connect_flow('hpc.Fl_O', 'bld3.Fl_I')
        self.pyc_connect_flow('bld3.Fl_O', 'burner.Fl_I')
        self.pyc_connect_flow('burner.Fl_O', 'hpt.Fl_I')
        self.pyc_connect_flow('hpt.Fl_O', 'duct11.Fl_I')
        self.pyc_connect_flow('duct11.Fl_O', 'lpt.Fl_I')
        self.pyc_connect_flow('lpt.Fl_O', 'duct13.Fl_I')
        self.pyc_connect_flow('duct13.Fl_O','core_nozz.Fl_I')
        self.pyc_connect_flow('splitter.Fl_O2', 'byp_bld.Fl_I')
        self.pyc_connect_flow('byp_bld.Fl_O', 'duct15.Fl_I')
        self.pyc_connect_flow('duct15.Fl_O', 'byp_nozz.Fl_I')

        #Bleed flows:
        self.pyc_connect_flow('hpc.cool1', 'lpt.cool1', connect_stat=False)
        self.pyc_connect_flow('hpc.cool2', 'lpt.cool2', connect_stat=False)
        self.pyc_connect_flow('bld3.cool3', 'hpt.cool3', connect_stat=False)
        self.pyc_connect_flow('bld3.cool4', 'hpt.cool4', connect_stat=False)

        #Specify solver settings:
        newton = self.nonlinear_solver = om.NewtonSolver()
        newton.options['atol'] = 1e-8

        # set this very small, so it never activates and we rely on atol
        newton.options['rtol'] = 1e-99
        newton.options['iprint'] = 2
        newton.options['maxiter'] = 50
        newton.options['solve_subsystems'] = True
        newton.options['max_sub_solves'] = 1000
        newton.options['reraise_child_analysiserror'] = False
        # ls = newton.linesearch = BoundsEnforceLS()
        ls = newton.linesearch = om.ArmijoGoldsteinLS()
        ls.options['maxiter'] = 3
        ls.options['rho'] = 0.75
        # ls.options['print_bound_enforce'] = True

        self.linear_solver = om.DirectSolver()

        super().setup()


def viewer(prob, pt, file=sys.stdout):
    """
    print a report of all the relevant cycle properties
    """

    if pt == 'DESIGN':
        MN = prob['DESIGN.fc.Fl_O:stat:MN']
        LPT_PR = prob['DESIGN.balance.lpt_PR']
        HPT_PR = prob['DESIGN.balance.hpt_PR']
        FAR = prob['DESIGN.balance.FAR']
    else:
        MN = prob[pt+'.fc.Fl_O:stat:MN']
        LPT_PR = prob[pt+'.lpt.PR']
        HPT_PR = prob[pt+'.hpt.PR']
        FAR = prob[pt+'.balance.FAR']

    summary_data = (MN[0], prob[pt+'.fc.alt'][0], prob[pt+'.inlet.Fl_O:stat:W'][0], prob[pt+'.perf.Fn'][0],
                        prob[pt+'.perf.Fg'][0], prob[pt+'.inlet.F_ram'][0], prob[pt+'.perf.OPR'][0],
                        prob[pt+'.perf.TSFC'][0], prob[pt+'.splitter.BPR'][0])

    print(file=file, flush=True)
    print(file=file, flush=True)
    print(file=file, flush=True)
    print("----------------------------------------------------------------------------", file=file, flush=True)
    print("                              POINT:", pt, file=file, flush=True)
    print("----------------------------------------------------------------------------", file=file, flush=True)
    print("                       PERFORMANCE CHARACTERISTICS", file=file, flush=True)
    print("    Mach      Alt       W      Fn      Fg    Fram     OPR     TSFC      BPR ", file=file, flush=True)
    print(" %7.5f  %7.1f %7.3f %7.1f %7.1f %7.1f %7.3f  %7.5f  %7.3f" %summary_data, file=file, flush=True)


    fs_names = ['fc.Fl_O', 'inlet.Fl_O', 'fan.Fl_O', 'splitter.Fl_O1', 'splitter.Fl_O2',
                'duct4.Fl_O', 'lpc.Fl_O', 'duct6.Fl_O', 'hpc.Fl_O', 'bld3.Fl_O', 'burner.Fl_O',
                'hpt.Fl_O', 'duct11.Fl_O', 'lpt.Fl_O', 'duct13.Fl_O', 'core_nozz.Fl_O', 'byp_bld.Fl_O',
                'duct15.Fl_O', 'byp_nozz.Fl_O']
    fs_full_names = [f'{pt}.{fs}' for fs in fs_names]
    pyc.print_flow_station(prob, fs_full_names, file=file)

    comp_names = ['fan', 'lpc', 'hpc']
    comp_full_names = [f'{pt}.{c}' for c in comp_names]
    pyc.print_compressor(prob, comp_full_names, file=file)

    pyc.print_burner(prob, [f'{pt}.burner'], file=file)

    turb_names = ['hpt', 'lpt']
    turb_full_names = [f'{pt}.{t}' for t in turb_names]
    pyc.print_turbine(prob, turb_full_names, file=file)

    noz_names = ['core_nozz', 'byp_nozz']
    noz_full_names = [f'{pt}.{n}' for n in noz_names]
    pyc.print_nozzle(prob, noz_full_names, file=file)

    shaft_names = ['hp_shaft', 'lp_shaft']
    shaft_full_names = [f'{pt}.{s}' for s in shaft_names]
    pyc.print_shaft(prob, shaft_full_names, file=file)

    bleed_names = ['hpc', 'bld3', 'byp_bld']
    bleed_full_names = [f'{pt}.{b}' for b in bleed_names]
    pyc.print_bleed(prob, bleed_full_names, file=file)


def _make_mphbtf(cfg):

    class MPhbtf(pyc.MPCycle):

        def setup(self):

            self.pyc_add_pnt('DESIGN', HBTF(thermo_method='CEA', hpt_map=cfg['hpt_map']))

            self.set_input_defaults('DESIGN.inlet.MN', 0.751)
            self.set_input_defaults('DESIGN.fan.MN', 0.4578)
            self.set_input_defaults('DESIGN.splitter.BPR', cfg['BPR'])
            self.set_input_defaults('DESIGN.splitter.MN1', 0.3104)
            self.set_input_defaults('DESIGN.splitter.MN2', 0.4518)
            self.set_input_defaults('DESIGN.duct4.MN', 0.3121)
            self.set_input_defaults('DESIGN.lpc.MN', 0.3059)
            self.set_input_defaults('DESIGN.duct6.MN', 0.3563)
            self.set_input_defaults('DESIGN.hpc.MN', 0.2442)
            self.set_input_defaults('DESIGN.bld3.MN', 0.3000)
            self.set_input_defaults('DESIGN.burner.MN', 0.1025)
            self.set_input_defaults('DESIGN.hpt.MN', 0.3650)
            self.set_input_defaults('DESIGN.duct11.MN', 0.3063)
            self.set_input_defaults('DESIGN.lpt.MN', 0.4127)
            self.set_input_defaults('DESIGN.duct13.MN', 0.4463)
            self.set_input_defaults('DESIGN.byp_bld.MN', 0.4489)
            self.set_input_defaults('DESIGN.duct15.MN', 0.4589)
            self.set_input_defaults('DESIGN.LP_Nmech', cfg['LP_Nmech'], units='rpm')
            self.set_input_defaults('DESIGN.HP_Nmech', cfg['HP_Nmech'], units='rpm')

            self.pyc_add_cycle_param('inlet.ram_recovery', cfg['ram_recovery'])
            self.pyc_add_cycle_param('duct4.dPqP', 0.0048)
            self.pyc_add_cycle_param('duct6.dPqP', 0.0101)
            # burner.dPqP is NOT a cycle param — DESIGN uses set_val, OD driven by orifice
            self.pyc_add_cycle_param('duct11.dPqP', 0.0051)
            self.pyc_add_cycle_param('duct13.dPqP', 0.0107)
            self.pyc_add_cycle_param('duct15.dPqP', 0.0149)
            self.pyc_add_cycle_param('core_nozz.Cv', 0.9933)
            self.pyc_add_cycle_param('byp_bld.bypBld:frac_W', 0.005)
            self.pyc_add_cycle_param('byp_nozz.Cv', 0.9939)
            self.pyc_add_cycle_param('hpc.cool1:frac_W', 0.0)
            self.pyc_add_cycle_param('hpc.cool1:frac_P', 0.5)
            self.pyc_add_cycle_param('hpc.cool1:frac_work', 0.5)
            self.pyc_add_cycle_param('hpc.cool2:frac_W', 0.0)
            self.pyc_add_cycle_param('hpc.cool2:frac_P', 0.55)
            self.pyc_add_cycle_param('hpc.cool2:frac_work', 0.5)
            self.pyc_add_cycle_param('hpc.cust:frac_P', 0.5)
            self.pyc_add_cycle_param('hpc.cust:frac_work', 0.5)
            self.pyc_add_cycle_param('hpc.cust:frac_W', 0.0445)
            self.pyc_add_cycle_param('hpt.cool3:frac_P', 1.0)
            self.pyc_add_cycle_param('hpt.cool4:frac_P', 0.0)
            self.pyc_add_cycle_param('lpt.cool1:frac_P', 1.0)
            self.pyc_add_cycle_param('lpt.cool2:frac_P', 0.0)

            self.od_pts = ['OD_full_pwr', 'OD_part_pwr']

            self.od_MNs = [0.8, 0.8]
            self.od_alts = [35000.0, 35000.0]
            self.od_Fn_target = [cfg['Fn_TOC'], cfg['Fn_crse']]
            self.od_dTs = [0.0, 0.0]

            self.pyc_add_pnt('OD_full_pwr', HBTF(design=False, thermo_method='CEA',
                                                  throttle_mode='T4', hpt_map=cfg['hpt_map']))

            self.set_input_defaults('OD_full_pwr.fc.MN', 0.8)
            self.set_input_defaults('OD_full_pwr.fc.alt', 35000, units='ft')
            self.set_input_defaults('OD_full_pwr.fc.dTs', 0., units='degR')

            self.pyc_add_pnt('OD_part_pwr', HBTF(design=False, thermo_method='CEA',
                                                   throttle_mode='percent_thrust', hpt_map=cfg['hpt_map']))

            self.set_input_defaults('OD_part_pwr.fc.MN', 0.8)
            self.set_input_defaults('OD_part_pwr.fc.alt', 35000, units='ft')
            self.set_input_defaults('OD_part_pwr.fc.dTs', 0., units='degR')

            self.connect('OD_full_pwr.perf.Fn', 'OD_part_pwr.Fn_max')

            # A4 sweep: constant Fn (fn_target throttle), variable NGV throat area
            self.a4_pts = []
            for i in range(len(cfg.get('a4_scalars', []))):
                pt = f'OD_A4_{i:03d}'
                self.a4_pts.append(pt)
                self.pyc_add_pnt(pt, HBTF(design=False, thermo_method='CEA',
                                          throttle_mode='fn_target', hpt_map=cfg['hpt_map']))
                self.set_input_defaults(f'{pt}.fc.MN',  0.8)
                self.set_input_defaults(f'{pt}.fc.alt', 35000., units='ft')
                self.set_input_defaults(f'{pt}.fc.dTs', 0.,     units='degR')

            # Mirror combustor_py_cycle._connect_od_scalars:
            # Connect all scalars for ALL OD points via pyc_connect_des_od,
            # EXCEPT hpt.s_Wp which must be free on A4 points so we can scale it.
            for comp in ['fan', 'lpc', 'hpc']:
                for sc in ['s_Wc', 's_PR', 's_eff', 's_Nc']:
                    self.pyc_connect_des_od(f'{comp}.{sc}', f'{comp}.{sc}')
                self.pyc_connect_des_od(f'{comp}.Fl_O:stat:area', f'{comp}.area')

            for sc in ['s_PR', 's_Np']:                  # hpt — s_Wp and s_eff excluded
                self.pyc_connect_des_od(f'hpt.{sc}', f'hpt.{sc}')
            self.pyc_connect_des_od('hpt.Fl_O:stat:area', 'hpt.area')

            for sc in ['s_Wp', 's_PR', 's_eff', 's_Np']:  # lpt — full set
                self.pyc_connect_des_od(f'lpt.{sc}', f'lpt.{sc}')
            self.pyc_connect_des_od('lpt.Fl_O:stat:area', 'lpt.area')

            # hpt.s_Wp and s_eff: design → standard OD only; A4 points read from VGT map
            for pt in self.od_pts:
                self.connect('DESIGN.hpt.s_Wp',  f'{pt}.hpt.s_Wp')
                self.connect('DESIGN.hpt.s_eff', f'{pt}.hpt.s_eff')

            self.pyc_connect_des_od('core_nozz.Throat:stat:area', 'balance.rhs:W')
            self.pyc_connect_des_od('byp_nozz.Throat:stat:area',  'balance.rhs:BPR')

            super().setup()

    return MPhbtf


def _interp_eff_at_design(map_obj):
    """Interpolate map efficiency at design point (alpha_des, Np_des, PR_des)."""
    from scipy.interpolate import RegularGridInterpolator
    ei = RegularGridInterpolator(
        (np.array(map_obj.alphaMap), np.array(map_obj.NpMap), np.array(map_obj.PRmap)),
        np.array(map_obj.effMap), method='linear', bounds_error=False, fill_value=None)
    return float(ei([[map_obj.defaults['alphaMap'],
                      map_obj.defaults['NpMap'],
                      map_obj.defaults['PRmap']]])[0])


def _run_scenario(CFG):
    """Run one HPT map scenario: design → OD → A4 sweep → per-scenario plots.

    Returns dict with a4, tsfc, t4 arrays for comparison plotting.
    """
    import time
    import pint
    import cantera as ct
    import matplotlib.pyplot as plt

    ureg = pint.UnitRegistry()
    Q_   = ureg.Quantity

    tag = 'fixed' if CFG.get('a4_mode', 'sWp') == 'sWp' else 'vgt'
    print(f'\n{"="*60}')
    print(f'  Scenario: {CFG["label"]}')
    print(f'  hpt_eff={CFG["hpt_eff"]:.4f}   a4_mode={CFG["a4_mode"]}')
    print(f'{"="*60}')

    # ── Pre-compute VGT map ratios for alpha mode ────────────────────────────
    # This is pure map math — no pyCycle needed. After the design solve we only
    # need des_s_Wp and des_s_eff (pyCycle outputs) to get the final scalers.
    if CFG.get('a4_scalars') and CFG.get('a4_mode') == 'alpha':
        from scipy.interpolate import RegularGridInterpolator
        _hmap  = CFG['hpt_map']
        _ei = RegularGridInterpolator(
            (np.array(_hmap.alphaMap), np.array(_hmap.NpMap), np.array(_hmap.PRmap)),
            np.array(_hmap.effMap), method='linear', bounds_error=False, fill_value=None)
        _wi = RegularGridInterpolator(
            (np.array(_hmap.alphaMap), np.array(_hmap.NpMap), np.array(_hmap.PRmap)),
            np.array(_hmap.WpMap),  method='linear', bounds_error=False, fill_value=None)
        _Np0 = _hmap.defaults['NpMap']   # 100.0
        _PR0 = _hmap.defaults['PRmap']   # 3.259
        _eff0 = _ei([[1.0, _Np0, _PR0]])[0]
        _Wp0  = _wi([[1.0, _Np0, _PR0]])[0]
        CFG['_Wp_ratios']  = [float(_wi([[a, _Np0, _PR0]])[0]) / _Wp0  for a in CFG['a4_scalars']]
        CFG['_eff_ratios'] = [float(_ei([[a, _Np0, _PR0]])[0]) / _eff0 for a in CFG['a4_scalars']]
        print(f'\nVGT map design point (alpha=1.0, Np={_Np0}, PR={_PR0}):  '
              f'eff={_eff0:.4f}  Wp={_Wp0:.4f}')
        print(f'  {"alpha":>6}  {"Wp_ratio":>10}  {"eff_ratio":>10}')
        for _a, _wr, _er in zip(CFG['a4_scalars'], CFG['_Wp_ratios'], CFG['_eff_ratios']):
            print(f'  {_a:6.3f}  {_wr:10.4f}  {_er:10.4f}')

    # Validation targets — York (2017) Table 3.5 (hf = 40.8 MJ/kg)
    TSFC_TOC_TARGET  = 0.6941    # /hr
    TSFC_CRSE_TARGET = 0.6793    # /hr

    prob = om.Problem()
    prob.model = mp_hbtf = _make_mphbtf(CFG)()
    prob.setup()

    # ── Component design parameters ───────────────────────────────────────────
    # burner.dPqP: DESIGN only — OD points are driven by the orifice component
    prob.set_val('DESIGN.burner.dPqP', CFG['burner_dPqP'])

    prob.set_val('DESIGN.fan.PR',  CFG['fan_PR'])
    prob.set_val('DESIGN.fan.eff', CFG['fan_eff'])

    prob.set_val('DESIGN.lpc.PR',  CFG['lpc_PR'])
    prob.set_val('DESIGN.lpc.eff', CFG['lpc_eff'])

    prob.set_val('DESIGN.hpc.PR',  CFG['hpc_PR'])
    prob.set_val('DESIGN.hpc.eff', CFG['hpc_eff'])

    prob.set_val('DESIGN.hpt.eff', CFG['hpt_eff'])
    prob.set_val('DESIGN.lpt.eff', CFG['lpt_eff'])

    # ── Design flight condition: TOC ──────────────────────────────────────────
    prob.set_val('DESIGN.fc.alt',  35000., units='ft')
    prob.set_val('DESIGN.fc.MN',   0.8)
    prob.set_val('DESIGN.T4_MAX',  CFG['T4_MAX'],  units='degR')
    prob.set_val('DESIGN.Fn_DES',  CFG['Fn_TOC'],  units='lbf')

    # OD_full_pwr = TOC: same T4, alt, MN as design → reproduces TOC condition
    prob.set_val('OD_full_pwr.T4_MAX', CFG['T4_MAX'], units='degR')

    # OD_part_pwr = cruise: PC fraction of TOC thrust
    prob.set_val('OD_part_pwr.PC', CFG['Fn_crse'] / CFG['Fn_TOC'])

    # ── Initial guesses — DESIGN ──────────────────────────────────────────────
    prob['DESIGN.balance.FAR']    = CFG['FAR_guess']
    prob['DESIGN.balance.W']      = CFG['W_guess']
    prob['DESIGN.balance.lpt_PR'] = CFG['lpt_PR_guess']
    prob['DESIGN.balance.hpt_PR'] = CFG['hpt_PR_guess']
    prob['DESIGN.fc.balance.Pt']  = 5.2
    prob['DESIGN.fc.balance.Tt']  = 440.0

    # ── Initial guesses — OD (maxiter=0 disables OD for the design-only solve) ─
    all_od_pts = ['OD_full_pwr', 'OD_part_pwr'] + getattr(mp_hbtf, 'a4_pts', [])
    for pt in all_od_pts:
        prob[pt+'.balance.FAR']      = CFG['FAR_guess']
        prob[pt+'.balance.W']        = CFG['W_guess']
        prob[pt+'.balance.BPR']      = CFG['BPR']
        prob[pt+'.balance.lp_Nmech'] = CFG['LP_Nmech']
        prob[pt+'.balance.hp_Nmech'] = CFG['HP_Nmech']
        prob[pt+'.hpt.PR']           = CFG['hpt_PR_guess']
        prob[pt+'.lpt.PR']           = CFG['lpt_PR_guess']
        prob[pt+'.fan.map.RlineMap'] = 2.0
        prob[pt+'.lpc.map.RlineMap'] = 2.0
        prob[pt+'.hpc.map.RlineMap'] = 2.0
        prob.model._get_subsystem(pt).nonlinear_solver.options['maxiter'] = 0
        if pt.startswith('OD_A4'):
            continue  # no Fn_target or other A4-specific guesses needed yet

    prob.set_solver_print(level=-1)
    prob.set_solver_print(level=2, depth=1)

    # ── HPT cooling fractions ─────────────────────────────────────────────────
    prob.set_val('DESIGN.bld3.cool3:frac_W', CFG['frac_ngv'])
    prob.set_val('DESIGN.bld3.cool4:frac_W', CFG['frac_bld'])

    print('\n── Design solve ──')
    t0 = time.time()
    prob.run_model()
    print(f'Design solved in {time.time()-t0:.1f}s')

    viewer_file = open(f'cfm56_{tag}_view.out', 'w')
    viewer(prob, 'DESIGN', file=viewer_file)
    viewer(prob, 'DESIGN')

    # ── Calibrate orifice CdA from converged design-point combustor inlet ─────
    W_des   = float(prob.get_val('DESIGN.hpc.Fl_O:stat:W', units='lbm/s')[0])
    Tt3_des = float(prob.get_val('DESIGN.hpc.Fl_O:tot:T',  units='degR')[0])
    Pt3_des = float(prob.get_val('DESIGN.hpc.Fl_O:tot:P',  units='psi')[0])

    W_si   = Q_(W_des,   'lb/s').to('kg/s').magnitude
    Tt3_K  = Q_(Tt3_des, 'degR').to('K').magnitude
    Pt3_Pa = Q_(Pt3_des, 'psi').to('Pa').magnitude

    CdA = calc_CdA_liner(Tt3_K, Pt3_Pa, W_si, dPqP_ref=CFG['burner_dPqP'])
    print(f'\nCalibrated CdA = {CdA:.6f} m²')

    # ── Seed OD state from converged design solution ──────────────────────────
    des_FAR      = float(prob.get_val('DESIGN.balance.FAR')[0])
    des_W        = float(prob.get_val('DESIGN.balance.W')[0])
    des_BPR      = float(prob.get_val('DESIGN.splitter.BPR')[0])
    des_hpt_PR   = float(prob.get_val('DESIGN.balance.hpt_PR')[0])
    des_lpt_PR   = float(prob.get_val('DESIGN.balance.lpt_PR')[0])
    des_fan_Rline = float(prob.get_val('DESIGN.fan.map.RlineMap')[0])
    des_lpc_Rline = float(prob.get_val('DESIGN.lpc.map.RlineMap')[0])
    des_hpc_Rline = float(prob.get_val('DESIGN.hpc.map.RlineMap')[0])

    for pt in ['OD_full_pwr', 'OD_part_pwr']:
        prob[f'{pt}.balance.FAR']      = des_FAR
        prob[f'{pt}.balance.W']        = des_W
        prob[f'{pt}.balance.BPR']      = des_BPR
        prob[f'{pt}.balance.hp_Nmech'] = CFG['HP_Nmech']
        prob[f'{pt}.balance.lp_Nmech'] = CFG['LP_Nmech']
        prob[f'{pt}.hpt.PR']           = des_hpt_PR
        prob[f'{pt}.lpt.PR']           = des_lpt_PR
        prob[f'{pt}.fan.map.RlineMap'] = des_fan_Rline
        prob[f'{pt}.lpc.map.RlineMap'] = des_lpc_Rline
        prob[f'{pt}.hpc.map.RlineMap'] = des_hpc_Rline

    # ── Stage 1: solve standard OD (A4 remain disabled) ─────────────────────
    des_s_Wp  = float(prob.get_val('DESIGN.hpt.s_Wp')[0])
    des_s_eff = float(prob.get_val('DESIGN.hpt.s_eff')[0])
    a4_mode   = CFG.get('a4_mode', 'sWp')

    for pt in ['OD_full_pwr', 'OD_part_pwr']:
        prob.model._get_subsystem(pt).nonlinear_solver.options['maxiter'] = 50
        prob.set_val(f'{pt}.orifice.CdA', CdA)
        prob.set_val(f'{pt}.bld3.cool3:frac_W', CFG['frac_ngv'])
        prob.set_val(f'{pt}.bld3.cool4:frac_W', CFG['frac_bld'])

    print('\n── OD solve (standard) ──')
    t1 = time.time()
    prob.run_model()
    print(f'Standard OD solved in {time.time()-t1:.1f}s')

    # ── Stage 2: seed A4 from converged OD_part_pwr (cruise) and run sweep ──────
    # Seed from OD_part_pwr because fn_const = cruise thrust; OD_part_pwr is the
    # closest converged point and gives Newton the best basin for fn_target balance.
    if CFG.get('a4_scalars'):
        _seed_pt     = 'OD_part_pwr'
        od_FAR       = float(prob.get_val(f'{_seed_pt}.balance.FAR')[0])
        od_W         = float(prob.get_val(f'{_seed_pt}.balance.W')[0])
        od_BPR       = float(prob.get_val(f'{_seed_pt}.balance.BPR')[0])
        od_hp_Nmech  = float(prob.get_val(f'{_seed_pt}.balance.hp_Nmech', units='rpm')[0])
        od_lp_Nmech  = float(prob.get_val(f'{_seed_pt}.balance.lp_Nmech', units='rpm')[0])
        od_hpt_PR    = float(prob.get_val(f'{_seed_pt}.hpt.PR')[0])
        od_lpt_PR    = float(prob.get_val(f'{_seed_pt}.lpt.PR')[0])
        od_fan_Rline = float(prob.get_val(f'{_seed_pt}.fan.map.RlineMap')[0])
        od_lpc_Rline = float(prob.get_val(f'{_seed_pt}.lpc.map.RlineMap')[0])
        od_hpc_Rline = float(prob.get_val(f'{_seed_pt}.hpc.map.RlineMap')[0])

        _Fn_target_a4 = CFG.get('fn_const', CFG['Fn_TOC'])

        # Set static inputs for all A4 points upfront
        for i, a4 in enumerate(CFG['a4_scalars']):
            pt = f'OD_A4_{i:03d}'
            prob.set_val(f'{pt}.Fn_target', _Fn_target_a4, units='lbf')
            if a4_mode == 'alpha':
                prob.set_val(f'{pt}.hpt.s_Wp',  des_s_Wp  * CFG['_Wp_ratios'][i])
                prob.set_val(f'{pt}.hpt.s_eff', des_s_eff * CFG['_eff_ratios'][i])
            else:
                prob.set_val(f'{pt}.hpt.s_Wp',  des_s_Wp * a4)
                prob.set_val(f'{pt}.hpt.s_eff', des_s_eff)
            prob.set_val(f'{pt}.orifice.CdA', CdA)
            prob.set_val(f'{pt}.bld3.cool3:frac_W', CFG['frac_ngv'])
            prob.set_val(f'{pt}.bld3.cool4:frac_W', CFG['frac_bld'])

        # Standard OD already converged; keep at low maxiter so it doesn't drift
        for pt in ['OD_full_pwr', 'OD_part_pwr']:
            prob.model._get_subsystem(pt).nonlinear_solver.options['maxiter'] = 5

        # Solve A4 points one at a time, seeding each from the previous converged
        # point to stay in the correct Newton basin as alpha varies smoothly.
        seed = dict(FAR=od_FAR, W=od_W, BPR=od_BPR,
                    hp_Nmech=od_hp_Nmech, lp_Nmech=od_lp_Nmech,
                    hpt_PR=od_hpt_PR, lpt_PR=od_lpt_PR,
                    fan_Rline=od_fan_Rline, lpc_Rline=od_lpc_Rline,
                    hpc_Rline=od_hpc_Rline)

        print('\n── OD solve (A4 sweep, sequential) ──')
        t2 = time.time()
        for i, a4 in enumerate(CFG['a4_scalars']):
            pt = f'OD_A4_{i:03d}'
            prob[f'{pt}.balance.FAR']      = seed['FAR']
            prob[f'{pt}.balance.W']        = seed['W']
            prob[f'{pt}.balance.BPR']      = seed['BPR']
            prob[f'{pt}.balance.hp_Nmech'] = seed['hp_Nmech']
            prob[f'{pt}.balance.lp_Nmech'] = seed['lp_Nmech']
            prob[f'{pt}.hpt.PR']           = seed['hpt_PR']
            prob[f'{pt}.lpt.PR']           = seed['lpt_PR']
            prob[f'{pt}.fan.map.RlineMap'] = seed['fan_Rline']
            prob[f'{pt}.lpc.map.RlineMap'] = seed['lpc_Rline']
            prob[f'{pt}.hpc.map.RlineMap'] = seed['hpc_Rline']

            prob.model._get_subsystem(pt).nonlinear_solver.options['maxiter'] = 50
            prob.run_model()
            prob.model._get_subsystem(pt).nonlinear_solver.options['maxiter'] = 0

            fn = float(prob.get_val(f'{pt}.perf.Fn', units='lbf')[0])
            if abs(fn - _Fn_target_a4) < 50.:
                seed = dict(
                    FAR       = float(prob.get_val(f'{pt}.balance.FAR')[0]),
                    W         = float(prob.get_val(f'{pt}.balance.W')[0]),
                    BPR       = float(prob.get_val(f'{pt}.balance.BPR')[0]),
                    hp_Nmech  = float(prob.get_val(f'{pt}.balance.hp_Nmech', units='rpm')[0]),
                    lp_Nmech  = float(prob.get_val(f'{pt}.balance.lp_Nmech', units='rpm')[0]),
                    hpt_PR    = float(prob.get_val(f'{pt}.hpt.PR')[0]),
                    lpt_PR    = float(prob.get_val(f'{pt}.lpt.PR')[0]),
                    fan_Rline = float(prob.get_val(f'{pt}.fan.map.RlineMap')[0]),
                    lpc_Rline = float(prob.get_val(f'{pt}.lpc.map.RlineMap')[0]),
                    hpc_Rline = float(prob.get_val(f'{pt}.hpc.map.RlineMap')[0]),
                )
            print(f'  A4={a4:.3f}  Fn={fn:.1f}  {"OK" if abs(fn - _Fn_target_a4) < 50. else "BAD"}')
        print(f'A4 sweep solved in {time.time()-t2:.1f}s')

    viewer(prob, 'OD_full_pwr', file=viewer_file)
    viewer(prob, 'OD_part_pwr', file=viewer_file)
    viewer_file.close()

    # ── Validation summary vs York (2017) Table 3.5 ───────────────────────────
    tsfc_toc  = float(prob.get_val('OD_full_pwr.perf.TSFC')[0])
    tsfc_crse = float(prob.get_val('OD_part_pwr.perf.TSFC')[0])
    fn_toc    = float(prob.get_val('OD_full_pwr.perf.Fn', units='lbf')[0])
    fn_crse   = float(prob.get_val('OD_part_pwr.perf.Fn', units='lbf')[0])

    print('\n' + '='*60)
    print('  Validation vs York (2017) Table 3.5')
    print('='*60)
    print(f'  {"Point":<10} {"Fn (lbf)":>10} {"TSFC (/hr)":>12} '
          f'{"Target":>10} {"Error (%)":>10}')
    print(f'  {"-"*54}')
    print(f'  {"TOC":<10} {fn_toc:10.1f} {tsfc_toc:12.4f} '
          f'{TSFC_TOC_TARGET:10.4f} '
          f'{(tsfc_toc - TSFC_TOC_TARGET)/TSFC_TOC_TARGET*100:+10.2f}')
    print(f'  {"Cruise":<10} {fn_crse:10.1f} {tsfc_crse:12.4f} '
          f'{TSFC_CRSE_TARGET:10.4f} '
          f'{(tsfc_crse - TSFC_CRSE_TARGET)/TSFC_CRSE_TARGET*100:+10.2f}')
    print('='*60)

    a4_arr, t4_arr, tsfc_arr = [], [], []
    fan_pr_arr, lpc_pr_arr   = [], []
    hpc_pr_arr, hpc_eff_arr, hpc_wc_arr, hpc_nc_arr = [], [], [], []
    dpqp_arr   = []
    eta_gg_arr = []

    if CFG.get('a4_scalars'):
        _Fn_target = CFG.get('fn_const', CFG['Fn_TOC'])
        print('\n' + '='*60)
        print('  A4 Sweep — constant Fn, variable NGV throat area')
        print(f'  Mode: {a4_mode}   Fn_target = {_Fn_target:.1f} lbf')
        print('='*60)
        print(f'  {"A4":>6}  {"Fn(lbf)":>9}  {"T4(R)":>7}  {"TSFC":>7}  {"OPR":>7}  {"HPT_PR":>7}  {"HP_N(rpm)":>10}  {"Conv":>5}')
        print(f'  {"-"*68}')

        # Cp for combustion products at stations 4 and 4.5 — from reference table
        _CP4  = 1.280  # kJ/kg/K, combustor exit (hot products, ~1587 K)
        _CP45 = 1.184  # kJ/kg/K, HPT exit (hot products, ~1142 K)
        _air_ct = ct.Solution('air.yaml')

        for i, a4 in enumerate(CFG['a4_scalars']):
            pt   = f'OD_A4_{i:03d}'
            fn   = float(prob.get_val(f'{pt}.perf.Fn',           units='lbf')[0])
            t4   = float(prob.get_val(f'{pt}.burner.Fl_O:tot:T', units='degR')[0])
            tsfc = float(prob.get_val(f'{pt}.perf.TSFC')[0])
            opr  = float(prob.get_val(f'{pt}.perf.OPR')[0])
            hpr  = float(prob.get_val(f'{pt}.hpt.PR')[0])
            hpn  = float(prob.get_val(f'{pt}.balance.hp_Nmech',  units='rpm')[0])
            converged = abs(fn - _Fn_target) < 50.
            flag = '  OK' if converged else ' BAD'
            print(f'  {a4:6.3f}  {fn:9.1f}  {t4:7.1f}  {tsfc:7.4f}  {opr:7.3f}  {hpr:7.4f}  {hpn:10.1f}  {flag}')

            if converged:
                a4_arr.append(a4)
                t4_arr.append(t4 * 5/9)
                tsfc_arr.append(tsfc)
                fan_pr_arr.append(float(prob.get_val(f'{pt}.fan.PR')[0]))
                lpc_pr_arr.append(float(prob.get_val(f'{pt}.lpc.PR')[0]))
                hpc_pr_arr.append(float(prob.get_val(f'{pt}.hpc.PR')[0]))
                hpc_eff_arr.append(float(prob.get_val(f'{pt}.hpc.eff')[0]))
                hpc_wc_arr.append(float(prob.get_val(f'{pt}.hpc.map.WcMap')[0]))
                hpc_nc_arr.append(float(prob.get_val(f'{pt}.hpc.map.NcMap')[0]))
                pt3 = float(prob.get_val(f'{pt}.burner.Fl_I:tot:P', units='psi')[0])
                pt4 = float(prob.get_val(f'{pt}.burner.Fl_O:tot:P', units='psi')[0])
                dpqp_arr.append((pt3 - pt4) / pt3)
                # GG thermal efficiency: (Cp45·Tt45 - Cp25·Tt25) / (Cp4·Tt4 - Cp3·Tt3)
                # Fixed Cp for hot products (stations 4, 45) from reference;
                # air Cp at stations 25 and 3 from Cantera (T-dependent, ideal gas).
                T_t45_K = float(prob.get_val(f'{pt}.hpt.Fl_O:tot:T',    units='degR')[0]) * 5/9
                T_t25_K = float(prob.get_val(f'{pt}.hpc.Fl_I:tot:T',    units='degR')[0]) * 5/9
                T_t4_K  = float(prob.get_val(f'{pt}.burner.Fl_O:tot:T', units='degR')[0]) * 5/9
                T_t3_K  = float(prob.get_val(f'{pt}.hpc.Fl_O:tot:T',    units='degR')[0]) * 5/9
                _air_ct.TP = T_t25_K, 101325.0
                cp_25 = _air_ct.cp_mass / 1000.0   # kJ/kg/K
                _air_ct.TP = T_t3_K,  101325.0
                cp_3  = _air_ct.cp_mass / 1000.0   # kJ/kg/K
                eta_gg_arr.append(
                    (_CP45 * T_t45_K - cp_25 * T_t25_K) /
                    (_CP4  * T_t4_K  - cp_3  * T_t3_K)
                )
        print('='*60)

        _xlabel = ('NGV throat area fraction  α  (A4/A4_des)'
                   if a4_mode == 'alpha' else 'A4 scalar  (s_Wp relative to design)')
        _title_sfx = (f'Cruise: MN 0.8 / 35 000 ft, const Fn = {_Fn_target:.0f} lbf  '
                      f'({len(a4_arr)}/{len(CFG["a4_scalars"])} pts converged)')

        # ── Plot 1: TSFC vs A4 ───────────────────────────────────────────────
        fig1, ax1 = plt.subplots(figsize=(7, 4))
        ax1.plot(a4_arr, tsfc_arr, 'o-', color='steelblue', lw=1.8, ms=5)
        ax1.axvline(1.0, color='gray', ls='--', lw=0.8, label='design α')
        ax1.set_xlabel(_xlabel)
        ax1.set_ylabel('TSFC  (lbm/hr/lbf)')
        ax1.set_title(f'CFM56 {CFG["label"]} — TSFC vs NGV throat area\n' + _title_sfx)
        ax1.legend()
        ax1.grid(True, alpha=0.3)
        fig1.tight_layout()
        fig1.savefig(f'cfm56_{tag}_tsfc.png', dpi=150)
        print(f'  Saved cfm56_{tag}_tsfc.png')

        # ── Plot 2: T4 vs A4 ─────────────────────────────────────────────────
        fig2, ax2 = plt.subplots(figsize=(7, 4))
        ax2.plot(a4_arr, t4_arr, 's-', color='firebrick', lw=1.8, ms=5, label='T4 (TIT)')
        ax2.axvline(1.0, color='gray', ls='--', lw=0.8, label='design α')
        ax2.set_xlabel(_xlabel)
        ax2.set_ylabel('Temperature  (K)')
        ax2.set_title(f'CFM56 {CFG["label"]} — turbine inlet temperature vs NGV throat area\n' + _title_sfx)
        ax2.legend()
        ax2.grid(True, alpha=0.3)
        fig2.tight_layout()
        fig2.savefig(f'cfm56_{tag}_T4.png', dpi=150)
        print(f'  Saved cfm56_{tag}_T4.png')

        # ── Plot 3: Fan PR and LPC PR vs A4 ──────────────────────────────────
        fig3, (ax3a, ax3b) = plt.subplots(1, 2, figsize=(12, 4))
        ax3a.plot(a4_arr, fan_pr_arr, 'o-', color='darkorchid', lw=1.8, ms=5)
        ax3a.axvline(1.0, color='gray', ls='--', lw=0.8, label='design α')
        ax3a.set_xlabel(_xlabel)
        ax3a.set_ylabel('Fan PR')
        ax3a.set_title('Fan Pressure Ratio vs A4')
        ax3a.legend()
        ax3a.grid(True, alpha=0.3)

        ax3b.plot(a4_arr, lpc_pr_arr, 'o-', color='darkorange', lw=1.8, ms=5)
        ax3b.axvline(1.0, color='gray', ls='--', lw=0.8, label='design α')
        ax3b.set_xlabel(_xlabel)
        ax3b.set_ylabel('LPC PR')
        ax3b.set_title('LPC Pressure Ratio vs A4')
        ax3b.legend()
        ax3b.grid(True, alpha=0.3)

        fig3.suptitle(f'CFM56 {CFG["label"]} — Fan & LPC pressure ratios\n' + _title_sfx, fontsize=10)
        fig3.tight_layout()
        fig3.savefig(f'cfm56_{tag}_comp_pr.png', dpi=150)
        print(f'  Saved cfm56_{tag}_comp_pr.png')

        # ── Plot 4: HPC map with operating points ────────────────────────────
        fig4, ax4 = plt.subplots(figsize=(10, 7))

        # Map background — mirrors draw_compressor_map_background in combustor_turboshaft.py
        hpc_sys  = prob.model._get_subsystem('DESIGN.hpc')
        hpc_mdat = hpc_sys.options['map_data']
        s_Wc_h   = float(prob.get_val('DESIGN.hpc.s_Wc')[0])
        s_PR_h   = float(prob.get_val('DESIGN.hpc.s_PR')[0])
        s_eff_h  = float(prob.get_val('DESIGN.hpc.s_eff')[0])
        s_Nc_h   = float(prob.get_val('DESIGN.hpc.s_Nc')[0])

        _, _Nc_grid = np.meshgrid(hpc_mdat.RlineMap, hpc_mdat.NcMap, sparse=False)
        _Wc_bg  = hpc_mdat.WcMap[0, :, :]  * s_Wc_h
        _PR_bg  = (hpc_mdat.PRmap[0, :, :] - 1.0) * s_PR_h + 1.0
        _eff_bg = hpc_mdat.effMap[0, :, :] * s_eff_h
        _Nc_bg  = _Nc_grid * s_Nc_h

        eff_levels = np.linspace(0.60, 0.92, 20)
        eff_cf4 = ax4.contourf(_Wc_bg, _PR_bg, _eff_bg,
                               levels=eff_levels, cmap='viridis', alpha=0.85, zorder=1)
        eff_cs4 = ax4.contour(_Wc_bg, _PR_bg, _eff_bg,
                              levels=eff_levels[::4], colors='k', linewidths=0.5, zorder=2)
        ax4.clabel(eff_cs4, fmt='%.2f', fontsize=6, inline=True, inline_spacing=2)

        nc_levels = np.unique(np.round(hpc_mdat.NcMap * s_Nc_h, 4))
        nc_cs4 = ax4.contour(_Wc_bg, _PR_bg, _Nc_bg,
                             levels=nc_levels, colors='dimgray',
                             linewidths=0.8, linestyles='solid', zorder=2)
        ax4.clabel(nc_cs4, fmt='%.2f', fontsize=6, inline=True, inline_spacing=2)

        stall_idx = np.argsort(_Wc_bg[:, 0])
        ax4.plot(_Wc_bg[stall_idx, 0], _PR_bg[stall_idx, 0],
                 'r-', lw=2.0, zorder=3, label='Stall line')

        cb_eff4 = fig4.colorbar(eff_cf4, ax=ax4, shrink=0.75, pad=0.02)
        cb_eff4.set_label('HPC adiabatic efficiency  η  (—)', fontsize=9)

        # A4 sweep operating trajectory — WcMap is raw map Wc; physical = WcMap * s_Wc
        hpc_wc_phys = [w * s_Wc_h for w in hpc_wc_arr]
        sc4 = ax4.scatter(hpc_wc_phys, hpc_pr_arr, c=a4_arr, cmap='plasma',
                          s=70, zorder=6, edgecolors='k', linewidths=0.5)
        ax4.plot(hpc_wc_phys, hpc_pr_arr, '-', color='white',
                 lw=1.5, alpha=0.7, zorder=5)
        cb_a44 = fig4.colorbar(sc4, ax=ax4, shrink=0.45, pad=0.12)
        cb_a44.set_label(_xlabel, fontsize=9)

        if a4_arr:
            idx_des = int(np.argmin(np.abs(np.array(a4_arr) - 1.0)))
            ax4.plot(hpc_wc_phys[idx_des], hpc_pr_arr[idx_des],
                     '*', color='gold', ms=16, zorder=7,
                     markeredgecolor='k', markeredgewidth=0.8, label='α = 1.0')

        ax4.legend(fontsize=9, facecolor='k', labelcolor='white',
                   edgecolor='white', framealpha=0.8, loc='upper left')
        ax4.set_xlabel('HPC corrected flow  $W_c$  (lbm/s)', fontsize=11)
        ax4.set_ylabel('HPC Pressure Ratio', fontsize=11)
        ax4.set_title(f'CFM56 {CFG["label"]} — HPC map A4 sweep\n' + _title_sfx)
        ax4.grid(True, alpha=0.15, color='white', zorder=0)
        fig4.tight_layout()
        fig4.savefig(f'cfm56_{tag}_hpc_map.png', dpi=150)
        print(f'  Saved cfm56_{tag}_hpc_map.png')

        # ── Plot 5: HPC efficiency, HPC PR, combustor dP/P vs A4 ─────────────
        # ── Plot 5: HPC adiabatic efficiency vs A4 ───────────────────────────
        fig5, ax5 = plt.subplots(figsize=(7, 4))
        ax5.plot(a4_arr, [e * 100 for e in hpc_eff_arr], 'o-',
                 color='seagreen', lw=1.8, ms=5)
        ax5.axvline(1.0, color='gray', ls='--', lw=0.8, label='design α')
        ax5.set_xlabel(_xlabel)
        ax5.set_ylabel('HPC adiabatic efficiency  η  (%)')
        ax5.set_title(f'CFM56 {CFG["label"]} — HPC efficiency\n' + _title_sfx)
        ax5.legend()
        ax5.grid(True, alpha=0.3)
        fig5.tight_layout()
        fig5.savefig(f'cfm56_{tag}_hpc_eff.png', dpi=150)
        print(f'  Saved cfm56_{tag}_hpc_eff.png')

        # ── Plot 6: HPC PR vs A4 ─────────────────────────────────────────────
        fig6, ax6 = plt.subplots(figsize=(7, 4))
        ax6.plot(a4_arr, hpc_pr_arr, 'o-', color='steelblue', lw=1.8, ms=5)
        ax6.axvline(1.0, color='gray', ls='--', lw=0.8, label='design α')
        ax6.set_xlabel(_xlabel)
        ax6.set_ylabel('HPC Pressure Ratio')
        ax6.set_title(f'CFM56 {CFG["label"]} — HPC pressure ratio\n' + _title_sfx)
        ax6.legend()
        ax6.grid(True, alpha=0.3)
        fig6.tight_layout()
        fig6.savefig(f'cfm56_{tag}_hpc_pr.png', dpi=150)
        print(f'  Saved cfm56_{tag}_hpc_pr.png')

        # ── Plot 7: Combustor ΔP/P vs A4 ─────────────────────────────────────
        fig7, ax7 = plt.subplots(figsize=(7, 4))
        ax7.plot(a4_arr, [d * 100 for d in dpqp_arr], 'o-',
                 color='firebrick', lw=1.8, ms=5)
        ax7.axvline(1.0, color='gray', ls='--', lw=0.8, label='design α')
        ax7.set_xlabel(_xlabel)
        ax7.set_ylabel('Combustor  ΔP/P  (%)')
        ax7.set_title(f'CFM56 {CFG["label"]} — combustor pressure loss\n' + _title_sfx)
        ax7.legend()
        ax7.grid(True, alpha=0.3)
        fig7.tight_layout()
        fig7.savefig(f'cfm56_{tag}_dpqp.png', dpi=150)
        print(f'  Saved cfm56_{tag}_dpqp.png')

        # ── Plot 8: GG thermal efficiency vs A4 ──────────────────────────────
        # η_GG = (Cp45·Tt45 - Cp25·Tt25) / (Cp4·Tt4 - Cp3·Tt3)
        # Isolates HPC+combustor+HPT losses from fan, LPT, and propulsive effects.
        fig8, ax8 = plt.subplots(figsize=(7, 4))
        ax8.plot(a4_arr, [e * 100 for e in eta_gg_arr], 'o-',
                 color='darkorchid', lw=1.8, ms=5)
        ax8.axvline(1.0, color='gray', ls='--', lw=0.8, label='design α')
        ax8.set_xlabel(_xlabel)
        ax8.set_ylabel('GG thermal efficiency  η_GG  (%)')
        ax8.set_title(f'CFM56 {CFG["label"]} — gas generator thermal efficiency\n'
                      r'$\eta_{GG} = (c_{p,45}T_{t45} - c_{p,25}T_{t25})\ /\ (c_{p,4}T_{t4} - c_{p,3}T_{t3})$'
                      + '\n' + _title_sfx)
        ax8.legend()
        ax8.grid(True, alpha=0.3)
        fig8.tight_layout()
        fig8.savefig(f'cfm56_{tag}_eta_gg.png', dpi=150)
        print(f'  Saved cfm56_{tag}_eta_gg.png')

        plt.close('all')

    return {
        'a4': a4_arr, 'tsfc': tsfc_arr, 't4': t4_arr, 'label': CFG['label'],
        'a4_mode': a4_mode, 'xlabel': _xlabel if CFG.get('a4_scalars') else None,
        'fan_pr': fan_pr_arr, 'lpc_pr': lpc_pr_arr,
        'hpc_pr': hpc_pr_arr, 'hpc_eff': hpc_eff_arr,
        'hpc_wc': hpc_wc_arr, 'hpc_nc': hpc_nc_arr,
        'dpqp': dpqp_arr, 'eta_gg': eta_gg_arr,
        # HPC map background (design-point map scalars) for the combined map plot
        'hpc_map_data':  hpc_mdat if CFG.get('a4_scalars') else None,
        's_Wc': s_Wc_h if CFG.get('a4_scalars') else None,
        's_PR':  s_PR_h if CFG.get('a4_scalars') else None,
        's_eff': s_eff_h if CFG.get('a4_scalars') else None,
        's_Nc':  s_Nc_h if CFG.get('a4_scalars') else None,
    }


if __name__ == "__main__":

    import time
    import matplotlib.pyplot as plt

    eff_fixed = _interp_eff_at_design(CFM56HPTMapFixed)
    eff_vgt   = _interp_eff_at_design(CFM56HPTMapVGT)
    print(f'Design η  —  Fixed map: {eff_fixed*100:.3f}%    VGT map: {eff_vgt*100:.3f}%')

    BASE = dict(
        fan_PR       = 1.685,
        fan_eff      = 0.9005,
        lpc_PR       = 1.935,
        lpc_eff      = 0.9306,
        hpc_PR       = 9.369,
        hpc_eff      = 0.9030,
        lpt_eff      = 0.8851,
        burner_dPqP  = 0.06,
        ram_recovery = 0.98,
        T4_MAX       = 2857.0,
        Fn_TOC       = 5961.9,
        Fn_crse      = 5496.4,
        LP_Nmech     = 4666.1,
        HP_Nmech     = 14705.7,
        BPR          = 5.105,
        frac_ngv     = 0.07,
        frac_bld     = 0.12,
        FAR_guess    = 0.025,
        W_guess      = 300.,
        hpt_PR_guess = 3.0,
        lpt_PR_guess = 4.0,
        a4_scalars   = list(np.linspace(0.85, 1.05, 15)),
        fn_const     = 5496.4,
    )

    SCENARIOS = [
        {**BASE,
         'hpt_map': CFM56HPTMapFixed,
         'hpt_eff': eff_fixed,
         'a4_mode': 'sWp',
         'label':   'Fixed NGV  (s_Wp scaling)'},
        {**BASE,
         'hpt_map': CFM56HPTMapVGT,
         'hpt_eff': eff_vgt,
         'a4_mode': 'alpha',
         'label':   'VGT  (α scheduling)'},
    ]

    t_wall = time.time()
    all_results = [_run_scenario(s) for s in SCENARIOS]

    # ── Comparison plots — Fixed (s_Wp) vs VGT (α), every metric ──────────────
    _xlabel_cmp = 'NGV throat area fraction  α / s_Wp scalar  (relative to design)'
    _colors     = ['steelblue', 'firebrick']
    _markers    = ['o', 's']

    def _combined_plot(key, ylabel, title, fname, pct=False):
        fig, ax = plt.subplots(figsize=(8, 5))
        any_data = False
        for r, col, mk in zip(all_results, _colors, _markers):
            if r['a4'] and r[key]:
                any_data = True
                yvals = [v * 100 for v in r[key]] if pct else r[key]
                ax.plot(r['a4'], yvals, f'{mk}-', color=col, lw=1.8, ms=5, label=r['label'])
        if not any_data:
            plt.close(fig)
            return
        ax.axvline(1.0, color='gray', ls='--', lw=0.8, label='design point')
        ax.set_xlabel(_xlabel_cmp)
        ax.set_ylabel(ylabel)
        ax.set_title(f'CFM56  —  {title}: Fixed (s_Wp) vs VGT (α)')
        ax.legend()
        ax.grid(True, alpha=0.3)
        fig.tight_layout()
        fig.savefig(fname, dpi=150)
        print(f'  Saved {fname}')

    _combined_plot('tsfc',    'TSFC  (lbm/hr/lbf)',                 'TSFC vs NGV area',
                   'fixed_vs_vgt_tsfc.png')
    _combined_plot('t4',      'Turbine inlet temperature  T4  (K)', 'T4 vs NGV area',
                   'fixed_vs_vgt_T4.png')
    _combined_plot('fan_pr',  'Fan PR',                             'Fan pressure ratio vs NGV area',
                   'fixed_vs_vgt_fan_pr.png')
    _combined_plot('lpc_pr',  'LPC PR',                             'LPC pressure ratio vs NGV area',
                   'fixed_vs_vgt_lpc_pr.png')
    _combined_plot('hpc_pr',  'HPC PR',                             'HPC pressure ratio vs NGV area',
                   'fixed_vs_vgt_hpc_pr.png')
    _combined_plot('hpc_eff', 'HPC adiabatic efficiency  η  (%)',   'HPC efficiency vs NGV area',
                   'fixed_vs_vgt_hpc_eff.png', pct=True)
    _combined_plot('dpqp',    'Combustor  ΔP/P  (%)',               'combustor pressure loss vs NGV area',
                   'fixed_vs_vgt_dpqp.png', pct=True)
    _combined_plot('eta_gg',  'GG thermal efficiency  η_GG  (%)',   'gas generator thermal efficiency vs NGV area',
                   'fixed_vs_vgt_eta_gg.png', pct=True)

    # ── Combined HPC map — both scenarios' operating trajectories overlaid ────
    _map_ref = next((r for r in all_results if r.get('hpc_map_data') is not None), None)
    if _map_ref is not None:
        fig_map, ax_map = plt.subplots(figsize=(10, 7))
        hpc_mdat = _map_ref['hpc_map_data']
        _Wc_bg  = hpc_mdat.WcMap[0, :, :]  * _map_ref['s_Wc']
        _PR_bg  = (hpc_mdat.PRmap[0, :, :] - 1.0) * _map_ref['s_PR'] + 1.0
        _eff_bg = hpc_mdat.effMap[0, :, :] * _map_ref['s_eff']

        eff_levels = np.linspace(0.60, 0.92, 20)
        eff_cf = ax_map.contourf(_Wc_bg, _PR_bg, _eff_bg,
                                  levels=eff_levels, cmap='viridis', alpha=0.7, zorder=1)
        cb_eff = fig_map.colorbar(eff_cf, ax=ax_map, shrink=0.75, pad=0.02)
        cb_eff.set_label('HPC adiabatic efficiency  η  (—)', fontsize=9)

        stall_idx = np.argsort(_Wc_bg[:, 0])
        ax_map.plot(_Wc_bg[stall_idx, 0], _PR_bg[stall_idx, 0],
                    'r-', lw=2.0, zorder=3, label='Stall line')

        for r, col, mk in zip(all_results, _colors, _markers):
            if r['a4'] and r['hpc_wc']:
                wc_phys = [w * r['s_Wc'] for w in r['hpc_wc']]
                ax_map.plot(wc_phys, r['hpc_pr'], f'{mk}-', color=col,
                            lw=1.8, ms=6, mec='k', mew=0.5, zorder=6, label=r['label'])

        ax_map.legend(fontsize=9, loc='upper left')
        ax_map.set_xlabel('HPC corrected flow  $W_c$  (lbm/s)', fontsize=11)
        ax_map.set_ylabel('HPC Pressure Ratio', fontsize=11)
        ax_map.set_title('CFM56  —  HPC map: Fixed (s_Wp) vs VGT (α) operating trajectories')
        ax_map.grid(True, alpha=0.15, zorder=0)
        fig_map.tight_layout()
        fig_map.savefig('fixed_vs_vgt_hpc_map.png', dpi=150)
        print('  Saved fixed_vs_vgt_hpc_map.png')

    plt.show()
    print(f'\nTotal wall time (both scenarios): {time.time()-t_wall:.1f}s')
