"""
combustor_pycycle_integration.py
---------------------------------
Self-contained A4 variation study with physics-based combustor pressure drop.

Edit the CYCLE CONFIG block in __main__ to change:
  - Maps (comp_map, turb_map)
  - Design targets (Fn, T4, OPR, Nmech, ...)
  - A4 sweep range and resolution
  - Thrust levels for Study 2
  - Turbine area mode ('sWp' or 'alpha')

Turbine area variation modes
-----------------------------
  'sWp'   : s_Wp *= a4_scalar  — works with any map
  'alpha' : turb.map.alphaMap = a4_scalar  — requires variable-area alphaMap
            (generated by generate_turbine_map.py with area_fracs as alphaMap)

Combustor pressure drop model
------------------------------
  Total-to-total orifice:
    mdot = CdA * sqrt(2 * rho_t3 * (Pt3 - Pt4))
    pi_b = 1 - (mdot/CdA)^2 / (2 * rho_t3 * Pt3)
  CdA back-calculated from design point at fixed reference dPqP.
"""

from __future__ import annotations

import sys
import time
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm
from matplotlib.lines import Line2D
import pint

import openmdao.api as om
import pycycle.api as pyc
from pycycle.elements.cooling import CoolingCalcs

import cantera as ct

from Combustor_a4_sweep import (
    _gas, FAR_ST, FUEL, MECH, PHASE,
)
from scipy.interpolate import RegularGridInterpolator
from scipy.optimize   import minimize_scalar
from EngineHPT_map       import EngineHPTMap as EngineHPTVGTMap
from EngineHPT_map_fixed import EngineHPTMap as EngineHPTFixedMap
import os
def clear_terminal():
    if os.name == 'nt':
        _ = os.system('cls')
clear_terminal()
ureg = pint.UnitRegistry()
Q_   = ureg.Quantity

# ══════════════════════════════════════════════════════════════════════════════
#  UNIT CONVERSION CONSTANTS
# ══════════════════════════════════════════════════════════════════════════════

LBM_S_TO_KG_S = 0.453592
LBF_TO_KN     = 0.00444822
RANKINE_TO_K  = 5.0 / 9.0
PSI_TO_KPA    = 6.89476

# ══════════════════════════════════════════════════════════════════════════════
#  STUDY CONSTANTS
# ══════════════════════════════════════════════════════════════════════════════

DPQP_FIXED = 0.05
DPQP_TOL   = 0.001
MAX_OUTER  = 10
FN_COLORS  = {0.60: "seagreen", 0.70: "darkorange",
              0.80: "firebrick", 0.90: "mediumpurple", 1.00: "steelblue"}

# Cooling model constants — Walsh & Fletcher (2004) §5.4
# Split ~equally between NGV (non-chargeable) and rotor blade (chargeable)
NGV_COOL_FRAC   = 0.00
BLD_COOL_FRAC   = 0.00
TOTAL_COOL_FRAC = NGV_COOL_FRAC + BLD_COOL_FRAC
ETA_COOL        = 0.65    # film cooling effectiveness (Horlock et al. 2001)
T_METAL_MAX     = 1200    # K — reference blade material limit (plotting reference)
T_METAL_VANE_R  = 2210.0  # allowable NGV bulk metal temperature (°R)
T_METAL_BLADE_R = 2110.0  # allowable rotor blade bulk metal temperature (°R)
PSI_DESIGN      = 1.325   # turbine blade loading coeff ψ (Turbine_Map_Generator.py)


# ══════════════════════════════════════════════════════════════════════════════
#  MAP HELPER  (module-level so parametric_opt_tt4_sweep can import it)
# ══════════════════════════════════════════════════════════════════════════════

def map_design_point(turb_map, Np_des: float, alpha_design: float = 1.0):
    """Return (eff_des, PR_des) from turb_map at Np_des and alpha_design."""
    a_idx  = int(np.argmin(np.abs(np.array(turb_map.alphaMap) - alpha_design)))
    eff_sl = np.array(turb_map.effMap[a_idx])
    NpMap  = np.array(turb_map.NpMap)
    PRmap  = np.array(turb_map.PRmap)
    PR_des = turb_map.defaults['PRmap']
    Np_q   = float(np.clip(Np_des, NpMap[0], NpMap[-1]))
    interp = RegularGridInterpolator(
        (NpMap, PRmap), eff_sl, method='linear',
        bounds_error=False, fill_value=None)
    return float(np.asarray(interp([[Np_q, PR_des]])).item()), PR_des


# ══════════════════════════════════════════════════════════════════════════════
#  UNIT HELPERS
# ══════════════════════════════════════════════════════════════════════════════

def rankine_to_kelvin(T_R):  return Q_(T_R, "degR").to("K").magnitude
def psi_to_pa(P_psi):        return Q_(P_psi, "psi").to("Pa").magnitude
def lbm_s_to_kg_s(w):        return Q_(w, "lb/s").to("kg/s").magnitude


# ══════════════════════════════════════════════════════════════════════════════
#  COOLING SIZING  (Gauntner, NASA-TM-81453)
# ══════════════════════════════════════════════════════════════════════════════

def estimate_T3_rankine(OPR, T2_R=518.67, comp_eff=0.83, gamma=1.4):
    """Analytical estimate of compressor exit total temperature (°R)."""
    T3_ideal = T2_R * OPR ** ((gamma - 1.0) / gamma)
    return T2_R + (T3_ideal - T2_R) / comp_eff


def turb_rel_temp_rankine(T4_R, T4_exit_R, psi=PSI_DESIGN):
    """
    Relative stagnation temperature at rotor inlet (°R).
    T0_rel = T0_abs - U²/(2Cp)  where  U²/(2Cp) = ΔTt_stage / (2ψ).
    The rotor blade sees T0_rel, not the absolute T4.
    """
    return T4_R - (T4_R - T4_exit_R) / (2.0 * psi)


def gauntner_cooling_fracs(T4_R, T3_R,
                            T4_exit_R=None,
                            T_metal_vane_R=T_METAL_VANE_R,
                            T_metal_blade_R=T_METAL_BLADE_R,
                            factor_vane=1.0, factor_blade=1.0):
    """
    Per-row cooling flow fractions from Gauntner's COOLIT algorithm
    (NASA-TM-81453).  Returns (frac_ngv, frac_blade) as fractions of
    turbine inlet gas flow W_gas.

    Row 1 — NGV stator : T_gas = T4 (stationary — absolute frame).
    Row 2 — rotor blade: T_gas = T0_rel = T4 - ΔTt/(2ψ) (rotating frame).
      If T4_exit_R is provided, T0_rel is computed from velocity triangle physics
      via turb_rel_temp_rankine().  Otherwise falls back to Gauntner's 0.92*T4.

    FACTOR=1.0 = full-coverage film.  4/3 accounts for endwall/shroud/disk/leakage.
    """
    SAFETY = 150.0

    def _row_frac(T_gas_R, T_metal_R, profil, factor):
        T_eff = T_gas_R + SAFETY
        PHI   = (T_eff - T_metal_R) / abs(T_eff - T3_R)
        PHI   = (profil + PHI) / (profil + 1.0)
        PHI   = max(PHI, 0.0)
        if PHI >= 1.0:
            return factor * 0.022 * 10.0 * (4.0 / 3.0)
        return factor * 0.022 * (PHI / (1.0 - PHI)) ** 1.25 * (4.0 / 3.0)

    if T4_exit_R is not None:
        T_blade_gas_R = turb_rel_temp_rankine(T4_R, T4_exit_R)
    else:
        T_blade_gas_R = 0.92 * T4_R   # Gauntner approximation (fallback)

    frac_ngv   = _row_frac(T4_R,           T_metal_vane_R,  profil=0.30, factor=factor_vane)
    frac_blade = _row_frac(T_blade_gas_R,  T_metal_blade_R, profil=0.13, factor=factor_blade)
    return frac_ngv, frac_blade


def lmp_life_ratio(T_metal_ref_K, T_metal_od_K, t_r_ref_hr=20_000, C=20.0):
    """
    Creep life ratio t_r_od / t_r_ref from the Larson-Miller Parameter.

    At constant stress (fixed Nmech, fixed blade geometry), LMP = T*(C + log10(t_r))
    is conserved, giving:
        log10(life_ratio) = (T_ref/T_od - 1) * (C + log10(t_r_ref))

    Source: Larson & Miller (1952), Trans. ASME 74:765.
    C ~ 20 for Ni superalloys; t_r_ref_hr is the design life target in hours.
    T_ref/T_od is scale-invariant (K or degR give identical results).
    """
    log10_ratio = (T_metal_ref_K / T_metal_od_K - 1.0) * (C + np.log10(t_r_ref_hr))
    return float(10.0 ** log10_ratio)


# ══════════════════════════════════════════════════════════════════════════════
#  CANTERA HELPERS
# ══════════════════════════════════════════════════════════════════════════════

_GRI30 = ct.Solution("gri30.yaml")

def rho_total(Tt_K, Pt_Pa):
    # Cantera throws a hard error on T ≤ 0 or P ≤ 0 (e.g. during Newton line
    # search). Clamp to physical floors so the residual stays finite instead of
    # crashing; the solver will back-track away from these extreme states.
    Tt_K  = max(float(Tt_K),  1.0)
    Pt_Pa = max(float(Pt_Pa), 1.0)
    _GRI30.TPX = Tt_K, Pt_Pa, "O2:0.21, N2:0.79"
    return float(_GRI30.density)


# ══════════════════════════════════════════════════════════════════════════════
#  COMBUSTOR PRESSURE DROP MODEL
# ══════════════════════════════════════════════════════════════════════════════

def physics_pib(Pt3_Pa, Tt3_K, mdot_si, CdA):
    rho_t3 = rho_total(Tt3_K, Pt3_Pa)
    dPt    = (mdot_si / CdA) ** 2 / (2.0 * rho_t3)
    dPqP   = dPt / Pt3_Pa
    return float(1.0 - dPqP), float(dPqP)


def calc_CdA_liner(Tt3_K, Pt3_Pa, mdot_si, dPqP_ref=None):
    if dPqP_ref is None:
        dPqP_ref = DPQP_FIXED
    rho_t3 = rho_total(Tt3_K, Pt3_Pa)
    dPt    = dPqP_ref * Pt3_Pa
    return float(mdot_si / np.sqrt(2.0 * rho_t3 * dPt))


# ══════════════════════════════════════════════════════════════════════════════
#  THERMAL EFFICIENCY
# ══════════════════════════════════════════════════════════════════════════════

def extract_eta_th(prob, pt):
    # η_th = KE_exhaust / Q_fuel = Fn² / (2 · ṁ_exh · ṁ_fuel · LHV)
    # At static V_inf=0: Fn = ṁ_exh·V_exh exactly, so KE = Fn²/(2·ṁ_exh).
    # Fn is the FAR-balance-converged quantity — more stable than V_exh directly.
    LHV_JetA = 43.2e6   # J/kg, Jet-A lower heating value
    Fn_N  = float(prob.get_val(f"{pt}.perf.Fn", units='lbf')[0]) * 4.44822
    m_exh = Q_(float(prob.get_val(f"{pt}.inlet.Fl_O:stat:W")[0]) +
               float(prob.get_val(f"{pt}.burner.Wfuel")[0]),
               "lb/s").to("kg/s").magnitude
    Wfuel = Q_(float(prob.get_val(f"{pt}.burner.Wfuel")[0]),
               "lb/s").to("kg/s").magnitude
    return float(Fn_N**2 / (2.0 * m_exh * Wfuel * LHV_JetA))


# ══════════════════════════════════════════════════════════════════════════════
#  PHYSICS dP/P COMPONENT  — endogenous orifice model for Newton integration
# ══════════════════════════════════════════════════════════════════════════════

class PhysicsCombustor(om.ExplicitComponent):
    """
    Orifice liner head-loss model as an OpenMDAO component.

    When connected to burner.dPqP inside a Cycle, the pyCycle Newton solver
    treats combustor pressure drop as an algebraic state rather than a fixed
    input, giving a physics-consistent solution in one Newton solve with no
    outer Gauss-Seidel loop.

    dPqP = (ṁ_SI / CdA)² / (2 · ρ_total(Tt3, Pt3) · Pt3)

    Inputs use pyCycle imperial conventions (lbm/s, degR, psi).
    CdA is in SI (m²) — calibrated once from the design-point flow state.
    """
    def setup(self):
        self.add_input('W',   val=100.0, units='lbm/s', desc='inlet mass flow')
        self.add_input('Tt3', val=800.0, units='degR',  desc='total temperature at burner inlet')
        self.add_input('Pt3', val=100.0, units='psi',   desc='total pressure at burner inlet')
        self.add_input('CdA', val=1e-3,                 desc='orifice effective area, m²')
        self.add_output('dPqP', val=DPQP_FIXED, lower=1e-4, upper=0.49,
                        desc='fractional total-pressure loss (burner.dPqP)')
        # Finite-difference partials: Cantera inside rho_total can't accept
        # complex perturbations, so cs is not viable.
        self.declare_partials('dPqP', ['W', 'Tt3', 'Pt3', 'CdA'],
                              method='fd', step=1e-5, step_calc='rel')

    def compute(self, inputs, outputs):
        W_si   = Q_(float(inputs['W'][0]),   'lb/s').to('kg/s').magnitude
        Tt3_K  = Q_(float(inputs['Tt3'][0]), 'degR').to('K').magnitude
        Pt3_Pa = Q_(float(inputs['Pt3'][0]), 'psi').to('Pa').magnitude
        CdA    = float(inputs['CdA'][0])
        if CdA < 1e-10:
            outputs['dPqP'] = DPQP_FIXED
            return
        rho  = rho_total(Tt3_K, Pt3_Pa)
        dPt  = (W_si / CdA) ** 2 / (2.0 * rho)
        outputs['dPqP'] = float(np.clip(dPt / Pt3_Pa, 1e-4, 0.49))


# ══════════════════════════════════════════════════════════════════════════════
#  CYCLE COMPONENTS  (parameterised by cfg)
# ══════════════════════════════════════════════════════════════════════════════

def _make_turbojet_core(comp_map, turb_map):
    """Return a _setup_core(self) closure with all subsystems, flow connections,
    scalar connects, and solver config — shared by all three Cycle variants."""
    def _setup_core(self):
        self.options['thermo_method'] = 'TABULAR'
        self.options['thermo_data']   = pyc.AIR_JETA_TAB_SPEC

        self.add_subsystem('fc',     pyc.FlightConditions())
        self.add_subsystem('inlet',  pyc.Inlet())
        self.add_subsystem('comp',   pyc.Compressor(map_data=comp_map,
                                                     map_extrap=True),
                                     promotes_inputs=['Nmech'])
        self.add_subsystem('bld3',   pyc.BleedOut(bleed_names=['ngv_cool', 'bld_cool']))
        self.add_subsystem('burner', pyc.Combustor(fuel_type='FAR'))
        self.add_subsystem('turb',   pyc.Turbine(map_data=turb_map,
                                                  bleed_names=['ngv_cool', 'bld_cool'],
                                                  map_extrap=True),
                                     promotes_inputs=['Nmech'])
        self.add_subsystem('nozz',   pyc.Nozzle(nozzType='CD', lossCoef='Cv'))
        self.add_subsystem('shaft',  pyc.Shaft(num_ports=2),
                                     promotes_inputs=['Nmech'])
        self.add_subsystem('perf',   pyc.Performance(num_nozzles=1, num_burners=1))

        # Cooling calcs: dynamically size bleed fracs from T4, T3, T_metal
        # CoolingCalcs uses pyCycle's Gauntner/COOLIT model (same formula as
        # gauntner_cooling_fracs()) but runs inside the Newton loop so fracs
        # update as T4 changes across the A4/Fn sweep.
        self.add_subsystem('ngv_calcs', CoolingCalcs(
            n_stages=1, i_row=0,
            T_metal=T_METAL_VANE_R, T_safety=150.0))
        self.add_subsystem('bld_calcs', CoolingCalcs(
            n_stages=1, i_row=1,
            T_metal=T_METAL_BLADE_R, T_safety=150.0))
        self.add_subsystem('cool_fracs', om.ExecComp(
            ['frac_ngv = W_ngv / W_in',
             'frac_bld = W_bld / W_in'],
            W_ngv={'val': 5.0, 'units': 'lbm/s'},
            W_bld={'val': 3.0, 'units': 'lbm/s'},
            W_in={'val': 100.0, 'units': 'lbm/s'},
        ))

        self.pyc_connect_flow('fc.Fl_O',       'inlet.Fl_I',  connect_w=False)
        self.pyc_connect_flow('inlet.Fl_O',    'comp.Fl_I')
        self.pyc_connect_flow('comp.Fl_O',     'bld3.Fl_I')
        self.pyc_connect_flow('bld3.Fl_O',     'burner.Fl_I')
        self.pyc_connect_flow('burner.Fl_O',   'turb.Fl_I')
        self.pyc_connect_flow('bld3.ngv_cool', 'turb.ngv_cool', connect_stat=False)
        self.pyc_connect_flow('bld3.bld_cool', 'turb.bld_cool', connect_stat=False)
        self.pyc_connect_flow('turb.Fl_O',     'nozz.Fl_I')

        self.connect('comp.trq',         'shaft.trq_0')
        self.connect('turb.trq',         'shaft.trq_1')
        self.connect('fc.Fl_O:stat:P',   'nozz.Ps_exhaust')
        self.connect('inlet.Fl_O:tot:P', 'perf.Pt2')
        self.connect('comp.Fl_O:tot:P',  'perf.Pt3')
        self.connect('burner.Wfuel',     'perf.Wfuel_0')
        self.connect('inlet.F_ram',      'perf.ram_drag')
        self.connect('nozz.Fg',          'perf.Fg_0')

        # Cooling calc connections — same inputs as TurbineCooling.row_N
        for calc in ('ngv_calcs', 'bld_calcs'):
            self.connect('burner.Fl_O:tot:T', f'{calc}.Tt_primary')
            self.connect('burner.Fl_O:tot:h', f'{calc}.ht_primary')
            self.connect('burner.Fl_O:stat:W', f'{calc}.W_primary')
            self.connect('burner.Fl_O:tot:P',  f'{calc}.Pt_in')
            self.connect('turb.Fl_O:tot:P',    f'{calc}.Pt_out')
            self.connect('bld3.Fl_O:tot:T',    f'{calc}.Tt_cool')
            self.connect('bld3.Fl_O:tot:h',    f'{calc}.ht_cool')
            self.connect('turb.power',          f'{calc}.turb_pwr')
        self.connect('ngv_calcs.W_cool', 'cool_fracs.W_ngv')
        self.connect('bld_calcs.W_cool', 'cool_fracs.W_bld')
        self.connect('comp.Fl_O:stat:W', 'cool_fracs.W_in')
        self.connect('cool_fracs.frac_ngv', 'bld3.ngv_cool:frac_W')
        self.connect('cool_fracs.frac_bld', 'bld3.bld_cool:frac_W')

        newton = self.nonlinear_solver = om.NewtonSolver()
        newton.options['atol']             = 1e-6
        newton.options['rtol']             = 1e-6
        newton.options['iprint']           = 2
        newton.options['maxiter']          = 15
        newton.options['solve_subsystems'] = True
        newton.options['max_sub_solves']   = 100
        newton.options['reraise_child_analysiserror'] = False
        ls = newton.linesearch = om.ArmijoGoldsteinLS()
        ls.options['iprint']  = -1
        ls.options['maxiter'] = 3
        ls.options['rho']     = 0.75
        self.linear_solver = om.DirectSolver()

    return _setup_core


def _make_turbojet(cfg):
    _core = _make_turbojet_core(cfg['comp_map'], cfg['turb_map'])

    class Turbojet(pyc.Cycle):
        def setup(self):
            _core(self)
            design = self.options['design']
            bal = self.add_subsystem('balance', om.BalanceComp())
            if design:
                bal.add_balance('W', units='lbm/s', eq_units='lbf',
                                rhs_name='Fn_target')
                self.connect('balance.W',  'inlet.Fl_I:stat:W')
                self.connect('perf.Fn',    'balance.lhs:W')

                bal.add_balance('FAR', eq_units='degR', lower=1e-4,
                                val=0.017, rhs_name='T4_target')
                self.connect('balance.FAR',       'burner.Fl_I:FAR')
                self.connect('burner.Fl_O:tot:T', 'balance.lhs:FAR')

                bal.add_balance('turb_PR', val=1.5, lower=1.001, upper=8,
                                eq_units='hp', rhs_val=0.)
                self.connect('balance.turb_PR', 'turb.PR')
                self.connect('shaft.pwr_net',   'balance.lhs:turb_PR')
            super().setup()

    return Turbojet


def _make_turbojet_const_tt4(cfg):
    _core = _make_turbojet_core(cfg['comp_map'], cfg['turb_map'])

    class TurbojetConstTt4(pyc.Cycle):
        def setup(self):
            _core(self)
            bal = self.add_subsystem('balance', om.BalanceComp())

            bal.add_balance('FAR', eq_units='degR', lower=1e-4,
                            val=0.017, rhs_name='T4_target')
            self.connect('balance.FAR',       'burner.Fl_I:FAR')
            self.connect('burner.Fl_O:tot:T', 'balance.lhs:FAR')

            bal.add_balance('Nmech', val=8070., units='rpm',
                            lower=500., eq_units='hp', rhs_val=0.)
            self.connect('balance.Nmech', 'Nmech')
            self.connect('shaft.pwr_net', 'balance.lhs:Nmech')

            bal.add_balance('W', val=168.0, units='lbm/s',
                            eq_units='inch**2', rhs_name='nozz_area_target')
            self.connect('balance.W',             'inlet.Fl_I:stat:W')
            self.connect('nozz.Throat:stat:area', 'balance.lhs:W')
            super().setup()

    return TurbojetConstTt4


def _make_turbojet_const_fn(cfg):
    _core = _make_turbojet_core(cfg['comp_map'], cfg['turb_map'])

    class TurbojetConstFn(pyc.Cycle):
        def setup(self):
            _core(self)
            # Physics dP/P: endogenous to the Newton solve.
            # comp.Fl_O ≈ bld3.Fl_I ≈ burner.Fl_I (bld3 doesn't change total T/P).
            # W uses inlet mass flow (consistent with CdA calibration at design).
            self.add_subsystem('orifice', PhysicsCombustor())
            self.connect('comp.Fl_O:tot:T',   'orifice.Tt3')
            self.connect('comp.Fl_O:tot:P',   'orifice.Pt3')
            self.connect('inlet.Fl_O:stat:W', 'orifice.W')
            self.connect('orifice.dPqP',      'burner.dPqP')

            bal = self.add_subsystem('balance', om.BalanceComp())

            bal.add_balance('FAR', eq_units='lbf', lower=1e-4,
                            val=0.017, rhs_name='Fn_target')
            self.connect('balance.FAR', 'burner.Fl_I:FAR')
            self.connect('perf.Fn',     'balance.lhs:FAR')

            bal.add_balance('Nmech', val=8070., units='rpm',
                            lower=500., eq_units='hp', rhs_val=0.)
            self.connect('balance.Nmech', 'Nmech')
            self.connect('shaft.pwr_net', 'balance.lhs:Nmech')

            bal.add_balance('W', val=168.0, units='lbm/s',
                            eq_units='inch**2', rhs_name='nozz_area_target')
            self.connect('balance.W',             'inlet.Fl_I:stat:W')
            self.connect('nozz.Throat:stat:area', 'balance.lhs:W')
            super().setup()

    return TurbojetConstFn


# ══════════════════════════════════════════════════════════════════════════════
#  MULTI-POINT MODELS
# ══════════════════════════════════════════════════════════════════════════════

def _add_design_point_and_params(mp, Turbojet, cfg, include_dPqP=True):
    """Register DESIGN point, Mach/speed defaults, and cooling cycle params."""
    mp.pyc_add_pnt('DESIGN', Turbojet())
    mp.set_input_defaults('DESIGN.Nmech',     cfg['Nmech'],    units='rpm')
    mp.set_input_defaults('DESIGN.inlet.MN',  cfg['inlet_MN'])
    mp.set_input_defaults('DESIGN.comp.MN',   cfg['comp_MN'])
    mp.set_input_defaults('DESIGN.burner.MN', cfg['burner_MN'])
    mp.set_input_defaults('DESIGN.turb.MN',   cfg['turb_MN'])
    if include_dPqP:
        mp.pyc_add_cycle_param('burner.dPqP',          cfg['burner_dPqP'])
    mp.pyc_add_cycle_param('nozz.Cv',              cfg['nozz_Cv'])
    mp.pyc_add_cycle_param('turb.ngv_cool:frac_P', 1.0)
    mp.pyc_add_cycle_param('turb.bld_cool:frac_P', 0.0)


def _connect_od_scalars(mp, od_pts):
    """Propagate DESIGN map scalars and nozzle area to all OD points."""
    for pt in od_pts:
        mp.connect('DESIGN.nozz.Throat:stat:area', f'{pt}.balance.nozz_area_target')
        for sc in ['s_PR', 's_Wc', 's_eff', 's_Nc']:
            mp.connect(f'DESIGN.comp.{sc}', f'{pt}.comp.{sc}')
        for sc in ['s_PR', 's_eff', 's_Np']:
            mp.connect(f'DESIGN.turb.{sc}', f'{pt}.turb.{sc}')


def _make_mp_const_tt4(cfg):
    Turbojet         = _make_turbojet(cfg)
    TurbojetConstTt4 = _make_turbojet_const_tt4(cfg)

    class MPConstTt4(pyc.MPCycle):
        def setup(self):
            _add_design_point_and_params(self, Turbojet, cfg)

            self.a4_scalars = cfg['a4_scalars']
            self.a4_pts     = [f'A4_{i:03d}' for i in range(len(self.a4_scalars))]

            for pt in self.a4_pts:
                self.pyc_add_pnt(pt, TurbojetConstTt4(design=False))
                self.set_input_defaults(pt + '.fc.MN',  0.000001)
                self.set_input_defaults(pt + '.fc.alt', 0.0, units='ft')

            _connect_od_scalars(self, self.a4_pts)
            super().setup()

    return MPConstTt4


def _make_mp_const_fn(cfg):
    Turbojet        = _make_turbojet(cfg)
    TurbojetConstFn = _make_turbojet_const_fn(cfg)

    class MPConstFn(pyc.MPCycle):
        def setup(self):
            _add_design_point_and_params(self, Turbojet, cfg)

            self.fn_fractions = cfg['fn_fractions']
            self.a4_scalars   = cfg['a4_scalars']
            self.od_pts       = []

            for fi in range(len(self.fn_fractions)):
                for ai in range(len(self.a4_scalars)):
                    pt = f'FN{fi:02d}_A4_{ai:03d}'
                    self.od_pts.append(pt)
                    self.pyc_add_pnt(pt, TurbojetConstFn(design=False))
                    self.set_input_defaults(pt + '.fc.MN',  0.000001)
                    self.set_input_defaults(pt + '.fc.alt', 0.0, units='ft')

            _connect_od_scalars(self, self.od_pts)
            super().setup()

    return MPConstFn


# ══════════════════════════════════════════════════════════════════════════════
#  RESULT EXTRACTION
# ══════════════════════════════════════════════════════════════════════════════

def viewer(prob, pt, file=sys.stdout):
    summary = (
        prob[pt + '.fc.Fl_O:stat:MN'],
        prob[pt + '.fc.alt'],
        prob[pt + '.inlet.Fl_O:stat:W'],
        prob[pt + '.perf.Fn'],
        prob[pt + '.perf.Fg'],
        prob[pt + '.inlet.F_ram'],
        prob[pt + '.perf.OPR'],
        prob[pt + '.perf.TSFC'],
    )
    print(file=file, flush=True)
    print('─' * 76, file=file)
    print(f'  POINT: {pt}', file=file)
    print('─' * 76, file=file)
    print('  Mach      Alt       W      Fn      Fg    Fram     OPR     TSFC', file=file)
    print(' %7.5f  %7.1f %7.3f %7.1f %7.1f %7.1f %7.3f  %7.5f' % summary,
          file=file, flush=True)
    fs_full = [f'{pt}.{fs}' for fs in
               ['fc.Fl_O', 'inlet.Fl_O', 'comp.Fl_O', 'bld3.Fl_O',
                'burner.Fl_O', 'turb.Fl_O', 'nozz.Fl_O']]
    pyc.print_flow_station(prob, fs_full, file=file)
    pyc.print_compressor(prob, [f'{pt}.comp'],  file=file)
    pyc.print_burner(prob,     [f'{pt}.burner'])
    pyc.print_turbine(prob,    [f'{pt}.turb'],  file=file)
    pyc.print_nozzle(prob,     [f'{pt}.nozz'],  file=file)
    pyc.print_shaft(prob,      [f'{pt}.shaft'], file=file)


def extract_design(prob, pt='DESIGN'):
    W_des  = prob.get_val(f'{pt}.inlet.Fl_O:stat:W',  units='lbm/s')[0]
    Pt_des = prob.get_val(f'{pt}.inlet.Fl_O:tot:P',   units='psi')[0]
    Tt_des = prob.get_val(f'{pt}.inlet.Fl_O:tot:T',   units='degR')[0]
    Wc_des = W_des * np.sqrt(Tt_des / 518.67) / (Pt_des / 14.696)
    return {
        'pi_c':           prob.get_val(f'{pt}.perf.OPR')[0],
        'Nmech':          prob.get_val(f'{pt}.shaft.Nmech',       units='rpm')[0],
        'W':              W_des,
        'TSFC':           prob.get_val(f'{pt}.perf.TSFC',         units='lbm/(h*lbf)')[0],
        'T4_design':      prob.get_val(f'{pt}.burner.Fl_O:tot:T', units='degR')[0],
        's_Wp_design':    prob.get_val(f'{pt}.turb.s_Wp')[0],
        'eff_design':     prob.get_val(f'{pt}.turb.eff')[0],
        'comp_PR_design': prob.get_val(f'{pt}.comp.PR')[0],
        'comp_Wc_design': Wc_des,
        'Fn_design':      prob.get_val(f'{pt}.perf.Fn',           units='lbf')[0],
        'T3_design':      prob.get_val(f'{pt}.comp.Fl_O:tot:T',   units='degR')[0],
        'P3_design':      prob.get_val(f'{pt}.comp.Fl_O:tot:P',   units='lbf/inch**2')[0],
        'T4_exit_design': prob.get_val(f'{pt}.turb.Fl_O:tot:T',   units='degR')[0],
    }


def extract_od_point(prob, pt):
    W_od  = prob.get_val(f'{pt}.inlet.Fl_O:stat:W', units='lbm/s')[0]
    Pt_od = prob.get_val(f'{pt}.inlet.Fl_O:tot:P',  units='psi')[0]
    Tt_od = prob.get_val(f'{pt}.inlet.Fl_O:tot:T',  units='degR')[0]
    Wc_od = W_od * np.sqrt(Tt_od / 518.67) / (Pt_od / 14.696)
    return {
        'pi_c':     prob.get_val(f'{pt}.perf.OPR')[0],
        'Nmech':    prob.get_val(f'{pt}.shaft.Nmech',        units='rpm')[0],
        'W':        W_od,
        'Fn':       prob.get_val(f'{pt}.perf.Fn',            units='lbf')[0],
        'TSFC':     prob.get_val(f'{pt}.perf.TSFC',          units='lbm/(h*lbf)')[0],
        'T3':       prob.get_val(f'{pt}.comp.Fl_O:tot:T',    units='degR')[0],
        'P3':       prob.get_val(f'{pt}.comp.Fl_O:tot:P',    units='lbf/inch**2')[0],
        'T4':       prob.get_val(f'{pt}.burner.Fl_O:tot:T',  units='degR')[0],
        'comp_PR':  prob.get_val(f'{pt}.comp.PR')[0],
        'comp_Wc':  Wc_od,
        'turb_PR':   prob.get_val(f'{pt}.turb.PR')[0],
        'turb_eff':  prob.get_val(f'{pt}.turb.eff')[0],
        'turb_Wp':   prob.get_val(f'{pt}.turb.Wp')[0],
        'T4_exit':   prob.get_val(f'{pt}.turb.Fl_O:tot:T', units='degR')[0],
    }


# ══════════════════════════════════════════════════════════════════════════════
#  TURBINE AREA CONTROL
# ══════════════════════════════════════════════════════════════════════════════

def set_turb_area(prob, pt, a4_scalar, s_Wp_design, mode):
    if mode == 'sWp':
        prob.set_val(f"{pt}.turb.s_Wp", s_Wp_design * a4_scalar)
    elif mode == 'alpha':
        prob.set_val(f"{pt}.turb.map.alphaMap", a4_scalar)
        prob.set_val(f"{pt}.turb.s_Wp", s_Wp_design)  # alphaMap controls area; s_Wp stays at design
    else:
        raise ValueError(f"Unknown TURB_AREA_MODE: {mode!r}  (use 'sWp' or 'alpha')")


# ══════════════════════════════════════════════════════════════════════════════
#  STUDY 1 — CONSTANT Tt4
# ══════════════════════════════════════════════════════════════════════════════

def run_study1(cfg, mode):
    print('\n' + '█' * 60)
    print(f' STUDY 1 — Constant Tt4, Variable A4  [mode={mode}]')
    print('█' * 60)

    MPConstTt4 = _make_mp_const_tt4(cfg)
    prob = om.Problem()
    mp   = prob.model = MPConstTt4()
    prob.setup(check=False)

    # Design inputs
    prob.set_val('DESIGN.fc.alt',            0.0,               units='ft')
    prob.set_val('DESIGN.fc.MN',             0.000001)
    prob.set_val('DESIGN.balance.Fn_target', cfg['Fn_design'],  units='lbf')
    prob.set_val('DESIGN.balance.T4_target', cfg['T4_design'],  units='degR')
    prob.set_val('DESIGN.comp.PR',           cfg['OPR'])
    prob.set_val('DESIGN.comp.eff',          cfg['comp_eff'])
    prob.set_val('DESIGN.turb.eff',          cfg['turb_eff'])
    prob['DESIGN.balance.FAR']     = cfg.get('FAR_guess',     0.0175)
    prob['DESIGN.balance.W']       = cfg.get('W_guess',       168.0)
    prob['DESIGN.balance.turb_PR'] = cfg.get('turb_PR_guess', 3.5)
    prob['DESIGN.fc.balance.Pt']   = 14.696
    prob['DESIGN.fc.balance.Tt']   = 518.67
    prob.set_val('DESIGN.cool_fracs.frac_ngv', cfg.get('ngv_cool_frac', 0.05))
    prob.set_val('DESIGN.cool_fracs.frac_bld', cfg.get('bld_cool_frac', 0.03))

    for pt in mp.a4_pts:
        prob[pt + '.balance.FAR']   = cfg.get('FAR_guess', 0.017)
        prob[pt + '.balance.Nmech'] = cfg['Nmech']
        prob[pt + '.balance.W']     = cfg.get('W_guess', 168.0)
        prob[pt + '.fc.balance.Pt'] = 14.696
        prob[pt + '.fc.balance.Tt'] = 518.67
        prob.set_val(pt + '.balance.T4_target', cfg['T4_design'], units='degR')
        prob.model._get_subsystem(pt).nonlinear_solver.options['maxiter'] = 0

    prob.set_solver_print(level=-1)
    prob.set_solver_print(level=2, depth=1)

    print('\n── Design point ──')
    t0 = time.time()
    prob.run_model()
    print(f'Design solved in {time.time()-t0:.1f}s')

    design_results = extract_design(prob)
    viewer(prob, 'DESIGN')
    print(f"\nDesign PR={design_results['pi_c']:.3f}  s_Wp={design_results['s_Wp_design']:.6f}")

    # Set design alpha for alpha mode
    if mode == 'alpha':
        prob.set_val('DESIGN.turb.map.alphaMap', 1.0)

    print('\n── A4 sweep ──')
    for pt in mp.a4_pts:
        prob.model._get_subsystem(pt).nonlinear_solver.options['maxiter'] = 15

    for pt, a4 in zip(mp.a4_pts, mp.a4_scalars):
        set_turb_area(prob, pt, a4, design_results['s_Wp_design'], mode)
        prob[pt + '.balance.Nmech'] = design_results['Nmech'] * (1.0/a4)**0.3

    t1 = time.time()
    prob.run_model()
    print(f'Sweep solved in {time.time()-t1:.1f}s')

    results = []
    for pt, a4 in zip(mp.a4_pts, mp.a4_scalars):
        r = extract_od_point(prob, pt)
        r['scalar'] = a4
        results.append(r)

    print('\n' + '=' * 80)
    print(' STUDY 1 RESULTS — Constant Tt4')
    print('=' * 80)
    print(f"{'A4 scl':>7} {'PR':>8} {'Nmech':>9} {'W kg/s':>8} "
          f"{'Fn kN':>8} {'TSFC':>9} {'T3 K':>7} {'T4 K':>7}")
    print('-' * 80)
    for r in results:
        print(f"  {r['scalar']:5.3f}  {r['pi_c']:8.3f}  {r['Nmech']:8.1f}  "
              f"{r['W']*LBM_S_TO_KG_S:7.2f}  {r['Fn']*LBF_TO_KN:7.2f}  "
              f"{r['TSFC']:9.5f}  {r['T3']*RANKINE_TO_K:6.1f}  "
              f"{r['T4']*RANKINE_TO_K:6.1f}")

    return prob, design_results, results


# ══════════════════════════════════════════════════════════════════════════════
#  STUDY 2 — CONSTANT Fn
# ══════════════════════════════════════════════════════════════════════════════

def run_study2(cfg, mode, design_results_s1):
    print('\n' + '█' * 60)
    print(f' STUDY 2 — Constant Fn, Variable A4  [mode={mode}]')
    print('█' * 60)

    MPConstFn = _make_mp_const_fn(cfg)
    prob = om.Problem()
    mp   = prob.model = MPConstFn()
    prob.setup(check=False)

    prob.set_val('DESIGN.fc.alt',            0.0,               units='ft')
    prob.set_val('DESIGN.fc.MN',             0.000001)
    prob.set_val('DESIGN.balance.Fn_target', cfg['Fn_design'],  units='lbf')
    prob.set_val('DESIGN.balance.T4_target', cfg['T4_design'],  units='degR')
    prob.set_val('DESIGN.comp.PR',           cfg['OPR'])
    prob.set_val('DESIGN.comp.eff',          cfg['comp_eff'])
    prob.set_val('DESIGN.turb.eff',          cfg['turb_eff'])
    prob['DESIGN.balance.FAR']     = cfg.get('FAR_guess',     0.0175)
    prob['DESIGN.balance.W']       = cfg.get('W_guess',       168.0)
    prob['DESIGN.balance.turb_PR'] = cfg.get('turb_PR_guess', 3.5)
    prob['DESIGN.fc.balance.Pt']   = 14.696
    prob['DESIGN.fc.balance.Tt']   = 518.67
    prob.set_val('DESIGN.cool_fracs.frac_ngv', cfg.get('ngv_cool_frac', 0.05))
    prob.set_val('DESIGN.cool_fracs.frac_bld', cfg.get('bld_cool_frac', 0.03))

    for pt in mp.od_pts:
        prob[pt + '.balance.FAR']   = cfg.get('FAR_guess', 0.017)
        prob[pt + '.balance.Nmech'] = cfg['Nmech']
        prob[pt + '.balance.W']     = cfg.get('W_guess', 168.0)
        prob[pt + '.fc.balance.Pt'] = 14.696
        prob[pt + '.fc.balance.Tt'] = 518.67
        prob.model._get_subsystem(pt).nonlinear_solver.options['maxiter'] = 0

    prob.set_solver_print(level=-1)
    prob.set_solver_print(level=2, depth=1)

    print('\n── Design point ──')
    t0 = time.time()
    prob.run_model()
    print(f'Design solved in {time.time()-t0:.1f}s')
    design_results = extract_design(prob)

    # Set design alpha for alpha mode
    if mode == 'alpha':
        prob.set_val('DESIGN.turb.map.alphaMap', 1.0)

    print('\n── Constant-Fn sweep ──')
    for pt in mp.od_pts:
        prob.model._get_subsystem(pt).nonlinear_solver.options['maxiter'] = 15

    for fi, frac in enumerate(mp.fn_fractions):
        Fn_target = frac * cfg['Fn_design']
        for ai, a4 in enumerate(mp.a4_scalars):
            pt = f'FN{fi:02d}_A4_{ai:03d}'
            set_turb_area(prob, pt, a4, design_results['s_Wp_design'], mode)
            prob.set_val(f'{pt}.balance.Fn_target', Fn_target, units='lbf')
            prob[pt + '.balance.Nmech'] = (design_results['Nmech']
                                           * frac**0.5 * (1.0/a4)**0.3)
            prob[pt + '.balance.FAR']   = cfg.get('FAR_guess', 0.017) * frac

    t1 = time.time()
    prob.run_model()
    print(f'Sweep solved in {time.time()-t1:.1f}s')

    baseline_ai = int(np.argmin(np.abs(np.array(mp.a4_scalars) - 1.0)))
    const_fn_results = {}
    for fi, frac in enumerate(mp.fn_fractions):
        sweep = []
        for ai, a4 in enumerate(mp.a4_scalars):
            r = extract_od_point(prob, f'FN{fi:02d}_A4_{ai:03d}')
            r['scalar'] = a4
            sweep.append(r)
        tsfc_arr = np.array([r['TSFC'] for r in sweep])
        opt_idx  = int(np.argmin(tsfc_arr))
        const_fn_results[frac] = {
            'sweep':         sweep,
            'opt_idx':       opt_idx,
            'opt_scalar':    mp.a4_scalars[opt_idx],
            'opt_tsfc':      tsfc_arr[opt_idx],
            'opt_T4':        sweep[opt_idx]['T4'],
            'baseline_tsfc': tsfc_arr[baseline_ai],
            'baseline_T4':   sweep[baseline_ai]['T4'],
        }

    _summarise_const_fn(mp.fn_fractions, mp.a4_scalars,
                        const_fn_results, design_results, cfg)
    return prob, design_results, const_fn_results


def _summarise_const_fn(fn_fractions, a4_scalars, const_fn_results,
                        design_results, cfg):
    print('\n' + '=' * 80)
    print(' STUDY 2 SUMMARY — OPTIMAL A4 AT EACH THRUST SETTING')
    print('=' * 80)
    print(f"{'Fn (%)':>7} {'Fn_tgt (kN)':>12} {'Opt A4':>8} "
          f"{'Opt TSFC':>10} {'T4 opt (K)':>11} "
          f"{'T4 fixed (K)':>13} {'ΔT4 (K)':>8} {'ΔTSFC (%)':>10}")
    print('-' * 80)
    for frac in fn_fractions:
        d = const_fn_results[frac]
        print(f"  {int(frac*100):5d}  "
              f"{frac*cfg['Fn_design']*LBF_TO_KN:11.2f}  "
              f"{d['opt_scalar']:8.3f}  "
              f"{d['opt_tsfc']:10.5f}  "
              f"{d['opt_T4']*RANKINE_TO_K:11.1f}  "
              f"{d['baseline_T4']*RANKINE_TO_K:13.1f}  "
              f"{(d['baseline_T4']-d['opt_T4'])*RANKINE_TO_K:8.1f}  "
              f"{(d['baseline_tsfc']-d['opt_tsfc'])/d['baseline_tsfc']*100:10.2f}")


# ══════════════════════════════════════════════════════════════════════════════
#  COMBUSTOR PHYSICS SWEEPS
# ══════════════════════════════════════════════════════════════════════════════

def _make_mp_single_fn(cfg):
    """Single-Fn MPCycle for the physics dP/P Gauss-Seidel sweeps."""
    Turbojet        = _make_turbojet(cfg)
    TurbojetConstFn = _make_turbojet_const_fn(cfg)

    class MPSingleFn(pyc.MPCycle):
        def setup(self):
            # dPqP is set per-point in the physics sweep, not as a cycle param
            _add_design_point_and_params(self, Turbojet, cfg, include_dPqP=False)

            self.a4_scalars = cfg['a4_scalars']
            self.od_pts     = [f'A4_{i:03d}' for i in range(len(self.a4_scalars))]

            for pt in self.od_pts:
                self.pyc_add_pnt(pt, TurbojetConstFn(design=False))
                self.set_input_defaults(pt + '.fc.MN',  0.000001)
                self.set_input_defaults(pt + '.fc.alt', 0.0, units='ft')

            _connect_od_scalars(self, self.od_pts)
            super().setup()

    return MPSingleFn


def _run_od_sweep_sequential(prob, mp, maxiter=30, pts_order=None):
    pts = pts_order if pts_order is not None else mp.od_pts
    t0 = time.time()
    for i, pt in enumerate(pts):
        for other in mp.od_pts:
            prob.model._get_subsystem(other).nonlinear_solver.options['maxiter'] = 0
        prob.model._get_subsystem(pt).nonlinear_solver.options['maxiter'] = maxiter
        prob.run_model()
        if i + 1 < len(pts):
            nxt = pts[i+1]
            for var in ['balance.FAR', 'balance.Nmech', 'balance.W']:
                prob[f'{nxt}.{var}'] = prob[f'{pt}.{var}']
        print(f'    {pt} ({i+1}/{len(pts)})')
    print(f'  sweep in {time.time()-t0:.1f}s')


def run_fixed_dPqP_sweep(prob, mp, design_results, fn_frac, cfg, mode):
    print(f"\n  Fixed dP/P={DPQP_FIXED*100:.0f}%  {fn_frac*100:.0f}% Fn")
    Fn_target = fn_frac * cfg['Fn_design']
    for pt, a4 in zip(mp.od_pts, mp.a4_scalars):
        set_turb_area(prob, pt, a4, design_results['s_Wp_design'], mode)
        prob.set_val(f'{pt}.balance.Fn_target', Fn_target, units='lbf')
        prob.set_val(f'{pt}.burner.dPqP', DPQP_FIXED)
        prob[pt + '.balance.Nmech'] = (design_results['Nmech']
                                       * fn_frac**0.5 * (1.0/a4)**0.3)
        prob[pt + '.balance.FAR']   = cfg.get('FAR_guess', 0.017) * fn_frac
        prob.model._get_subsystem(pt).nonlinear_solver.options['maxiter'] = 15

    _run_od_sweep_sequential(prob, mp)

    results = []
    for pt, a4 in zip(mp.od_pts, mp.a4_scalars):
        r = extract_od_point(prob, pt)
        r.update(a4_scalar=a4, dPqP=DPQP_FIXED,
                 fn_frac=fn_frac, eta_th=extract_eta_th(prob, pt))
        results.append(r)
    return results


def run_physics_dPqP_sweep(prob, mp, design_results, fn_frac, cfg, mode,
                           dPqP_init=None):
    """
    Run physics dP/P outer loop. Returns (results, dPqP_converged).
    Pass dPqP_init (dict pt→value from a previous converged call) to warm-start
    the outer iteration — saves 2-4 outer iterations when moving between nearby
    design cells.
    """
    print(f"\n  Physics dP/P  {fn_frac*100:.0f}% Fn")
    Fn_target = fn_frac * cfg['Fn_design']
    if dPqP_init is not None:
        dPqP_cur = {pt: dPqP_init.get(pt, DPQP_FIXED) for pt in mp.od_pts}
    else:
        dPqP_cur = {pt: DPQP_FIXED for pt in mp.od_pts}

    # If OD cycles include an endogenous PhysicsCombustor orifice, inject CdA
    # so the Newton solve uses the design-calibrated orifice area.
    # The explicit burner.dPqP sets below become no-ops (connected input).
    CdA = design_results.get('CdA_liner')
    if CdA is not None:
        for pt in mp.od_pts:
            try:
                prob.set_val(f'{pt}.orifice.CdA', CdA)
            except KeyError:
                pass   # TurbojetConstTt4 cycle — no orifice subsystem

    # Reversed order: process largest A4 (easiest) first so converged W propagates
    # toward smallest A4 (hardest) rather than poisoning the chain if A4_min fails.
    _pts_reversed = list(reversed(mp.od_pts))

    for outer in range(MAX_OUTER):
        print(f"\n  Outer iter {outer+1}/{MAX_OUTER}")
        for pt, a4 in zip(mp.od_pts, mp.a4_scalars):
            set_turb_area(prob, pt, a4, design_results['s_Wp_design'], mode)
            prob.set_val(f'{pt}.balance.Fn_target', Fn_target, units='lbf')
            prob.set_val(f'{pt}.burner.dPqP', dPqP_cur[pt])
            prob[pt + '.balance.Nmech'] = (design_results['Nmech']
                                           * fn_frac**0.5 * (1.0/a4)**0.3)
            prob[pt + '.balance.FAR']   = cfg.get('FAR_guess', 0.017) * fn_frac
            prob[pt + '.balance.W']     = design_results['W'] * fn_frac
            prob.model._get_subsystem(pt).nonlinear_solver.options['maxiter'] = 15

        _run_od_sweep_sequential(prob, mp, pts_order=_pts_reversed)

        dPqP_new, max_change = {}, 0.0
        for pt, a4 in zip(mp.od_pts, mp.a4_scalars):
            r = extract_od_point(prob, pt)
            _, dPqP_phys = physics_pib(
                psi_to_pa(r['P3']), rankine_to_kelvin(r['T3']),
                lbm_s_to_kg_s(r['W']), design_results['CdA_liner'])
            dPqP_phys    = float(np.clip(dPqP_phys, 0.001, 0.50))
            dPqP_new[pt] = dPqP_phys
            change       = abs(dPqP_phys - dPqP_cur[pt]) / max(dPqP_cur[pt], 1e-6)
            max_change   = max(max_change, change)
            print(f'    {pt}  A4={a4:.3f}  dP/P: '
                  f'{dPqP_cur[pt]*100:.2f}%→{dPqP_phys*100:.2f}%')

        print(f'  max change={max_change*100:.3f}%')
        dPqP_cur = dPqP_new
        if max_change < DPQP_TOL:
            print(f'  Converged in {outer+1} iters')
            break

    # Cleanup pass at the converged dPqP — dPqP is now fixed, pure Newton.
    # maxiter=20 is enough since OD state is already warm from the outer loop.
    print('\n  Final cleanup pass...')
    for pt in mp.od_pts:
        prob.set_val(f'{pt}.burner.dPqP', dPqP_cur[pt])
    _run_od_sweep_sequential(prob, mp, maxiter=20, pts_order=_pts_reversed)

    results = []
    for pt, a4 in zip(mp.od_pts, mp.a4_scalars):
        r = extract_od_point(prob, pt)
        r.update(a4_scalar=a4, dPqP=dPqP_cur[pt],
                 fn_frac=fn_frac, eta_th=extract_eta_th(prob, pt))
        results.append(r)
    return results, dPqP_cur


# ══════════════════════════════════════════════════════════════════════════════
#  PLOTS
# ══════════════════════════════════════════════════════════════════════════════

def plot_study1(scalars, results, design_results, cfg):
    s     = np.array(scalars)
    pi_c  = np.array([r['pi_c']  for r in results])
    Nmech = np.array([r['Nmech'] for r in results])
    W     = np.array([r['W']     for r in results]) * LBM_S_TO_KG_S
    Fn    = np.array([r['Fn']    for r in results]) * LBF_TO_KN
    TSFC  = np.array([r['TSFC']  for r in results])
    T3    = np.array([r['T3']    for r in results]) * RANKINE_TO_K
    P3    = np.array([r['P3']    for r in results]) * PSI_TO_KPA
    T4_K  = design_results['T4_design'] * RANKINE_TO_K

    fig, axes = plt.subplots(2, 3, figsize=(15, 9))
    fig.suptitle(f'Study 1 — Constant TIT={T4_K:.0f}K, Variable A₄  |  SLS',
                 fontsize=12, fontweight='bold')

    kw  = dict(lw=2, marker='o', markersize=3)
    kwh = dict(ls=':', lw=1.4, alpha=0.8)

    panels = [
        (axes[0,0], pi_c,  'C0', 'Overall PR', f"Des={design_results['pi_c']:.2f}"),
        (axes[0,1], Nmech, 'C1', 'Shaft Speed (rpm)', f"Des={design_results['Nmech']:.0f}"),
        (axes[0,2], W,     'C2', 'Mass Flow (kg/s)', f"Des={design_results['W']*LBM_S_TO_KG_S:.1f}"),
        (axes[1,0], Fn,    'C3', 'Net Thrust (kN)', f"Des={cfg['Fn_design']*LBF_TO_KN:.1f}"),
        (axes[1,1], TSFC,  'C4', 'TSFC (lbm/hr/lbf)', f"Des={design_results['TSFC']:.5f}"),
    ]
    for ax, data, color, ylabel, des_label in panels:
        ax.plot(s, data, color, **kw)
        ax.axhline(data[np.argmin(np.abs(s-1.0))], color=color,
                   label=des_label, **kwh)
        ax.axvline(1.0, color='gray', ls='--', lw=1.5)
        ax.set_xlabel('A₄ scalar', fontsize=9)
        ax.set_ylabel(ylabel, fontsize=9)
        ax.legend(fontsize=8); ax.grid(True, alpha=0.3)

    # TSFC annotation
    ax = axes[1,1]
    mi = int(np.argmin(TSFC))
    ax.annotate(f'Opt={s[mi]:.3f}\nTSFC={TSFC[mi]:.5f}',
                xy=(s[mi], TSFC[mi]),
                xytext=(s[mi]+0.03, TSFC[mi]+0.003), fontsize=7,
                bbox=dict(boxstyle='round', fc='lightyellow', ec='C4'),
                arrowprops=dict(arrowstyle='->', color='C4'))

    # T3/P3
    ax = axes[1,2]; ax2 = ax.twinx()
    l1, = ax.plot(s,  T3, 'C5', **kw, label='T₃ (K)')
    l2, = ax2.plot(s, P3, 'C6', lw=2, marker='s', ms=3, ls='--', label='P₃ (kPa)')
    ax.axvline(1.0, color='gray', ls='--', lw=1.5)
    ax.set_xlabel('A₄ scalar', fontsize=9)
    ax.set_ylabel('T₃ (K)', fontsize=9, color='C5')
    ax2.set_ylabel('P₃ (kPa)', fontsize=9, color='C6')
    ax.legend(handles=[l1, l2], fontsize=8); ax.grid(True, alpha=0.3)

    plt.subplots_adjust(hspace=0.55, wspace=0.38)
    plt.savefig('study1_const_tt4.png', dpi=150)
    plt.show()


def plot_study2(fn_fractions, a4_scalars, const_fn_results, design_results, cfg):
    s      = np.array(a4_scalars)
    colors = cm.viridis(np.linspace(0.15, 0.85, len(fn_fractions)))
    T4_K   = design_results['T4_design'] * RANKINE_TO_K

    fig, axes = plt.subplots(2, 2, figsize=(13, 10))
    fig.suptitle('Study 2 — Constant Thrust, Variable A₄  |  SLS',
                 fontsize=12, fontweight='bold')

    # TSFC locus
    ax = axes[0,0]
    for fi, frac in enumerate(fn_fractions):
        sweep = const_fn_results[frac]['sweep']
        tsfc  = np.array([r['TSFC'] for r in sweep])
        ax.plot(s, tsfc, color=colors[fi], lw=2, marker='o', ms=2,
                label=f'{int(frac*100)}% Fₙ')
        mi = int(np.argmin(tsfc))
        ax.plot(s[mi], tsfc[mi], '*', color=colors[fi], ms=10,
                markeredgecolor='k', zorder=5)
    opt_s    = [const_fn_results[f]['opt_scalar'] for f in fn_fractions]
    opt_tsfc = [const_fn_results[f]['opt_tsfc']   for f in fn_fractions]
    ax.plot(opt_s, opt_tsfc, 'k--', lw=1.5, label='Locus of optima')
    ax.axvline(1.0, color='gray', ls='--', lw=1.2)
    ax.set_xlabel('A₄ scalar'); ax.set_ylabel('TSFC')
    ax.set_title('TSFC vs A₄ — ★ = minimum'); ax.legend(fontsize=8); ax.grid(True, alpha=0.3)

    # Optimal A4 schedule
    ax = axes[0,1]
    pct = [f*100 for f in fn_fractions]
    ax.plot(pct, opt_s, 'ko-', lw=2, ms=8)
    ax.axhline(1.0, color='gray', ls='--', lw=1.2, label='Design')
    ax.set_xlabel('Thrust (% design)'); ax.set_ylabel('Optimal A₄ scalar')
    ax.set_title('Optimal A₄ Schedule'); ax.legend(fontsize=8); ax.grid(True, alpha=0.3)

    # TSFC improvement
    ax = axes[1,0]; ax2 = ax.twinx()
    fg_tsfc = [const_fn_results[f]['baseline_tsfc'] for f in fn_fractions]
    op_tsfc = [const_fn_results[f]['opt_tsfc']      for f in fn_fractions]
    d_abs   = [fg-op for fg,op in zip(fg_tsfc, op_tsfc)]
    d_pct   = [d/fg*100 for d,fg in zip(d_abs, fg_tsfc)]
    ax.bar(pct, d_pct, width=4, color=colors, edgecolor='k', alpha=0.85)
    ax2.plot(pct, d_abs, 'k^--', lw=1.5, ms=7)
    for i,(p,dp) in enumerate(zip(pct, d_pct)):
        ax.text(p, dp+0.01, f'{dp:.2f}%', ha='center', fontsize=8, fontweight='bold')
    ax.set_xlabel('Thrust (% design)'); ax.set_ylabel('ΔTSFC (%)', color='C0')
    ax2.set_ylabel('ΔTSFC (abs)', color='k')
    ax.set_title('TSFC Benefit of Variable A₄'); ax.grid(True, alpha=0.3, axis='y')

    # T4 reduction
    ax = axes[1,1]
    opt_T4  = [const_fn_results[f]['opt_T4']*RANKINE_TO_K      for f in fn_fractions]
    fix_T4  = [const_fn_results[f]['baseline_T4']*RANKINE_TO_K for f in fn_fractions]
    ax.plot(pct, opt_T4, 'o-', color='C3', lw=2, ms=8, label='Optimal A₄')
    ax.plot(pct, fix_T4, 's--', color='C1', lw=2, ms=8, label='Fixed geometry')
    ax.axhline(T4_K, color='gray', ls=':', lw=1.2, label=f'Design T₄={T4_K:.0f}K')
    ax.fill_between(pct, fix_T4, opt_T4, alpha=0.15, color='green')
    ax.set_xlabel('Thrust (% design)'); ax.set_ylabel('T₄ (K)')
    ax.set_title('TIT Reduction with Variable A₄'); ax.legend(fontsize=8); ax.grid(True, alpha=0.3)

    plt.subplots_adjust(hspace=0.50, wspace=0.38)
    plt.savefig('study2_const_fn.png', dpi=150)
    plt.show()


def plot_combustor(fixed_by_fn, physics_by_fn, fn_fracs):
    colors = {}
    for f in fn_fracs:
        colors[f] = FN_COLORS.get(f, f'C{list(fn_fracs).index(f)}')

    fig1, axes = plt.subplots(1, len(fn_fracs),
                               figsize=(5*len(fn_fracs), 5), sharey=False)
    if len(fn_fracs) == 1:
        axes = [axes]
    fig1.suptitle("Gas Generator Thermal Efficiency vs A₄\n"
                  "Solid=physics dP/P  |  Faded=fixed 5%",
                  fontsize=11, fontweight='bold')

    for ax, frac in zip(axes, fn_fracs):
        color = colors[frac]
        res_f = fixed_by_fn[frac]
        s_f   = np.array([r['a4_scalar'] for r in res_f])
        eta_f = np.array([r['eta_th']    for r in res_f]) * 100
        ax.plot(s_f, eta_f, '-', color=color, lw=1.5, alpha=0.35, label='Fixed dP/P')

        res_p = physics_by_fn[frac]
        s_p   = np.array([r['a4_scalar'] for r in res_p])
        eta_p = np.array([r['eta_th']    for r in res_p]) * 100
        ax.plot(s_p, eta_p, '-', color=color, lw=2.2, label='Physics dP/P')

        idx_p = int(np.argmax(eta_p))
        ax.scatter([s_p[idx_p]], [eta_p[idx_p]], color=color,
                   s=160, marker='*', edgecolors='k', zorder=5)
        ax.axvline(1.0, color='gray', ls='--', lw=1.0, alpha=0.5)
        ax.set_xlabel('A₄ scalar'); ax.set_ylabel('η_th (%)');
        ax.set_title(f'{frac*100:.0f}% Fₙ', fontweight='bold', color=color)
        ax.legend(fontsize=8); ax.grid(False)
        ax.spines['top'].set_visible(False); ax.spines['right'].set_visible(False)

    fig1.tight_layout()
    fig1.savefig('combustor_eta_th.png', dpi=150, bbox_inches='tight')

    fig2, ax2 = plt.subplots(figsize=(7, 5))
    ax2.axhline(DPQP_FIXED*100, color='gray', ls='--', lw=1.2,
                label=f'Design dP/P={DPQP_FIXED*100:.0f}%')
    for frac, results in physics_by_fn.items():
        color = colors[frac]
        s     = np.array([r['a4_scalar'] for r in results])
        dPqP  = np.array([r['dPqP']*100  for r in results])
        ax2.plot(s, dPqP, 'o-', color=color, lw=2, ms=4,
                 label=f'Physics {frac*100:.0f}% Fₙ')
        idx1 = int(np.argmin(np.abs(s-1.0)))
        ax2.scatter([s[idx1]], [dPqP[idx1]], color=color,
                    s=100, marker='D', edgecolors='k', zorder=5)
        ax2.annotate(f'{dPqP[idx1]:.2f}%',
                     xy=(s[idx1], dPqP[idx1]),
                     xytext=(s[idx1]-0.06, dPqP[idx1]+0.05),
                     fontsize=7.5, color=color)
    ax2.axvline(1.0, color='gray', ls='--', lw=1.0, alpha=0.5)
    ax2.set_xlabel('A₄ scalar'); ax2.set_ylabel('Combustor dP/P (%)')
    ax2.set_title('Physics-Based Combustor Pressure Drop', fontweight='bold')
    ax2.legend(fontsize=8)
    ax2.spines['top'].set_visible(False); ax2.spines['right'].set_visible(False)
    fig2.tight_layout()
    fig2.savefig('combustor_dpqp.png', dpi=150, bbox_inches='tight')
    plt.show()


# ══════════════════════════════════════════════════════════════════════════════
#  COMPRESSOR MAP
# ══════════════════════════════════════════════════════════════════════════════

def draw_compressor_map_background(
        ax, prob, e_name, alpha_idx=0,
        eff_vals=np.array([0, 0.50, 0.55, 0.60, 0.65,
                           0.70, 0.75, 0.80, 0.85, 0.90, 0.95, 1.0]),
        show_rlines=True, show_nclines=True, eff_alpha=1.0):
    """Draw efficiency fill, speed lines, R-lines, and stall line onto ax."""
    comp     = prob.model._get_subsystem(e_name)
    map_data = comp.options['map_data']

    s_Wc  = prob.get_val(f'{e_name}.s_Wc')[0]
    s_PR  = prob.get_val(f'{e_name}.s_PR')[0]
    s_eff = prob.get_val(f'{e_name}.s_eff')[0]
    s_Nc  = prob.get_val(f'{e_name}.s_Nc')[0]

    RlineMap, NcMap = np.meshgrid(map_data.RlineMap, map_data.NcMap, sparse=False)
    a       = alpha_idx
    Wc_map  = map_data.WcMap[a, :, :]  * s_Wc
    PR_map  = (map_data.PRmap[a, :, :] - 1.0) * s_PR + 1.0
    eff_map = map_data.effMap[a, :, :] * s_eff
    Nc_map  = NcMap * s_Nc

    eff_cf = ax.contourf(Wc_map, PR_map, eff_map,
                         levels=eff_vals, cmap='viridis',
                         alpha=eff_alpha, zorder=1)

    eff_edge = eff_vals[eff_vals > 0]
    eff_cs = ax.contour(Wc_map, PR_map, eff_map,
                        levels=eff_edge, colors='k', linewidths=0.6, zorder=2)
    ax.clabel(eff_cs, fmt='%.2f', fontsize=6, inline=True, inline_spacing=2)

    if show_nclines:
        nc_cs = ax.contour(Wc_map, PR_map, Nc_map,
                           levels=map_data.NcMap * s_Nc,
                           colors='k', linewidths=0.8, linestyles='solid', zorder=2)
        ax.clabel(nc_cs, fmt='%.0f', fontsize=6, inline=True, inline_spacing=2)

    if show_rlines:
        r_cs = ax.contour(Wc_map, PR_map, RlineMap,
                          levels=map_data.RlineMap,
                          colors='k', linewidths=0.6, linestyles='solid',
                          alpha=1.0, zorder=2)
        ax.clabel(r_cs, fmt='%.2f', fontsize=6, inline=True, inline_spacing=2)

    stall_Wc = Wc_map[:, 0]
    stall_PR = PR_map[:, 0]
    idx      = np.argsort(stall_Wc)
    ax.plot(stall_Wc[idx], stall_PR[idx], 'k-', lw=2.0, zorder=3, label='Stall line')
    return eff_cf


def plot_compressor_map_oplines(prob, all_results, fn_fracs):
    """
    Compressor map with one VGT A4 sweep curve per thrust level.

    Fixed engine (A4=1.0) shown as open circle per Fn level.
    VGT sweep shown as a solid colored curve; star marks minimum TSFC.
    Yellow arrow connects fixed point to the min-TSFC VGT point.
    """
    des  = all_results['vgt']['des']
    T4_K = des['T4_design'] * RANKINE_TO_K

    fig, ax = plt.subplots(figsize=(13, 10))
    fig.suptitle(
        'Compressor Map — Fixed vs Variable A₄ Operating Points\n'
        f'Design T₄ = {T4_K:.0f} K   |   Sea Level Static   |   Physics dP/P\n'
        'Solid curves = VGT A₄ sweep per thrust level  (★ = min TSFC)    '
        '○ = Fixed A₄=1.0',
        fontsize=11, fontweight='bold')

    eff_cf = draw_compressor_map_background(
        ax, prob, 'DESIGN.comp',
        alpha_idx=0,
        eff_vals=np.linspace(0.70, 0.85, 25),
        show_rlines=False, show_nclines=True, eff_alpha=1.0)
    cb = plt.colorbar(eff_cf, ax=ax, shrink=0.55, pad=0.02)
    cb.set_label('Adiabatic efficiency  η_c  (—)', fontsize=10)

    ax.plot(des['comp_Wc_design'], des['comp_PR_design'],
            '*', ms=20, color='gold', markeredgecolor='k',
            markeredgewidth=1.2, zorder=10, label='Design point')

    for fn_frac in fn_fracs:
        color  = FN_COLORS.get(fn_frac, 'gray')
        fn_lbl = f'{int(fn_frac*100)}% Fₙ'

        # Fixed engine — single A4=1.0 marker
        fix_r  = all_results['fixed']['phys_dpqp'][fn_frac][0]
        fix_Wc = fix_r['comp_Wc']
        fix_PR = fix_r['comp_PR']
        ax.plot(fix_Wc, fix_PR,
                'o', ms=12, color='white',
                markeredgecolor=color, markeredgewidth=2.2, zorder=8)
        ax.annotate(f'{int(fn_frac*100)}%\nFixed',
                    xy=(fix_Wc, fix_PR),
                    xytext=(fix_Wc - 9, fix_PR + 0.08),
                    fontsize=7.5, color='white', fontweight='bold', zorder=9,
                    arrowprops=dict(arrowstyle='-', color='white', lw=0.5))

        # VGT A4 sweep curve
        vgt_pts = all_results['vgt']['phys_dpqp'][fn_frac]
        Wc_v    = np.array([r['comp_Wc']   for r in vgt_pts])
        PR_v    = np.array([r['comp_PR']   for r in vgt_pts])
        a4_v    = np.array([r['a4_scalar'] for r in vgt_pts])

        ax.plot(Wc_v, PR_v, '-', color='k',    lw=3.5, zorder=5)
        ax.plot(Wc_v, PR_v, '-', color=color,  lw=2.0, zorder=6,
                label=f'{fn_lbl} VGT sweep')
        ax.plot(Wc_v, PR_v, 'o', color=color,  ms=5,   zorder=7,
                markeredgecolor='k', markeredgewidth=0.4)

        # Endpoint labels (A4 min and max)
        for idx_ep, ha in [(0, 'right'), (-1, 'left')]:
            ax.annotate(f'A₄={a4_v[idx_ep]:.2f}',
                        xy=(Wc_v[idx_ep], PR_v[idx_ep]),
                        xytext=(Wc_v[idx_ep] + (3 if ha=='left' else -3),
                                PR_v[idx_ep] + 0.06),
                        fontsize=6.5, color=color, zorder=10,
                        arrowprops=dict(arrowstyle='-', color=color, lw=0.5))

        # Star at minimum TSFC
        opt_idx = int(np.argmin([r['TSFC'] for r in vgt_pts]))
        ax.plot(Wc_v[opt_idx], PR_v[opt_idx],
                '*', ms=16, color='white',
                markeredgecolor=color, markeredgewidth=1.2, zorder=9)

        # Yellow arrow: fixed → optimal VGT
        dwc = Wc_v[opt_idx] - fix_Wc
        dpr = PR_v[opt_idx] - fix_PR
        if np.hypot(dwc, dpr) > 0.5:
            ax.annotate('',
                        xy=(Wc_v[opt_idx], PR_v[opt_idx]),
                        xytext=(fix_Wc, fix_PR),
                        arrowprops=dict(arrowstyle='->', color='yellow',
                                        lw=2.0, mutation_scale=16),
                        zorder=9)

    ax.set_xlabel('Corrected Mass Flow  $W_c$  (lbm/s)', fontsize=11)
    ax.set_ylabel('Compressor Pressure Ratio  $\\pi_c$  (—)', fontsize=11)
    ax.legend(fontsize=8.5, loc='upper left',
              facecolor='k', labelcolor='white',
              edgecolor='white', framealpha=0.85)
    ax.grid(True, alpha=0.15, color='white', zorder=0)

    fig.tight_layout()
    fig.savefig('compressor_map_oplines.png', dpi=150, bbox_inches='tight')
    return fig


# ══════════════════════════════════════════════════════════════════════════════
#  MAIN
# ══════════════════════════════════════════════════════════════════════════════

if __name__ == '__main__':

    # ══════════════════════════════════════════════════════════════
    #  MAP DESIGN POINT EXTRACTION
    #  pyCycle Np convention: N / sqrt(Tt_degR), Tref = 1 degR
    # ══════════════════════════════════════════════════════════════

    _Nmech   = 8070.0
    _T4_degR = 2370.0
    _Np_des  = _Nmech / np.sqrt(_T4_degR)   # ≈ 165.77

    eff_fixed, PR_fixed = map_design_point(EngineHPTFixedMap, _Np_des)
    eff_vgt,   PR_vgt   = map_design_point(EngineHPTVGTMap,   _Np_des)

    print("=" * 65)
    print("  Map design point extraction")
    print(f"  Fixed:  eta={eff_fixed*100:.3f}%  PR={PR_fixed:.4f}")
    print(f"  VGT:    eta={eff_vgt*100:.3f}%    PR={PR_vgt:.4f}")
    print(f"  Leakage penalty: Δeta={(eff_fixed-eff_vgt)*100:+.3f}%")
    print("=" * 65)

    # ╔══════════════════════════════════════════════════════════════╗
    # ║  SHARED CYCLE CONFIG                                         ║
    # ╚══════════════════════════════════════════════════════════════╝
    FN_FRACS   = list(np.linspace(0.50, 1.00, 15))   # 11-point Fn sweep
    A4_BOUNDS  = (0.75, 1.05)                         # Brent search bounds for VGT

    BASE_CFG = dict(
        comp_map     = pyc.AXI5,
        Fn_design    = 11800.0,   # lbf
        T4_design    = _T4_degR,  # degR
        OPR          = 13.5,
        Nmech        = _Nmech,    # rpm
        comp_eff     = 0.83,
        inlet_MN     = 0.60,
        comp_MN      = 0.020,
        burner_MN    = 0.020,
        turb_MN      = 0.40,
        nozz_Cv      = 0.99,
        FAR_guess    = 0.0175,
        W_guess      = 168.0,
        fn_fractions = FN_FRACS,
        a4_scalars   = [1.0],     # single OD point; Brent drives actual A4 for VGT
    )

    # Gauntner cooling sizing (NASA-TM-81453) — used for initial guesses only.
    # Actual fracs are computed inside the Newton loop by ngv_calcs/bld_calcs.
    _T3_est_R = estimate_T3_rankine(BASE_CFG['OPR'], comp_eff=BASE_CFG['comp_eff'])
    _frac_ngv_des, _frac_blade_des = gauntner_cooling_fracs(
        BASE_CFG['T4_design'], _T3_est_R)

    CFG_FIXED = {
        **BASE_CFG,
        'turb_map'     : EngineHPTFixedMap,
        'turb_eff'     : eff_fixed,
        'turb_PR_guess': PR_fixed,
    }
    CFG_VGT = {
        **BASE_CFG,
        'turb_map'     : EngineHPTFixedMap,
        'turb_eff'     : eff_fixed,
        'turb_PR_guess': PR_fixed,
    }

    print("=" * 65)
    print("  Gauntner cooling sizing  (NASA-TM-81453)")
    print(f"  T4={BASE_CFG['T4_design']:.0f}°R  T3_est={_T3_est_R:.1f}°R")
    print(f"  T_metal: vane={T_METAL_VANE_R:.0f}°R  blade={T_METAL_BLADE_R:.0f}°R")
    print(f"  NGV={_frac_ngv_des*100:.2f}%  Blade={_frac_blade_des*100:.2f}%"
          f"  Total={(_frac_ngv_des+_frac_blade_des)*100:.2f}%")
    print("=" * 65)
    print(f" Fixed vs VGT — η_th vs Fn sweep  (endogenous physics dP/P)")
    print(f" Fn levels: {[f'{int(f*100)}%' for f in FN_FRACS]}")
    print(f" VGT A4 bounds: [{A4_BOUNDS[0]:.2f}, {A4_BOUNDS[1]:.2f}]  (Brent per Fn level)")
    print("=" * 65)

    # ── Helper: single OD solve at a fixed A4 ────────────────────────────────
    def _run_single_od(prob, mp, des, fn_frac, cfg, mode, a4=1.0):
        pt = mp.od_pts[0]
        prob.set_val(f'{pt}.orifice.CdA', des['CdA_liner'])
        set_turb_area(prob, pt, a4, des['s_Wp_design'], mode)
        prob.set_val(f'{pt}.balance.Fn_target',
                     fn_frac * cfg['Fn_design'], units='lbf')
        prob[pt + '.balance.W']     = des['W'] * fn_frac
        prob[pt + '.balance.Nmech'] = (des['Nmech']
                                       * fn_frac**0.5 * (1.0/a4)**0.3)
        prob[pt + '.balance.FAR']   = cfg.get('FAR_guess', 0.017) * fn_frac
        prob[pt + '.fc.balance.Pt'] = 14.696
        prob[pt + '.fc.balance.Tt'] = 518.67
        prob.model._get_subsystem(pt).nonlinear_solver.options['maxiter'] = 50
        prob.run_model()
        r          = extract_od_point(prob, pt)
        r['eta_th']    = extract_eta_th(prob, pt)
        r['a4_scalar'] = a4
        r['dPqP']      = float(prob.get_val(f'{pt}.orifice.dPqP')[0])
        r['fn_frac']   = fn_frac
        return r

    # ── Helper: Brent-optimal A4 with endogenous dP/P ────────────────────────
    def _run_opt_a4(prob, mp, des, fn_frac, cfg, mode, a4_bounds=A4_BOUNDS):
        pt        = mp.od_pts[0]
        Fn_target = fn_frac * cfg['Fn_design']
        prob.set_val(f'{pt}.orifice.CdA', des['CdA_liner'])

        T4_limit_R = cfg['T4_design']   # hard redline — never exceed design T4

        def _eval(a4):
            set_turb_area(prob, pt, a4, des['s_Wp_design'], mode)
            prob.set_val(f'{pt}.balance.Fn_target', Fn_target, units='lbf')
            prob[pt + '.balance.W']     = des['W'] * fn_frac
            prob[pt + '.balance.Nmech'] = (des['Nmech']
                                           * fn_frac**0.5 * (1.0/a4)**0.3)
            prob[pt + '.balance.FAR']   = cfg.get('FAR_guess', 0.017) * fn_frac
            prob[pt + '.fc.balance.Pt'] = 14.696
            prob[pt + '.fc.balance.Tt'] = 518.67
            prob.model._get_subsystem(pt).nonlinear_solver.options['maxiter'] = 25
            prob.run_model()
            T4_R = float(prob.get_val(f'{pt}.burner.Fl_O:tot:T', units='degR')[0])
            if T4_R > T4_limit_R:
                return -99.0   # T4 redline violated — steer Brent away
            eta = extract_eta_th(prob, pt)
            return eta if np.isfinite(eta) else -99.0

        res    = minimize_scalar(lambda a4: -_eval(a4),
                                 bounds=a4_bounds, method='bounded',
                                 options={'xatol': 1e-3})
        a4_opt = float(res.x)

        # Final cleanup solve at a4_opt with tighter maxiter
        set_turb_area(prob, pt, a4_opt, des['s_Wp_design'], mode)
        prob.set_val(f'{pt}.balance.Fn_target', Fn_target, units='lbf')
        prob[pt + '.balance.Nmech'] = (des['Nmech']
                                       * fn_frac**0.5 * (1.0/a4_opt)**0.3)
        prob[pt + '.balance.FAR']   = cfg.get('FAR_guess', 0.017) * fn_frac
        prob.model._get_subsystem(pt).nonlinear_solver.options['maxiter'] = 50
        prob.run_model()

        r          = extract_od_point(prob, pt)
        r['eta_th']    = extract_eta_th(prob, pt)
        r['a4_scalar'] = a4_opt
        r['dPqP']      = float(prob.get_val(f'{pt}.orifice.dPqP')[0])
        r['fn_frac']   = fn_frac
        print(f"    Fn={fn_frac*100:.0f}%  a4*={a4_opt:.4f}"
              f"  η_th={r['eta_th']*100:.4f}%"
              f"  T4={r['T4']*RANKINE_TO_K:.1f}K"
              f"  dP/P={r['dPqP']*100:.2f}%")
        return r

    # ── Helper: blade metal temperature and Gauntner cooling ─────────────────
    def _add_thermal(r, bld_frac):
        Tt4_rel_K   = turb_rel_temp_rankine(r['T4'], r['T4_exit']) * RANKINE_TO_K
        T3_K        = r['T3'] * RANKINE_TO_K
        r['T_metal'] = Tt4_rel_K - ETA_COOL * bld_frac * (Tt4_rel_K - T3_K)
        req_ngv, req_blade = gauntner_cooling_fracs(r['T4'], r['T3'],
                                                    T4_exit_R=r['T4_exit'])
        r['req_frac_ngv']   = req_ngv
        r['req_frac_blade'] = req_blade

    # ════════════════════════════════════════════════════════════════
    #  OUTER LOOP — Fixed then VGT
    # ════════════════════════════════════════════════════════════════
    all_results = {}
    prob_vgt    = None   # kept for compressor map background after loop

    for label, cfg, mode in [
        ('fixed', CFG_FIXED, 'sWp'),
        ('vgt',   CFG_VGT,   'sWp'),
    ]:
        print(f"\n{'█'*65}")
        print(f" {label.upper()} TURBINE  — {'single OD solve' if label == 'fixed' else 'Brent-optimal A4'} per Fn level")
        print(f"{'█'*65}")

        MPSingleFn = _make_mp_single_fn(cfg)
        prob_cb    = om.Problem()
        mp_cb      = prob_cb.model = MPSingleFn()
        prob_cb.setup(check=False)

        prob_cb.set_val('DESIGN.fc.alt',            0.0,              units='ft')
        prob_cb.set_val('DESIGN.fc.MN',             0.000001)
        prob_cb.set_val('DESIGN.balance.Fn_target', cfg['Fn_design'], units='lbf')
        prob_cb.set_val('DESIGN.balance.T4_target', cfg['T4_design'], units='degR')
        prob_cb.set_val('DESIGN.comp.PR',           cfg['OPR'])
        prob_cb.set_val('DESIGN.comp.eff',          cfg['comp_eff'])
        prob_cb.set_val('DESIGN.turb.eff',          cfg['turb_eff'])
        prob_cb.set_val('DESIGN.burner.dPqP',       DPQP_FIXED)
        if mode == 'alpha':
            prob_cb.set_val('DESIGN.turb.map.alphaMap', 1.0)
        prob_cb['DESIGN.balance.FAR']     = cfg.get('FAR_guess', 0.0175)
        prob_cb['DESIGN.balance.W']       = cfg.get('W_guess', 168.0)
        prob_cb['DESIGN.balance.turb_PR'] = cfg.get('turb_PR_guess', 3.5)
        prob_cb['DESIGN.fc.balance.Pt']   = 14.696
        prob_cb['DESIGN.fc.balance.Tt']   = 518.67
        # Seed ExecComp outputs so Newton starts near the converged cooling fracs
        prob_cb.set_val('DESIGN.cool_fracs.frac_ngv', _frac_ngv_des)
        prob_cb.set_val('DESIGN.cool_fracs.frac_bld', _frac_blade_des)
        for pt in mp_cb.od_pts:
            prob_cb.model._get_subsystem(pt).nonlinear_solver.options['maxiter'] = 0
        prob_cb.set_solver_print(level=-1)
        prob_cb.set_solver_print(level=2, depth=1)
        prob_cb.run_model()

        des_cb = extract_design(prob_cb)

        # Converged cooling fracs from CoolingCalcs (dynamic, in-solver)
        cfg['ngv_cool_frac'] = float(prob_cb.get_val('DESIGN.cool_fracs.frac_ngv')[0])
        cfg['bld_cool_frac'] = float(prob_cb.get_val('DESIGN.cool_fracs.frac_bld')[0])

        s_eff = prob_cb.get_val('DESIGN.turb.s_eff')[0]
        s_Wp  = prob_cb.get_val('DESIGN.turb.s_Wp')[0]
        print(f"  nozz area = {prob_cb.get_val('DESIGN.nozz.Throat:stat:area')[0]:.4f} in²")
        print(f"  Design: eta={des_cb['eff_design']*100:.3f}%"
              f"  s_Wp={s_Wp:.6f}  s_eff={s_eff:.6f}"
              f"  TSFC={des_cb['TSFC']:.5f}")

        # Design-point T_metal (reference)
        T3_des_K      = des_cb['T3_design']      * RANKINE_TO_K
        Tt4_rel_des_K = turb_rel_temp_rankine(des_cb['T4_design'],
                                              des_cb['T4_exit_design']) * RANKINE_TO_K
        T_metal_des = Tt4_rel_des_K - ETA_COOL * cfg['bld_cool_frac'] * (Tt4_rel_des_K - T3_des_K)
        print(f"  Cooling (Gauntner): NGV={cfg['ngv_cool_frac']*100:.2f}%"
              f"  blade={cfg['bld_cool_frac']*100:.2f}%"
              f"  T_metal_des={T_metal_des:.1f}K")

        # CdA calibrated from design-point flow state
        des_cb['CdA_liner'] = calc_CdA_liner(
            T3_des_K,
            psi_to_pa(des_cb['P3_design']),
            lbm_s_to_kg_s(des_cb['W']),
        )
        print(f"  CdA = {des_cb['CdA_liner']*1e4:.4f} cm²")

        # ── Per-Fn solves ─────────────────────────────────────────────────
        results_by_fn = {}
        print(f"\n  {'Fn%':>4}  solving...")
        for fn_frac in FN_FRACS:
            if label == 'fixed':
                r = _run_single_od(prob_cb, mp_cb, des_cb, fn_frac, cfg, mode)
                print(f"    Fn={fn_frac*100:.0f}%  A4=1.00"
                      f"  η_th={r['eta_th']*100:.4f}%"
                      f"  T4={r['T4']*RANKINE_TO_K:.1f}K"
                      f"  dP/P={r['dPqP']*100:.2f}%")
            else:
                r = _run_opt_a4(prob_cb, mp_cb, des_cb, fn_frac, cfg, mode)
            _add_thermal(r, cfg['bld_cool_frac'])
            results_by_fn[fn_frac] = r

        all_results[label] = {
            'des':         des_cb,
            'frac_ngv':    cfg['ngv_cool_frac'],
            'frac_blade':  cfg['bld_cool_frac'],
            'T_metal_des': T_metal_des,
            'by_fn':       results_by_fn,
        }

        if label == 'vgt':
            prob_vgt  = prob_cb
            mp_vgt    = mp_cb
            des_vgt   = des_cb
            cfg_vgt   = cfg
            mode_vgt  = mode

    # ════════════════════════════════════════════════════════════════
    #  BUILD PLOT ARRAYS
    # ════════════════════════════════════════════════════════════════
    fn_pct   = np.array(FN_FRACS) * 100
    a4_opt   = np.array([all_results['vgt']['by_fn'][f]['a4_scalar'] for f in FN_FRACS])

    eta_fix  = np.array([all_results['fixed']['by_fn'][f]['eta_th']    for f in FN_FRACS]) * 100
    T4_fix   = np.array([all_results['fixed']['by_fn'][f]['T4']        for f in FN_FRACS]) * RANKINE_TO_K
    Tm_fix   = np.array([all_results['fixed']['by_fn'][f]['T_metal']   for f in FN_FRACS])
    dP_fix   = np.array([all_results['fixed']['by_fn'][f]['dPqP']      for f in FN_FRACS]) * 100

    eta_vgt  = np.array([all_results['vgt']['by_fn'][f]['eta_th']      for f in FN_FRACS]) * 100
    T4_vgt   = np.array([all_results['vgt']['by_fn'][f]['T4']          for f in FN_FRACS]) * RANKINE_TO_K
    Tm_vgt   = np.array([all_results['vgt']['by_fn'][f]['T_metal']     for f in FN_FRACS])
    dP_vgt   = np.array([all_results['vgt']['by_fn'][f]['dPqP']        for f in FN_FRACS]) * 100

    d_eta    = eta_vgt - eta_fix       # positive = VGT better
    d_Tm     = Tm_vgt  - Tm_fix        # negative = VGT blade cooler
    d_T4     = T4_vgt  - T4_fix        # negative = VGT allows lower TIT

    def _style_ax(ax, xlabel='Fₙ (%)', ylabel=''):
        ax.set_xlabel(xlabel, fontsize=10)
        ax.set_ylabel(ylabel, fontsize=10)
        ax.grid(True, alpha=0.25)
        ax.spines['top'].set_visible(False)
        ax.spines['right'].set_visible(False)

    # ══════════════════════════════════════════════════════════════
    #  FIGURE 1 — η_th vs Fn  (Fixed vs VGT)
    # ══════════════════════════════════════════════════════════════
    fig1, ax1 = plt.subplots(figsize=(8, 5))
    fig1.suptitle('Thermal Efficiency vs Thrust — Fixed vs Variable A₄\n'
                  f'VGT: Brent-optimal A₄ ∈ [{A4_BOUNDS[0]:.2f}, {A4_BOUNDS[1]:.2f}]'
                  f'  |  Physics dP/P (endogenous)',
                  fontsize=11, fontweight='bold')

    ax1.plot(fn_pct, eta_fix, 'o-', color='steelblue', lw=2.2, ms=6,
             label='Fixed  (A₄ = 1.0)')
    ax1.plot(fn_pct, eta_vgt, 's-', color='firebrick', lw=2.2, ms=6,
             label='VGT  (A₄ optimal)')
    ax1.fill_between(fn_pct, eta_fix, eta_vgt,
                     where=(d_eta >= 0), alpha=0.12, color='firebrick',
                     label='VGT benefit')
    ax1.fill_between(fn_pct, eta_fix, eta_vgt,
                     where=(d_eta < 0),  alpha=0.12, color='steelblue',
                     label='Fixed benefit')

    # Annotate Δη at 50% and 100% Fn
    for fn_pct_ann, align in [(50, 'left'), (100, 'right')]:
        idx = int(np.argmin(np.abs(fn_pct - fn_pct_ann)))
        ax1.annotate(f'Δη={d_eta[idx]:+.3f}%',
                     xy=(fn_pct[idx], (eta_fix[idx] + eta_vgt[idx]) / 2),
                     fontsize=8, color='dimgray',
                     ha=align, va='center')

    ax1.legend(fontsize=9, loc='lower right')
    _style_ax(ax1, ylabel='η_th (%)')
    fig1.tight_layout()
    fig1.savefig('fixed_vs_vgt_eta_th.png', dpi=150, bbox_inches='tight')

    # ══════════════════════════════════════════════════════════════
    #  FIGURE 2 — ΔT_metal vs Fn  (VGT − Fixed)
    # ══════════════════════════════════════════════════════════════
    fig2, ax2 = plt.subplots(figsize=(8, 5))
    fig2.suptitle('Blade Metal Temperature Reduction — VGT vs Fixed\n'
                  f'Cooling: NGV={_frac_ngv_des*100:.2f}%  blade={_frac_blade_des*100:.2f}%'
                  f'  η_cool={ETA_COOL}  (Horlock 2001)',
                  fontsize=11, fontweight='bold')

    ax2.axhline(0.0, color='gray', ls='--', lw=1.2, alpha=0.6)
    ax2.plot(fn_pct, d_Tm, 'o-', color='firebrick', lw=2.2, ms=6,
             label='ΔT_metal  VGT − Fixed')
    ax2.fill_between(fn_pct, 0, d_Tm,
                     where=(d_Tm <= 0), alpha=0.15, color='steelblue',
                     label='VGT blade cooler')
    ax2.fill_between(fn_pct, 0, d_Tm,
                     where=(d_Tm > 0),  alpha=0.15, color='firebrick',
                     label='VGT blade hotter')

    idx_max_benefit = int(np.argmin(d_Tm))
    ax2.annotate(f'Max ΔT={d_Tm[idx_max_benefit]:+.1f}K\n'
                 f'Fn={fn_pct[idx_max_benefit]:.0f}%',
                 xy=(fn_pct[idx_max_benefit], d_Tm[idx_max_benefit]),
                 xytext=(fn_pct[idx_max_benefit] + 5, d_Tm[idx_max_benefit] + 0.5),
                 fontsize=8.5, color='steelblue',
                 bbox=dict(boxstyle='round,pad=0.3', fc='white',
                           ec='steelblue', alpha=0.9),
                 arrowprops=dict(arrowstyle='->', color='steelblue', lw=0.8))

    ax2.legend(fontsize=9)
    _style_ax(ax2, ylabel='ΔT_metal  (K)  [VGT − Fixed]')
    fig2.tight_layout()
    fig2.savefig('fixed_vs_vgt_delta_Tmetal.png', dpi=150, bbox_inches='tight')

    # ══════════════════════════════════════════════════════════════
    #  FIGURE 3 — T4 vs Fn  (Fixed and VGT)
    # ══════════════════════════════════════════════════════════════
    fig3, ax3 = plt.subplots(figsize=(8, 5))
    fig3.suptitle('Turbine Inlet Temperature vs Thrust\n'
                  'VGT at optimal A₄ allows lower T4 for the same Fₙ',
                  fontsize=11, fontweight='bold')

    ax3.plot(fn_pct, T4_fix, 'o-', color='steelblue', lw=2.2, ms=6,
             label='Fixed  (A₄ = 1.0)')
    ax3.plot(fn_pct, T4_vgt, 's-', color='firebrick', lw=2.2, ms=6,
             label='VGT  (A₄ optimal)')
    ax3.fill_between(fn_pct, T4_fix, T4_vgt,
                     where=(d_T4 <= 0), alpha=0.12, color='steelblue',
                     label='VGT cooler inlet')
    ax3.fill_between(fn_pct, T4_fix, T4_vgt,
                     where=(d_T4 > 0),  alpha=0.12, color='firebrick',
                     label='VGT hotter inlet')

    # T4 redline at design temperature — axhspan shades the forbidden region
    T4_des_K = _T4_degR * RANKINE_TO_K
    ax3.axhline(T4_des_K, color='crimson', ls='-', lw=2.0, zorder=5,
                label=f'T₄ redline = {T4_des_K:.0f} K')
    ax3.axhspan(T4_des_K, T4_des_K + 200, alpha=0.07, color='crimson', zorder=0)
    ax3.annotate(f'T₄ redline  {T4_des_K:.0f} K',
                 xy=(fn_pct[0], T4_des_K),
                 xytext=(fn_pct[0] + 1, T4_des_K + 4),
                 fontsize=8, color='crimson', fontweight='bold')

    ax3.legend(fontsize=9)
    _style_ax(ax3, ylabel='T₄  (K)')
    fig3.tight_layout()
    fig3.savefig('fixed_vs_vgt_T4.png', dpi=150, bbox_inches='tight')

    # ══════════════════════════════════════════════════════════════
    #  FIGURE 4 — VGT schedule: optimal A4 vs Fn fraction
    # ══════════════════════════════════════════════════════════════
    fig4, ax4a = plt.subplots(figsize=(8, 5))
    fig4.suptitle('VGT Optimal A₄ Schedule vs Thrust\n'
                  'A₄ < 1.0 → smaller throat → higher PR  |  A₄ > 1.0 → larger throat',
                  fontsize=11, fontweight='bold')

    ax4a.axhline(1.0, color='steelblue', ls='--', lw=1.5, alpha=0.7,
                 label='Fixed baseline  (A₄ = 1.0)')
    ax4a.plot(fn_pct, a4_opt, 's-', color='firebrick', lw=2.2, ms=6,
              label='VGT optimal A₄')
    ax4a.fill_between(fn_pct, 1.0, a4_opt,
                      where=(a4_opt < 1.0), alpha=0.12, color='steelblue',
                      label='A₄ closed (higher PR)')
    ax4a.fill_between(fn_pct, 1.0, a4_opt,
                      where=(a4_opt >= 1.0), alpha=0.12, color='firebrick',
                      label='A₄ open (lower PR)')

    # Annotate optimal A4 at design Fn
    idx_des = int(np.argmin(np.abs(fn_pct - 100)))
    ax4a.annotate(f'Design Fn\nA₄={a4_opt[idx_des]:.3f}',
                  xy=(fn_pct[idx_des], a4_opt[idx_des]),
                  xytext=(fn_pct[idx_des] - 10, a4_opt[idx_des] + 0.02),
                  fontsize=8.5, color='firebrick',
                  bbox=dict(boxstyle='round,pad=0.3', fc='white',
                            ec='firebrick', alpha=0.9),
                  arrowprops=dict(arrowstyle='->', color='firebrick', lw=0.8))

    # Second y-axis: combustor dP/P for both configurations
    ax4b = ax4a.twinx()
    ax4b.plot(fn_pct, dP_fix, 'o:', color='steelblue', lw=1.5, ms=4, alpha=0.7,
              label='dP/P Fixed')
    ax4b.plot(fn_pct, dP_vgt, 's:', color='firebrick', lw=1.5, ms=4, alpha=0.7,
              label='dP/P VGT')
    ax4b.set_ylabel('Combustor ΔP/P (%)', fontsize=9, color='dimgray')
    ax4b.tick_params(axis='y', labelcolor='dimgray')
    ax4b.spines['top'].set_visible(False)

    # Merge legends
    lines_a, lbl_a = ax4a.get_legend_handles_labels()
    lines_b, lbl_b = ax4b.get_legend_handles_labels()
    ax4a.legend(lines_a + lines_b, lbl_a + lbl_b, fontsize=8, loc='upper left')

    ax4a.set_xlabel('Fₙ (%)', fontsize=10)
    ax4a.set_ylabel('A₄ scalar  (1.0 = design)', fontsize=10)
    ax4a.grid(True, alpha=0.25)
    ax4a.spines['top'].set_visible(False)
    ax4a.spines['right'].set_visible(False)
    fig4.tight_layout()
    fig4.savefig('vgt_a4_schedule.png', dpi=150, bbox_inches='tight')

    plt.show()

    # ── Summary table ─────────────────────────────────────────────────────────
    HDR = (f"  {'Fn%':>4}  {'η_fix%':>8}  {'η_vgt%':>8}"
           f"  {'Δη%':>7}  {'T4_fix':>7}  {'T4_vgt':>7}"
           f"  {'ΔT4':>6}  {'Tm_fix':>7}  {'Tm_vgt':>7}"
           f"  {'ΔTm':>6}  {'A4_opt':>7}  {'dP/P_v%':>8}")
    SEP = "  " + "-" * (len(HDR) - 2)
    print("\n" + "=" * len(HDR))
    print("  SUMMARY — Fixed vs VGT (Brent-optimal A4, physics dP/P)")
    print("=" * len(HDR))
    print(HDR)
    print(SEP)
    for i, fn_frac in enumerate(FN_FRACS):
        print(f"  {int(fn_frac*100):4d}"
              f"  {eta_fix[i]:8.4f}  {eta_vgt[i]:8.4f}"
              f"  {d_eta[i]:+7.4f}"
              f"  {T4_fix[i]:7.1f}  {T4_vgt[i]:7.1f}"
              f"  {d_T4[i]:+6.1f}"
              f"  {Tm_fix[i]:7.1f}  {Tm_vgt[i]:7.1f}"
              f"  {d_Tm[i]:+6.1f}"
              f"  {a4_opt[i]:7.4f}"
              f"  {dP_vgt[i]:8.3f}")
    print(SEP)
    
    
