"""
combustor_pycycle_integration.py
---------------------------------
Self-contained A4 variation study with physics-based combustor pressure drop.

Edit the CYCLE CONFIG block in __main__ to change:
  - Maps (comp_map, turb_map)
  - Design targets (Fn, T4, OPR, Nmech, ...)
  - A4 sweep range and resolution
  - Thrust levels for Study 2
  - Turbine area mode ('sWp' or 'alpha')

Turbine area variation modes
-----------------------------
  'sWp'   : s_Wp *= a4_scalar  — works with any map
  'alpha' : turb.map.alphaMap = a4_scalar  — requires variable-area alphaMap
            (generated by generate_turbine_map.py with area_fracs as alphaMap)

Combustor pressure drop model
------------------------------
  Total-to-total orifice:
    mdot = CdA * sqrt(2 * rho_t3 * (Pt3 - Pt4))
    pi_b = 1 - (mdot/CdA)^2 / (2 * rho_t3 * Pt3)
  CdA back-calculated from design point at fixed reference dPqP.
"""

from __future__ import annotations

import sys
import time
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm
from matplotlib.lines import Line2D
import pint

import openmdao.api as om
import pycycle.api as pyc

import cantera as ct

from Combustor_a4_sweep import (
    _gas, FAR_ST, FUEL, MECH, PHASE, LHV,
)
import os
def clear_terminal():
    if os.name == 'nt':
        _ = os.system('cls')
clear_terminal()
ureg = pint.UnitRegistry()
Q_   = ureg.Quantity

# ══════════════════════════════════════════════════════════════════════════════
#  UNIT CONVERSION CONSTANTS
# ══════════════════════════════════════════════════════════════════════════════

LBM_S_TO_KG_S = 0.453592
LBF_TO_KN     = 0.00444822
RANKINE_TO_K  = 5.0 / 9.0
PSI_TO_KPA    = 6.89476

# ══════════════════════════════════════════════════════════════════════════════
#  STUDY CONSTANTS
# ══════════════════════════════════════════════════════════════════════════════

DPQP_FIXED = 0.05
DPQP_TOL   = 0.001
MAX_OUTER  = 10
FN_COLORS  = {0.60: "seagreen", 0.70: "darkorange",
              0.80: "firebrick", 0.90: "mediumpurple", 1.00: "steelblue"}


# ══════════════════════════════════════════════════════════════════════════════
#  UNIT HELPERS
# ══════════════════════════════════════════════════════════════════════════════

def rankine_to_kelvin(T_R):  return Q_(T_R, "degR").to("K").magnitude
def psi_to_pa(P_psi):        return Q_(P_psi, "psi").to("Pa").magnitude
def lbm_s_to_kg_s(w):        return Q_(w, "lb/s").to("kg/s").magnitude


# ══════════════════════════════════════════════════════════════════════════════
#  CANTERA HELPERS
# ══════════════════════════════════════════════════════════════════════════════

_GRI30 = ct.Solution("gri30.yaml")

def rho_total(Tt_K, Pt_Pa):
    _GRI30.TPX = Tt_K, Pt_Pa, "O2:0.21, N2:0.79"
    return float(_GRI30.density)


# ══════════════════════════════════════════════════════════════════════════════
#  COMBUSTOR PRESSURE DROP MODEL
# ══════════════════════════════════════════════════════════════════════════════

def physics_pib(Pt3_Pa, Tt3_K, mdot_si, CdA):
    rho_t3 = rho_total(Tt3_K, Pt3_Pa)
    dPt    = (mdot_si / CdA) ** 2 / (2.0 * rho_t3)
    dPqP   = dPt / Pt3_Pa
    return float(1.0 - dPqP), float(dPqP)


def calc_CdA_liner(Tt3_K, Pt3_Pa, mdot_si, dPqP_ref=None):
    if dPqP_ref is None:
        dPqP_ref = DPQP_FIXED
    rho_t3 = rho_total(Tt3_K, Pt3_Pa)
    dPt    = dPqP_ref * Pt3_Pa
    return float(mdot_si / np.sqrt(2.0 * rho_t3 * dPt))


# ══════════════════════════════════════════════════════════════════════════════
#  THERMAL EFFICIENCY
# ══════════════════════════════════════════════════════════════════════════════

def extract_eta_th(prob, pt):
    V_exh  = Q_(float(prob.get_val(f"{pt}.nozz.Fl_O:stat:V")[0]),
                "ft/s").to("m/s").magnitude
    m_exh  = Q_(float(prob.get_val(f"{pt}.inlet.Fl_O:stat:W")[0]) +
                float(prob.get_val(f"{pt}.burner.Wfuel")[0]),
                "lb/s").to("kg/s").magnitude
    Wfuel  = Q_(float(prob.get_val(f"{pt}.burner.Wfuel")[0]),
                "lb/s").to("kg/s").magnitude
    return float(0.5 * m_exh * V_exh**2 / (Wfuel * LHV))


# ══════════════════════════════════════════════════════════════════════════════
#  CYCLE COMPONENTS  (parameterised by cfg)
# ══════════════════════════════════════════════════════════════════════════════

def _make_turbojet_core(comp_map, turb_map):
    """Return a _setup_core(self) closure with all subsystems, flow connections,
    scalar connects, and solver config — shared by all three Cycle variants."""
    def _setup_core(self):
        self.options['thermo_method'] = 'TABULAR'
        self.options['thermo_data']   = pyc.AIR_JETA_TAB_SPEC

        self.add_subsystem('fc',     pyc.FlightConditions())
        self.add_subsystem('inlet',  pyc.Inlet())
        self.add_subsystem('comp',   pyc.Compressor(map_data=comp_map,
                                                     map_extrap=True),
                                     promotes_inputs=['Nmech'])
        self.add_subsystem('bld3',   pyc.BleedOut(bleed_names=['ngv_cool', 'bld_cool']))
        self.add_subsystem('burner', pyc.Combustor(fuel_type='FAR'))
        self.add_subsystem('turb',   pyc.Turbine(map_data=turb_map,
                                                  bleed_names=['ngv_cool', 'bld_cool'],
                                                  map_extrap=True),
                                     promotes_inputs=['Nmech'])
        self.add_subsystem('nozz',   pyc.Nozzle(nozzType='CD', lossCoef='Cv'))
        self.add_subsystem('shaft',  pyc.Shaft(num_ports=2),
                                     promotes_inputs=['Nmech'])
        self.add_subsystem('perf',   pyc.Performance(num_nozzles=1, num_burners=1))

        self.pyc_connect_flow('fc.Fl_O',       'inlet.Fl_I',  connect_w=False)
        self.pyc_connect_flow('inlet.Fl_O',    'comp.Fl_I')
        self.pyc_connect_flow('comp.Fl_O',     'bld3.Fl_I')
        self.pyc_connect_flow('bld3.Fl_O',     'burner.Fl_I')
        self.pyc_connect_flow('burner.Fl_O',   'turb.Fl_I')
        self.pyc_connect_flow('bld3.ngv_cool', 'turb.ngv_cool', connect_stat=False)
        self.pyc_connect_flow('bld3.bld_cool', 'turb.bld_cool', connect_stat=False)
        self.pyc_connect_flow('turb.Fl_O',     'nozz.Fl_I')

        self.connect('comp.trq',         'shaft.trq_0')
        self.connect('turb.trq',         'shaft.trq_1')
        self.connect('fc.Fl_O:stat:P',   'nozz.Ps_exhaust')
        self.connect('inlet.Fl_O:tot:P', 'perf.Pt2')
        self.connect('comp.Fl_O:tot:P',  'perf.Pt3')
        self.connect('burner.Wfuel',     'perf.Wfuel_0')
        self.connect('inlet.F_ram',      'perf.ram_drag')
        self.connect('nozz.Fg',          'perf.Fg_0')

        newton = self.nonlinear_solver = om.NewtonSolver()
        newton.options['atol']             = 1e-6
        newton.options['rtol']             = 1e-6
        newton.options['iprint']           = 2
        newton.options['maxiter']          = 15
        newton.options['solve_subsystems'] = True
        newton.options['max_sub_solves']   = 100
        newton.options['reraise_child_analysiserror'] = False
        self.linear_solver = om.DirectSolver()

    return _setup_core


def _make_turbojet(cfg):
    _core = _make_turbojet_core(cfg['comp_map'], cfg['turb_map'])

    class Turbojet(pyc.Cycle):
        def setup(self):
            _core(self)
            design = self.options['design']
            bal = self.add_subsystem('balance', om.BalanceComp())
            if design:
                bal.add_balance('W', units='lbm/s', eq_units='lbf',
                                rhs_name='Fn_target')
                self.connect('balance.W',  'inlet.Fl_I:stat:W')
                self.connect('perf.Fn',    'balance.lhs:W')

                bal.add_balance('FAR', eq_units='degR', lower=1e-4,
                                val=0.017, rhs_name='T4_target')
                self.connect('balance.FAR',       'burner.Fl_I:FAR')
                self.connect('burner.Fl_O:tot:T', 'balance.lhs:FAR')

                bal.add_balance('turb_PR', val=1.5, lower=1.001, upper=8,
                                eq_units='hp', rhs_val=0.)
                self.connect('balance.turb_PR', 'turb.PR')
                self.connect('shaft.pwr_net',   'balance.lhs:turb_PR')
            super().setup()

    return Turbojet


def _make_turbojet_const_tt4(cfg):
    _core = _make_turbojet_core(cfg['comp_map'], cfg['turb_map'])

    class TurbojetConstTt4(pyc.Cycle):
        def setup(self):
            _core(self)
            bal = self.add_subsystem('balance', om.BalanceComp())

            bal.add_balance('FAR', eq_units='degR', lower=1e-4,
                            val=0.017, rhs_name='T4_target')
            self.connect('balance.FAR',       'burner.Fl_I:FAR')
            self.connect('burner.Fl_O:tot:T', 'balance.lhs:FAR')

            bal.add_balance('Nmech', val=8070., units='rpm',
                            lower=500., eq_units='hp', rhs_val=0.)
            self.connect('balance.Nmech', 'Nmech')
            self.connect('shaft.pwr_net', 'balance.lhs:Nmech')

            bal.add_balance('W', val=168.0, units='lbm/s',
                            eq_units='inch**2', rhs_name='nozz_area_target')
            self.connect('balance.W',             'inlet.Fl_I:stat:W')
            self.connect('nozz.Throat:stat:area', 'balance.lhs:W')
            super().setup()

    return TurbojetConstTt4


def _make_turbojet_const_fn(cfg):
    _core = _make_turbojet_core(cfg['comp_map'], cfg['turb_map'])

    class TurbojetConstFn(pyc.Cycle):
        def setup(self):
            _core(self)
            bal = self.add_subsystem('balance', om.BalanceComp())

            bal.add_balance('FAR', eq_units='lbf', lower=1e-4,
                            val=0.017, rhs_name='Fn_target')
            self.connect('balance.FAR', 'burner.Fl_I:FAR')
            self.connect('perf.Fn',     'balance.lhs:FAR')

            bal.add_balance('Nmech', val=8070., units='rpm',
                            lower=500., eq_units='hp', rhs_val=0.)
            self.connect('balance.Nmech', 'Nmech')
            self.connect('shaft.pwr_net', 'balance.lhs:Nmech')

            bal.add_balance('W', val=168.0, units='lbm/s',
                            eq_units='inch**2', rhs_name='nozz_area_target')
            self.connect('balance.W',             'inlet.Fl_I:stat:W')
            self.connect('nozz.Throat:stat:area', 'balance.lhs:W')
            super().setup()

    return TurbojetConstFn


# ══════════════════════════════════════════════════════════════════════════════
#  MULTI-POINT MODELS
# ══════════════════════════════════════════════════════════════════════════════

def _add_design_point_and_params(mp, Turbojet, cfg, include_dPqP=True):
    """Register DESIGN point, Mach/speed defaults, and cooling cycle params."""
    mp.pyc_add_pnt('DESIGN', Turbojet())
    mp.set_input_defaults('DESIGN.Nmech',     cfg['Nmech'],    units='rpm')
    mp.set_input_defaults('DESIGN.inlet.MN',  cfg['inlet_MN'])
    mp.set_input_defaults('DESIGN.comp.MN',   cfg['comp_MN'])
    mp.set_input_defaults('DESIGN.burner.MN', cfg['burner_MN'])
    mp.set_input_defaults('DESIGN.turb.MN',   cfg['turb_MN'])
    if include_dPqP:
        mp.pyc_add_cycle_param('burner.dPqP',          cfg['burner_dPqP'])
    mp.pyc_add_cycle_param('nozz.Cv',              cfg['nozz_Cv'])
    mp.pyc_add_cycle_param('bld3.ngv_cool:frac_W', cfg['ngv_cool_frac'])
    mp.pyc_add_cycle_param('turb.ngv_cool:frac_P', 1.0)
    mp.pyc_add_cycle_param('bld3.bld_cool:frac_W', cfg['bld_cool_frac'])
    mp.pyc_add_cycle_param('turb.bld_cool:frac_P', 0.0)


def _connect_od_scalars(mp, od_pts):
    """Propagate DESIGN map scalars and nozzle area to all OD points."""
    for pt in od_pts:
        mp.connect('DESIGN.nozz.Throat:stat:area', f'{pt}.balance.nozz_area_target')
        for sc in ['s_PR', 's_Wc', 's_eff', 's_Nc']:
            mp.connect(f'DESIGN.comp.{sc}', f'{pt}.comp.{sc}')
        for sc in ['s_PR', 's_eff', 's_Np']:
            mp.connect(f'DESIGN.turb.{sc}', f'{pt}.turb.{sc}')


def _make_mp_const_tt4(cfg):
    Turbojet         = _make_turbojet(cfg)
    TurbojetConstTt4 = _make_turbojet_const_tt4(cfg)

    class MPConstTt4(pyc.MPCycle):
        def setup(self):
            _add_design_point_and_params(self, Turbojet, cfg)

            self.a4_scalars = cfg['a4_scalars']
            self.a4_pts     = [f'A4_{i:03d}' for i in range(len(self.a4_scalars))]

            for pt in self.a4_pts:
                self.pyc_add_pnt(pt, TurbojetConstTt4(design=False))
                self.set_input_defaults(pt + '.fc.MN',  0.000001)
                self.set_input_defaults(pt + '.fc.alt', 0.0, units='ft')

            _connect_od_scalars(self, self.a4_pts)
            super().setup()

    return MPConstTt4


def _make_mp_const_fn(cfg):
    Turbojet        = _make_turbojet(cfg)
    TurbojetConstFn = _make_turbojet_const_fn(cfg)

    class MPConstFn(pyc.MPCycle):
        def setup(self):
            _add_design_point_and_params(self, Turbojet, cfg)

            self.fn_fractions = cfg['fn_fractions']
            self.a4_scalars   = cfg['a4_scalars']
            self.od_pts       = []

            for fi in range(len(self.fn_fractions)):
                for ai in range(len(self.a4_scalars)):
                    pt = f'FN{fi:02d}_A4_{ai:03d}'
                    self.od_pts.append(pt)
                    self.pyc_add_pnt(pt, TurbojetConstFn(design=False))
                    self.set_input_defaults(pt + '.fc.MN',  0.000001)
                    self.set_input_defaults(pt + '.fc.alt', 0.0, units='ft')

            _connect_od_scalars(self, self.od_pts)
            super().setup()

    return MPConstFn


# ══════════════════════════════════════════════════════════════════════════════
#  RESULT EXTRACTION
# ══════════════════════════════════════════════════════════════════════════════

def viewer(prob, pt, file=sys.stdout):
    summary = (
        prob[pt + '.fc.Fl_O:stat:MN'],
        prob[pt + '.fc.alt'],
        prob[pt + '.inlet.Fl_O:stat:W'],
        prob[pt + '.perf.Fn'],
        prob[pt + '.perf.Fg'],
        prob[pt + '.inlet.F_ram'],
        prob[pt + '.perf.OPR'],
        prob[pt + '.perf.TSFC'],
    )
    print(file=file, flush=True)
    print('─' * 76, file=file)
    print(f'  POINT: {pt}', file=file)
    print('─' * 76, file=file)
    print('  Mach      Alt       W      Fn      Fg    Fram     OPR     TSFC', file=file)
    print(' %7.5f  %7.1f %7.3f %7.1f %7.1f %7.1f %7.3f  %7.5f' % summary,
          file=file, flush=True)
    fs_full = [f'{pt}.{fs}' for fs in
               ['fc.Fl_O', 'inlet.Fl_O', 'comp.Fl_O', 'bld3.Fl_O',
                'burner.Fl_O', 'turb.Fl_O', 'nozz.Fl_O']]
    pyc.print_flow_station(prob, fs_full, file=file)
    pyc.print_compressor(prob, [f'{pt}.comp'],  file=file)
    pyc.print_burner(prob,     [f'{pt}.burner'])
    pyc.print_turbine(prob,    [f'{pt}.turb'],  file=file)
    pyc.print_nozzle(prob,     [f'{pt}.nozz'],  file=file)
    pyc.print_shaft(prob,      [f'{pt}.shaft'], file=file)


def extract_design(prob, pt='DESIGN'):
    W_des  = prob.get_val(f'{pt}.inlet.Fl_O:stat:W',  units='lbm/s')[0]
    Pt_des = prob.get_val(f'{pt}.inlet.Fl_O:tot:P',   units='psi')[0]
    Tt_des = prob.get_val(f'{pt}.inlet.Fl_O:tot:T',   units='degR')[0]
    Wc_des = W_des * np.sqrt(Tt_des / 518.67) / (Pt_des / 14.696)
    return {
        'pi_c':           prob.get_val(f'{pt}.perf.OPR')[0],
        'Nmech':          prob.get_val(f'{pt}.shaft.Nmech',       units='rpm')[0],
        'W':              W_des,
        'TSFC':           prob.get_val(f'{pt}.perf.TSFC',         units='lbm/(h*lbf)')[0],
        'T4_design':      prob.get_val(f'{pt}.burner.Fl_O:tot:T', units='degR')[0],
        's_Wp_design':    prob.get_val(f'{pt}.turb.s_Wp')[0],
        'eff_design':     prob.get_val(f'{pt}.turb.eff')[0],
        'comp_PR_design': prob.get_val(f'{pt}.comp.PR')[0],
        'comp_Wc_design': Wc_des,
        'Fn_design':      prob.get_val(f'{pt}.perf.Fn',           units='lbf')[0],
        'T3_design':      prob.get_val(f'{pt}.comp.Fl_O:tot:T',   units='degR')[0],
        'P3_design':      prob.get_val(f'{pt}.comp.Fl_O:tot:P',   units='lbf/inch**2')[0],
    }


def extract_od_point(prob, pt):
    W_od  = prob.get_val(f'{pt}.inlet.Fl_O:stat:W', units='lbm/s')[0]
    Pt_od = prob.get_val(f'{pt}.inlet.Fl_O:tot:P',  units='psi')[0]
    Tt_od = prob.get_val(f'{pt}.inlet.Fl_O:tot:T',  units='degR')[0]
    Wc_od = W_od * np.sqrt(Tt_od / 518.67) / (Pt_od / 14.696)
    return {
        'pi_c':     prob.get_val(f'{pt}.perf.OPR')[0],
        'Nmech':    prob.get_val(f'{pt}.shaft.Nmech',        units='rpm')[0],
        'W':        W_od,
        'Fn':       prob.get_val(f'{pt}.perf.Fn',            units='lbf')[0],
        'TSFC':     prob.get_val(f'{pt}.perf.TSFC',          units='lbm/(h*lbf)')[0],
        'T3':       prob.get_val(f'{pt}.comp.Fl_O:tot:T',    units='degR')[0],
        'P3':       prob.get_val(f'{pt}.comp.Fl_O:tot:P',    units='lbf/inch**2')[0],
        'T4':       prob.get_val(f'{pt}.burner.Fl_O:tot:T',  units='degR')[0],
        'comp_PR':  prob.get_val(f'{pt}.comp.PR')[0],
        'comp_Wc':  Wc_od,
        'turb_PR':  prob.get_val(f'{pt}.turb.PR')[0],
        'turb_eff': prob.get_val(f'{pt}.turb.eff')[0],
        'turb_Wp':  prob.get_val(f'{pt}.turb.Wp')[0],
    }


# ══════════════════════════════════════════════════════════════════════════════
#  TURBINE AREA CONTROL
# ══════════════════════════════════════════════════════════════════════════════

def set_turb_area(prob, pt, a4_scalar, s_Wp_design, mode):
    if mode == 'sWp':
        prob.set_val(f"{pt}.turb.s_Wp", s_Wp_design * a4_scalar)
    elif mode == 'alpha':
        prob.set_val(f"{pt}.turb.map.alphaMap", a4_scalar)
        prob.set_val(f"{pt}.turb.s_Wp", s_Wp_design)  # alphaMap controls area; s_Wp stays at design
    else:
        raise ValueError(f"Unknown TURB_AREA_MODE: {mode!r}  (use 'sWp' or 'alpha')")


# ══════════════════════════════════════════════════════════════════════════════
#  STUDY 1 — CONSTANT Tt4
# ══════════════════════════════════════════════════════════════════════════════

def run_study1(cfg, mode):
    print('\n' + '█' * 60)
    print(f' STUDY 1 — Constant Tt4, Variable A4  [mode={mode}]')
    print('█' * 60)

    MPConstTt4 = _make_mp_const_tt4(cfg)
    prob = om.Problem()
    mp   = prob.model = MPConstTt4()
    prob.setup(check=False)

    # Design inputs
    prob.set_val('DESIGN.fc.alt',            0.0,               units='ft')
    prob.set_val('DESIGN.fc.MN',             0.000001)
    prob.set_val('DESIGN.balance.Fn_target', cfg['Fn_design'],  units='lbf')
    prob.set_val('DESIGN.balance.T4_target', cfg['T4_design'],  units='degR')
    prob.set_val('DESIGN.comp.PR',           cfg['OPR'])
    prob.set_val('DESIGN.comp.eff',          cfg['comp_eff'])
    prob.set_val('DESIGN.turb.eff',          cfg['turb_eff'])
    prob['DESIGN.balance.FAR']     = cfg.get('FAR_guess',     0.0175)
    prob['DESIGN.balance.W']       = cfg.get('W_guess',       168.0)
    prob['DESIGN.balance.turb_PR'] = cfg.get('turb_PR_guess', 3.5)
    prob['DESIGN.fc.balance.Pt']   = 14.696
    prob['DESIGN.fc.balance.Tt']   = 518.67

    for pt in mp.a4_pts:
        prob[pt + '.balance.FAR']   = cfg.get('FAR_guess', 0.017)
        prob[pt + '.balance.Nmech'] = cfg['Nmech']
        prob[pt + '.balance.W']     = cfg.get('W_guess', 168.0)
        prob[pt + '.fc.balance.Pt'] = 14.696
        prob[pt + '.fc.balance.Tt'] = 518.67
        prob.set_val(pt + '.balance.T4_target', cfg['T4_design'], units='degR')
        prob.model._get_subsystem(pt).nonlinear_solver.options['maxiter'] = 0

    prob.set_solver_print(level=-1)
    prob.set_solver_print(level=2, depth=1)

    print('\n── Design point ──')
    t0 = time.time()
    prob.run_model()
    print(f'Design solved in {time.time()-t0:.1f}s')

    design_results = extract_design(prob)
    viewer(prob, 'DESIGN')
    print(f"\nDesign PR={design_results['pi_c']:.3f}  s_Wp={design_results['s_Wp_design']:.6f}")

    # Set design alpha for alpha mode
    if mode == 'alpha':
        prob.set_val('DESIGN.turb.map.alphaMap', 1.0)

    print('\n── A4 sweep ──')
    for pt in mp.a4_pts:
        prob.model._get_subsystem(pt).nonlinear_solver.options['maxiter'] = 15

    for pt, a4 in zip(mp.a4_pts, mp.a4_scalars):
        set_turb_area(prob, pt, a4, design_results['s_Wp_design'], mode)
        prob[pt + '.balance.Nmech'] = design_results['Nmech'] * (1.0/a4)**0.3

    t1 = time.time()
    prob.run_model()
    print(f'Sweep solved in {time.time()-t1:.1f}s')

    results = []
    for pt, a4 in zip(mp.a4_pts, mp.a4_scalars):
        r = extract_od_point(prob, pt)
        r['scalar'] = a4
        results.append(r)

    print('\n' + '=' * 80)
    print(' STUDY 1 RESULTS — Constant Tt4')
    print('=' * 80)
    print(f"{'A4 scl':>7} {'PR':>8} {'Nmech':>9} {'W kg/s':>8} "
          f"{'Fn kN':>8} {'TSFC':>9} {'T3 K':>7} {'T4 K':>7}")
    print('-' * 80)
    for r in results:
        print(f"  {r['scalar']:5.3f}  {r['pi_c']:8.3f}  {r['Nmech']:8.1f}  "
              f"{r['W']*LBM_S_TO_KG_S:7.2f}  {r['Fn']*LBF_TO_KN:7.2f}  "
              f"{r['TSFC']:9.5f}  {r['T3']*RANKINE_TO_K:6.1f}  "
              f"{r['T4']*RANKINE_TO_K:6.1f}")

    return prob, design_results, results


# ══════════════════════════════════════════════════════════════════════════════
#  STUDY 2 — CONSTANT Fn
# ══════════════════════════════════════════════════════════════════════════════

def run_study2(cfg, mode, design_results_s1):
    print('\n' + '█' * 60)
    print(f' STUDY 2 — Constant Fn, Variable A4  [mode={mode}]')
    print('█' * 60)

    MPConstFn = _make_mp_const_fn(cfg)
    prob = om.Problem()
    mp   = prob.model = MPConstFn()
    prob.setup(check=False)

    prob.set_val('DESIGN.fc.alt',            0.0,               units='ft')
    prob.set_val('DESIGN.fc.MN',             0.000001)
    prob.set_val('DESIGN.balance.Fn_target', cfg['Fn_design'],  units='lbf')
    prob.set_val('DESIGN.balance.T4_target', cfg['T4_design'],  units='degR')
    prob.set_val('DESIGN.comp.PR',           cfg['OPR'])
    prob.set_val('DESIGN.comp.eff',          cfg['comp_eff'])
    prob.set_val('DESIGN.turb.eff',          cfg['turb_eff'])
    prob['DESIGN.balance.FAR']     = cfg.get('FAR_guess',     0.0175)
    prob['DESIGN.balance.W']       = cfg.get('W_guess',       168.0)
    prob['DESIGN.balance.turb_PR'] = cfg.get('turb_PR_guess', 3.5)
    prob['DESIGN.fc.balance.Pt']   = 14.696
    prob['DESIGN.fc.balance.Tt']   = 518.67

    for pt in mp.od_pts:
        prob[pt + '.balance.FAR']   = cfg.get('FAR_guess', 0.017)
        prob[pt + '.balance.Nmech'] = cfg['Nmech']
        prob[pt + '.balance.W']     = cfg.get('W_guess', 168.0)
        prob[pt + '.fc.balance.Pt'] = 14.696
        prob[pt + '.fc.balance.Tt'] = 518.67
        prob.model._get_subsystem(pt).nonlinear_solver.options['maxiter'] = 0

    prob.set_solver_print(level=-1)
    prob.set_solver_print(level=2, depth=1)

    print('\n── Design point ──')
    t0 = time.time()
    prob.run_model()
    print(f'Design solved in {time.time()-t0:.1f}s')
    design_results = extract_design(prob)

    # Set design alpha for alpha mode
    if mode == 'alpha':
        prob.set_val('DESIGN.turb.map.alphaMap', 1.0)

    print('\n── Constant-Fn sweep ──')
    for pt in mp.od_pts:
        prob.model._get_subsystem(pt).nonlinear_solver.options['maxiter'] = 15

    for fi, frac in enumerate(mp.fn_fractions):
        Fn_target = frac * cfg['Fn_design']
        for ai, a4 in enumerate(mp.a4_scalars):
            pt = f'FN{fi:02d}_A4_{ai:03d}'
            set_turb_area(prob, pt, a4, design_results['s_Wp_design'], mode)
            prob.set_val(f'{pt}.balance.Fn_target', Fn_target, units='lbf')
            prob[pt + '.balance.Nmech'] = (design_results['Nmech']
                                           * frac**0.5 * (1.0/a4)**0.3)
            prob[pt + '.balance.FAR']   = cfg.get('FAR_guess', 0.017) * frac

    t1 = time.time()
    prob.run_model()
    print(f'Sweep solved in {time.time()-t1:.1f}s')

    baseline_ai = int(np.argmin(np.abs(np.array(mp.a4_scalars) - 1.0)))
    const_fn_results = {}
    for fi, frac in enumerate(mp.fn_fractions):
        sweep = []
        for ai, a4 in enumerate(mp.a4_scalars):
            r = extract_od_point(prob, f'FN{fi:02d}_A4_{ai:03d}')
            r['scalar'] = a4
            sweep.append(r)
        tsfc_arr = np.array([r['TSFC'] for r in sweep])
        opt_idx  = int(np.argmin(tsfc_arr))
        const_fn_results[frac] = {
            'sweep':         sweep,
            'opt_idx':       opt_idx,
            'opt_scalar':    mp.a4_scalars[opt_idx],
            'opt_tsfc':      tsfc_arr[opt_idx],
            'opt_T4':        sweep[opt_idx]['T4'],
            'baseline_tsfc': tsfc_arr[baseline_ai],
            'baseline_T4':   sweep[baseline_ai]['T4'],
        }

    _summarise_const_fn(mp.fn_fractions, mp.a4_scalars,
                        const_fn_results, design_results, cfg)
    return prob, design_results, const_fn_results


def _summarise_const_fn(fn_fractions, a4_scalars, const_fn_results,
                        design_results, cfg):
    print('\n' + '=' * 80)
    print(' STUDY 2 SUMMARY — OPTIMAL A4 AT EACH THRUST SETTING')
    print('=' * 80)
    print(f"{'Fn (%)':>7} {'Fn_tgt (kN)':>12} {'Opt A4':>8} "
          f"{'Opt TSFC':>10} {'T4 opt (K)':>11} "
          f"{'T4 fixed (K)':>13} {'ΔT4 (K)':>8} {'ΔTSFC (%)':>10}")
    print('-' * 80)
    for frac in fn_fractions:
        d = const_fn_results[frac]
        print(f"  {int(frac*100):5d}  "
              f"{frac*cfg['Fn_design']*LBF_TO_KN:11.2f}  "
              f"{d['opt_scalar']:8.3f}  "
              f"{d['opt_tsfc']:10.5f}  "
              f"{d['opt_T4']*RANKINE_TO_K:11.1f}  "
              f"{d['baseline_T4']*RANKINE_TO_K:13.1f}  "
              f"{(d['baseline_T4']-d['opt_T4'])*RANKINE_TO_K:8.1f}  "
              f"{(d['baseline_tsfc']-d['opt_tsfc'])/d['baseline_tsfc']*100:10.2f}")


# ══════════════════════════════════════════════════════════════════════════════
#  COMBUSTOR PHYSICS SWEEPS
# ══════════════════════════════════════════════════════════════════════════════

def _make_mp_single_fn(cfg):
    """Single-Fn MPCycle for the physics dP/P Gauss-Seidel sweeps."""
    Turbojet        = _make_turbojet(cfg)
    TurbojetConstFn = _make_turbojet_const_fn(cfg)

    class MPSingleFn(pyc.MPCycle):
        def setup(self):
            # dPqP is set per-point in the physics sweep, not as a cycle param
            _add_design_point_and_params(self, Turbojet, cfg, include_dPqP=False)

            self.a4_scalars = cfg['a4_scalars']
            self.od_pts     = [f'A4_{i:03d}' for i in range(len(self.a4_scalars))]

            for pt in self.od_pts:
                self.pyc_add_pnt(pt, TurbojetConstFn(design=False))
                self.set_input_defaults(pt + '.fc.MN',  0.000001)
                self.set_input_defaults(pt + '.fc.alt', 0.0, units='ft')

            _connect_od_scalars(self, self.od_pts)
            super().setup()

    return MPSingleFn


def _run_od_sweep_sequential(prob, mp):
    t0 = time.time()
    for i, pt in enumerate(mp.od_pts):
        for other in mp.od_pts:
            prob.model._get_subsystem(other).nonlinear_solver.options['maxiter'] = 0
        prob.model._get_subsystem(pt).nonlinear_solver.options['maxiter'] = 15
        prob.run_model()
        if i + 1 < len(mp.od_pts):
            nxt = mp.od_pts[i+1]
            for var in ['balance.FAR', 'balance.Nmech', 'balance.W']:
                prob[f'{nxt}.{var}'] = prob[f'{pt}.{var}']
        print(f'    {pt} ({i+1}/{len(mp.od_pts)})')
    print(f'  sweep in {time.time()-t0:.1f}s')


def run_fixed_dPqP_sweep(prob, mp, design_results, fn_frac, cfg, mode):
    print(f"\n  Fixed dP/P={DPQP_FIXED*100:.0f}%  {fn_frac*100:.0f}% Fn")
    Fn_target = fn_frac * cfg['Fn_design']
    for pt, a4 in zip(mp.od_pts, mp.a4_scalars):
        set_turb_area(prob, pt, a4, design_results['s_Wp_design'], mode)
        prob.set_val(f'{pt}.balance.Fn_target', Fn_target, units='lbf')
        prob.set_val(f'{pt}.burner.dPqP', DPQP_FIXED)
        prob[pt + '.balance.Nmech'] = (design_results['Nmech']
                                       * fn_frac**0.5 * (1.0/a4)**0.3)
        prob[pt + '.balance.FAR']   = cfg.get('FAR_guess', 0.017) * fn_frac
        prob.model._get_subsystem(pt).nonlinear_solver.options['maxiter'] = 15

    _run_od_sweep_sequential(prob, mp)

    results = []
    for pt, a4 in zip(mp.od_pts, mp.a4_scalars):
        r = extract_od_point(prob, pt)
        r.update(a4_scalar=a4, dPqP=DPQP_FIXED,
                 fn_frac=fn_frac, eta_th=extract_eta_th(prob, pt))
        results.append(r)
    return results


def run_physics_dPqP_sweep(prob, mp, design_results, fn_frac, cfg, mode):
    print(f"\n  Physics dP/P  {fn_frac*100:.0f}% Fn")
    Fn_target = fn_frac * cfg['Fn_design']
    dPqP_cur  = {pt: DPQP_FIXED for pt in mp.od_pts}

    for outer in range(MAX_OUTER):
        print(f"\n  Outer iter {outer+1}/{MAX_OUTER}")
        for pt, a4 in zip(mp.od_pts, mp.a4_scalars):
            set_turb_area(prob, pt, a4, design_results['s_Wp_design'], mode)
            prob.set_val(f'{pt}.balance.Fn_target', Fn_target, units='lbf')
            prob.set_val(f'{pt}.burner.dPqP', dPqP_cur[pt])
            prob[pt + '.balance.Nmech'] = (design_results['Nmech']
                                           * fn_frac**0.5 * (1.0/a4)**0.3)
            prob[pt + '.balance.FAR']   = cfg.get('FAR_guess', 0.017) * fn_frac
            prob.model._get_subsystem(pt).nonlinear_solver.options['maxiter'] = 15

        _run_od_sweep_sequential(prob, mp)

        dPqP_new, max_change = {}, 0.0
        for pt, a4 in zip(mp.od_pts, mp.a4_scalars):
            r = extract_od_point(prob, pt)
            _, dPqP_phys = physics_pib(
                psi_to_pa(r['P3']), rankine_to_kelvin(r['T3']),
                lbm_s_to_kg_s(r['W']), design_results['CdA_liner'])
            dPqP_phys    = float(np.clip(dPqP_phys, 0.001, 0.50))
            dPqP_new[pt] = dPqP_phys
            change       = abs(dPqP_phys - dPqP_cur[pt]) / max(dPqP_cur[pt], 1e-6)
            max_change   = max(max_change, change)
            print(f'    {pt}  A4={a4:.3f}  dP/P: '
                  f'{dPqP_cur[pt]*100:.2f}%→{dPqP_phys*100:.2f}%')

        print(f'  max change={max_change*100:.3f}%')
        dPqP_cur = dPqP_new
        if max_change < DPQP_TOL:
            print(f'  Converged in {outer+1} iters')
            break

    results = []
    for pt, a4 in zip(mp.od_pts, mp.a4_scalars):
        r = extract_od_point(prob, pt)
        r.update(a4_scalar=a4, dPqP=dPqP_cur[pt],
                 fn_frac=fn_frac, eta_th=extract_eta_th(prob, pt))
        results.append(r)
    return results


# ══════════════════════════════════════════════════════════════════════════════
#  PLOTS
# ══════════════════════════════════════════════════════════════════════════════

def plot_study1(scalars, results, design_results, cfg):
    s     = np.array(scalars)
    pi_c  = np.array([r['pi_c']  for r in results])
    Nmech = np.array([r['Nmech'] for r in results])
    W     = np.array([r['W']     for r in results]) * LBM_S_TO_KG_S
    Fn    = np.array([r['Fn']    for r in results]) * LBF_TO_KN
    TSFC  = np.array([r['TSFC']  for r in results])
    T3    = np.array([r['T3']    for r in results]) * RANKINE_TO_K
    P3    = np.array([r['P3']    for r in results]) * PSI_TO_KPA
    T4_K  = design_results['T4_design'] * RANKINE_TO_K

    fig, axes = plt.subplots(2, 3, figsize=(15, 9))
    fig.suptitle(f'Study 1 — Constant TIT={T4_K:.0f}K, Variable A₄  |  SLS',
                 fontsize=12, fontweight='bold')

    kw  = dict(lw=2, marker='o', markersize=3)
    kwh = dict(ls=':', lw=1.4, alpha=0.8)

    panels = [
        (axes[0,0], pi_c,  'C0', 'Overall PR', f"Des={design_results['pi_c']:.2f}"),
        (axes[0,1], Nmech, 'C1', 'Shaft Speed (rpm)', f"Des={design_results['Nmech']:.0f}"),
        (axes[0,2], W,     'C2', 'Mass Flow (kg/s)', f"Des={design_results['W']*LBM_S_TO_KG_S:.1f}"),
        (axes[1,0], Fn,    'C3', 'Net Thrust (kN)', f"Des={cfg['Fn_design']*LBF_TO_KN:.1f}"),
        (axes[1,1], TSFC,  'C4', 'TSFC (lbm/hr/lbf)', f"Des={design_results['TSFC']:.5f}"),
    ]
    for ax, data, color, ylabel, des_label in panels:
        ax.plot(s, data, color, **kw)
        ax.axhline(data[np.argmin(np.abs(s-1.0))], color=color,
                   label=des_label, **kwh)
        ax.axvline(1.0, color='gray', ls='--', lw=1.5)
        ax.set_xlabel('A₄ scalar', fontsize=9)
        ax.set_ylabel(ylabel, fontsize=9)
        ax.legend(fontsize=8); ax.grid(True, alpha=0.3)

    # TSFC annotation
    ax = axes[1,1]
    mi = int(np.argmin(TSFC))
    ax.annotate(f'Opt={s[mi]:.3f}\nTSFC={TSFC[mi]:.5f}',
                xy=(s[mi], TSFC[mi]),
                xytext=(s[mi]+0.03, TSFC[mi]+0.003), fontsize=7,
                bbox=dict(boxstyle='round', fc='lightyellow', ec='C4'),
                arrowprops=dict(arrowstyle='->', color='C4'))

    # T3/P3
    ax = axes[1,2]; ax2 = ax.twinx()
    l1, = ax.plot(s,  T3, 'C5', **kw, label='T₃ (K)')
    l2, = ax2.plot(s, P3, 'C6', lw=2, marker='s', ms=3, ls='--', label='P₃ (kPa)')
    ax.axvline(1.0, color='gray', ls='--', lw=1.5)
    ax.set_xlabel('A₄ scalar', fontsize=9)
    ax.set_ylabel('T₃ (K)', fontsize=9, color='C5')
    ax2.set_ylabel('P₃ (kPa)', fontsize=9, color='C6')
    ax.legend(handles=[l1, l2], fontsize=8); ax.grid(True, alpha=0.3)

    plt.subplots_adjust(hspace=0.55, wspace=0.38)
    plt.savefig('study1_const_tt4.png', dpi=150)
    plt.show()


def plot_study2(fn_fractions, a4_scalars, const_fn_results, design_results, cfg):
    s      = np.array(a4_scalars)
    colors = cm.viridis(np.linspace(0.15, 0.85, len(fn_fractions)))
    T4_K   = design_results['T4_design'] * RANKINE_TO_K

    fig, axes = plt.subplots(2, 2, figsize=(13, 10))
    fig.suptitle('Study 2 — Constant Thrust, Variable A₄  |  SLS',
                 fontsize=12, fontweight='bold')

    # TSFC locus
    ax = axes[0,0]
    for fi, frac in enumerate(fn_fractions):
        sweep = const_fn_results[frac]['sweep']
        tsfc  = np.array([r['TSFC'] for r in sweep])
        ax.plot(s, tsfc, color=colors[fi], lw=2, marker='o', ms=2,
                label=f'{int(frac*100)}% Fₙ')
        mi = int(np.argmin(tsfc))
        ax.plot(s[mi], tsfc[mi], '*', color=colors[fi], ms=10,
                markeredgecolor='k', zorder=5)
    opt_s    = [const_fn_results[f]['opt_scalar'] for f in fn_fractions]
    opt_tsfc = [const_fn_results[f]['opt_tsfc']   for f in fn_fractions]
    ax.plot(opt_s, opt_tsfc, 'k--', lw=1.5, label='Locus of optima')
    ax.axvline(1.0, color='gray', ls='--', lw=1.2)
    ax.set_xlabel('A₄ scalar'); ax.set_ylabel('TSFC')
    ax.set_title('TSFC vs A₄ — ★ = minimum'); ax.legend(fontsize=8); ax.grid(True, alpha=0.3)

    # Optimal A4 schedule
    ax = axes[0,1]
    pct = [f*100 for f in fn_fractions]
    ax.plot(pct, opt_s, 'ko-', lw=2, ms=8)
    ax.axhline(1.0, color='gray', ls='--', lw=1.2, label='Design')
    ax.set_xlabel('Thrust (% design)'); ax.set_ylabel('Optimal A₄ scalar')
    ax.set_title('Optimal A₄ Schedule'); ax.legend(fontsize=8); ax.grid(True, alpha=0.3)

    # TSFC improvement
    ax = axes[1,0]; ax2 = ax.twinx()
    fg_tsfc = [const_fn_results[f]['baseline_tsfc'] for f in fn_fractions]
    op_tsfc = [const_fn_results[f]['opt_tsfc']      for f in fn_fractions]
    d_abs   = [fg-op for fg,op in zip(fg_tsfc, op_tsfc)]
    d_pct   = [d/fg*100 for d,fg in zip(d_abs, fg_tsfc)]
    ax.bar(pct, d_pct, width=4, color=colors, edgecolor='k', alpha=0.85)
    ax2.plot(pct, d_abs, 'k^--', lw=1.5, ms=7)
    for i,(p,dp) in enumerate(zip(pct, d_pct)):
        ax.text(p, dp+0.01, f'{dp:.2f}%', ha='center', fontsize=8, fontweight='bold')
    ax.set_xlabel('Thrust (% design)'); ax.set_ylabel('ΔTSFC (%)', color='C0')
    ax2.set_ylabel('ΔTSFC (abs)', color='k')
    ax.set_title('TSFC Benefit of Variable A₄'); ax.grid(True, alpha=0.3, axis='y')

    # T4 reduction
    ax = axes[1,1]
    opt_T4  = [const_fn_results[f]['opt_T4']*RANKINE_TO_K      for f in fn_fractions]
    fix_T4  = [const_fn_results[f]['baseline_T4']*RANKINE_TO_K for f in fn_fractions]
    ax.plot(pct, opt_T4, 'o-', color='C3', lw=2, ms=8, label='Optimal A₄')
    ax.plot(pct, fix_T4, 's--', color='C1', lw=2, ms=8, label='Fixed geometry')
    ax.axhline(T4_K, color='gray', ls=':', lw=1.2, label=f'Design T₄={T4_K:.0f}K')
    ax.fill_between(pct, fix_T4, opt_T4, alpha=0.15, color='green')
    ax.set_xlabel('Thrust (% design)'); ax.set_ylabel('T₄ (K)')
    ax.set_title('TIT Reduction with Variable A₄'); ax.legend(fontsize=8); ax.grid(True, alpha=0.3)

    plt.subplots_adjust(hspace=0.50, wspace=0.38)
    plt.savefig('study2_const_fn.png', dpi=150)
    plt.show()


def plot_combustor(fixed_by_fn, physics_by_fn, fn_fracs):
    colors = {}
    for f in fn_fracs:
        colors[f] = FN_COLORS.get(f, f'C{list(fn_fracs).index(f)}')

    fig1, axes = plt.subplots(1, len(fn_fracs),
                               figsize=(5*len(fn_fracs), 5), sharey=False)
    if len(fn_fracs) == 1:
        axes = [axes]
    fig1.suptitle("Gas Generator Thermal Efficiency vs A₄\n"
                  "Solid=physics dP/P  |  Faded=fixed 5%",
                  fontsize=11, fontweight='bold')

    for ax, frac in zip(axes, fn_fracs):
        color = colors[frac]
        res_f = fixed_by_fn[frac]
        s_f   = np.array([r['a4_scalar'] for r in res_f])
        eta_f = np.array([r['eta_th']    for r in res_f]) * 100
        ax.plot(s_f, eta_f, '-', color=color, lw=1.5, alpha=0.35, label='Fixed dP/P')

        res_p = physics_by_fn[frac]
        s_p   = np.array([r['a4_scalar'] for r in res_p])
        eta_p = np.array([r['eta_th']    for r in res_p]) * 100
        ax.plot(s_p, eta_p, '-', color=color, lw=2.2, label='Physics dP/P')

        idx_p = int(np.argmax(eta_p))
        ax.scatter([s_p[idx_p]], [eta_p[idx_p]], color=color,
                   s=160, marker='*', edgecolors='k', zorder=5)
        ax.axvline(1.0, color='gray', ls='--', lw=1.0, alpha=0.5)
        ax.set_xlabel('A₄ scalar'); ax.set_ylabel('η_th (%)');
        ax.set_title(f'{frac*100:.0f}% Fₙ', fontweight='bold', color=color)
        ax.legend(fontsize=8); ax.grid(False)
        ax.spines['top'].set_visible(False); ax.spines['right'].set_visible(False)

    fig1.tight_layout()
    fig1.savefig('combustor_eta_th.png', dpi=150, bbox_inches='tight')

    fig2, ax2 = plt.subplots(figsize=(7, 5))
    ax2.axhline(DPQP_FIXED*100, color='gray', ls='--', lw=1.2,
                label=f'Design dP/P={DPQP_FIXED*100:.0f}%')
    for frac, results in physics_by_fn.items():
        color = colors[frac]
        s     = np.array([r['a4_scalar'] for r in results])
        dPqP  = np.array([r['dPqP']*100  for r in results])
        ax2.plot(s, dPqP, 'o-', color=color, lw=2, ms=4,
                 label=f'Physics {frac*100:.0f}% Fₙ')
        idx1 = int(np.argmin(np.abs(s-1.0)))
        ax2.scatter([s[idx1]], [dPqP[idx1]], color=color,
                    s=100, marker='D', edgecolors='k', zorder=5)
        ax2.annotate(f'{dPqP[idx1]:.2f}%',
                     xy=(s[idx1], dPqP[idx1]),
                     xytext=(s[idx1]-0.06, dPqP[idx1]+0.05),
                     fontsize=7.5, color=color)
    ax2.axvline(1.0, color='gray', ls='--', lw=1.0, alpha=0.5)
    ax2.set_xlabel('A₄ scalar'); ax2.set_ylabel('Combustor dP/P (%)')
    ax2.set_title('Physics-Based Combustor Pressure Drop', fontweight='bold')
    ax2.legend(fontsize=8)
    ax2.spines['top'].set_visible(False); ax2.spines['right'].set_visible(False)
    fig2.tight_layout()
    fig2.savefig('combustor_dpqp.png', dpi=150, bbox_inches='tight')
    plt.show()


# ══════════════════════════════════════════════════════════════════════════════
#  MAIN
# ══════════════════════════════════════════════════════════════════════════════

if __name__ == '__main__':

    from scipy.interpolate import RegularGridInterpolator
    from EngineHPT_map       import EngineHPTMap as EngineHPTVGTMap
    from EngineHPT_map_fixed import EngineHPTMap as EngineHPTFixedMap

    # ══════════════════════════════════════════════════════════════
    #  COOLING MODEL CONSTANTS
    # ══════════════════════════════════════════════════════════════
    # Fixed fractions — Walsh & Fletcher (2004) §5.4: total HPT cooling
    # ~10-12% of W3 for single-stage HPT at TIT 1300-1450 K, split ~equally.
    NGV_COOL_FRAC   = 0.05   # non-chargeable: NGV/stator, frac_P=1.0 on turbine
    BLD_COOL_FRAC   = 0.05   # chargeable: rotor blade, frac_P=0.0 on turbine
    TOTAL_COOL_FRAC = NGV_COOL_FRAC + BLD_COOL_FRAC

    ETA_COOL    = 0.65    # film cooling effectiveness (Horlock et al. 2001)
    T_METAL_MAX = 1200    # K — reference material limit for T_metal tracking

    # ══════════════════════════════════════════════════════════════
    #  MAP DESIGN POINT EXTRACTION
    #  pyCycle Np convention: N / sqrt(Tt_degR), Tref = 1 degR
    # ══════════════════════════════════════════════════════════════

    _Nmech   = 8070.0
    _T4_degR = 2370.0
    _Np_des  = _Nmech / np.sqrt(_T4_degR)   # ≈ 165.77

    def map_design_point(turb_map, Np_des, alpha_design=1.0):
        """Read design efficiency from map at defaults operating point."""
        a_idx   = int(np.argmin(np.abs(np.array(turb_map.alphaMap) - alpha_design)))
        eff_sl  = np.array(turb_map.effMap[a_idx])
        NpMap   = np.array(turb_map.NpMap)
        PRmap   = np.array(turb_map.PRmap)
        PR_des  = turb_map.defaults['PRmap']
        Np_q    = float(np.clip(Np_des, NpMap[0], NpMap[-1]))
        interp  = RegularGridInterpolator(
            (NpMap, PRmap), eff_sl,
            method='linear', bounds_error=False, fill_value=None)
        eff_des = float(interp([[Np_q, PR_des]]))
        return eff_des, PR_des

    eff_fixed, PR_fixed = map_design_point(EngineHPTFixedMap, _Np_des)
    eff_vgt,   PR_vgt   = map_design_point(EngineHPTVGTMap,   _Np_des)

    print("=" * 65)
    print("  Map design point extraction")
    print(f"  Fixed:  eta={eff_fixed*100:.3f}%  PR={PR_fixed:.4f}")
    print(f"  VGT:    eta={eff_vgt*100:.3f}%    PR={PR_vgt:.4f}")
    print(f"  Leakage penalty: Δeta={(eff_fixed-eff_vgt)*100:+.3f}%")
    print("=" * 65)

    # ╔══════════════════════════════════════════════════════════════╗
    # ║  SHARED CYCLE CONFIG                                        ║
    # ╚══════════════════════════════════════════════════════════════╝
    BASE_CFG = dict(
        comp_map     = pyc.HPCMap,
        Fn_design    = 11800.0,   # lbf
        T4_design    = _T4_degR,    # degR
        OPR          = 13.5*0.5,
        Nmech        = _Nmech,    # rpm
        comp_eff     = 0.83,
        inlet_MN     = 0.60,
        comp_MN      = 0.020,
        burner_MN    = 0.020,
        turb_MN      = 0.40,
        nozz_Cv      = 0.99,
        FAR_guess    = 0.0175,
        W_guess      = 168.0,
        fn_fractions = [0.50, 1.00],
        a4_scalars   = list(np.linspace(0.80, 1.10, 15)),
        ngv_cool_frac = NGV_COOL_FRAC,
        bld_cool_frac = BLD_COOL_FRAC,
    )

    CFG_FIXED = {
        **BASE_CFG,
        'turb_map'     : EngineHPTFixedMap,
        'turb_eff'     : eff_fixed,
        'turb_PR_guess': PR_fixed,
        'a4_scalars'   : [1.0],        # fixed geometry — single point
    }
    CFG_VGT = {
        **BASE_CFG,
        'turb_map'     : EngineHPTVGTMap,
        'turb_eff'     : eff_vgt,
        'turb_PR_guess': PR_vgt,
    }
    
    print("=" * 65)
    print(f" Fixed vs VGT — physics dP/P + blade temperature")
    print(f" Fn levels: {[int(f*100) for f in BASE_CFG['fn_fractions']]}%")
    print(f" VGT A4: {CFG_VGT['a4_scalars'][0]:.2f}→"
          f"{CFG_VGT['a4_scalars'][-1]:.2f}"
          f"  ({len(CFG_VGT['a4_scalars'])} pts)")
    print("=" * 65)

    all_results = {}

    for label, cfg, mode in [
        ('fixed', CFG_FIXED, 'sWp'),
        ('vgt',   CFG_VGT,   'sWp'),
    ]:
        print(f"\n{'█'*65}")
        print(f" {label.upper()} TURBINE")
        print(f"{'█'*65}")

        MPSingleFn = _make_mp_single_fn(cfg)
        prob_cb    = om.Problem()
        mp_cb      = prob_cb.model = MPSingleFn()
        prob_cb.setup(check=False)

        prob_cb.set_val('DESIGN.fc.alt',            0.0,              units='ft')
        prob_cb.set_val('DESIGN.fc.MN',             0.000001)
        prob_cb.set_val('DESIGN.balance.Fn_target', cfg['Fn_design'], units='lbf')
        prob_cb.set_val('DESIGN.balance.T4_target', cfg['T4_design'], units='degR')
        prob_cb.set_val('DESIGN.comp.PR',           cfg['OPR'])
        prob_cb.set_val('DESIGN.comp.eff',          cfg['comp_eff'])
        prob_cb.set_val('DESIGN.turb.eff',          cfg['turb_eff'])
        prob_cb.set_val('DESIGN.burner.dPqP',       DPQP_FIXED)
        if mode == 'alpha':
            prob_cb.set_val('DESIGN.turb.map.alphaMap', 1.0)
        prob_cb['DESIGN.balance.FAR']     = cfg.get('FAR_guess', 0.0175)
        prob_cb['DESIGN.balance.W']       = cfg.get('W_guess', 168.0)
        prob_cb['DESIGN.balance.turb_PR'] = cfg.get('turb_PR_guess', 3.5)
        prob_cb['DESIGN.fc.balance.Pt']   = 14.696
        prob_cb['DESIGN.fc.balance.Tt']   = 518.67
        for pt in mp_cb.od_pts:
            prob_cb.model._get_subsystem(pt).nonlinear_solver.options['maxiter'] = 0
        prob_cb.set_solver_print(level=-1)
        prob_cb.set_solver_print(level=2, depth=1)
        prob_cb.run_model()

        des_cb = extract_design(prob_cb)

        # ── Sanity check scale factors ────────────────────────────────────
        s_eff = prob_cb.get_val('DESIGN.turb.s_eff')[0]
        s_Wp  = prob_cb.get_val('DESIGN.turb.s_Wp')[0]

        print(f"  nozz area = {prob_cb.get_val('DESIGN.nozz.Throat:stat:area')[0]:.4f} in²")
        print(f"  Design: eta={des_cb['eff_design']*100:.3f}%"
              f"  s_Wp={s_Wp:.6f}  s_eff={s_eff:.6f}"
              f"  TSFC={des_cb['TSFC']:.5f}")

        # ── Design-point T_metal (reference, not a constraint) ───────────
        Tt4_des_K = des_cb['T4_design'] * RANKINE_TO_K
        T3_des_K  = des_cb['T3_design'] * RANKINE_TO_K
        T_metal_des = Tt4_des_K - ETA_COOL * TOTAL_COOL_FRAC * (Tt4_des_K - T3_des_K)
        print(f"  Cooling: NGV={NGV_COOL_FRAC*100:.0f}%  blade={BLD_COOL_FRAC*100:.0f}%"
              f"  T_metal_des={T_metal_des:.1f}K  (ref limit={T_METAL_MAX:.0f}K)")

        # ── CdA from design point (placeholder) ──────────────────────────
        des_cb['CdA_liner'] = calc_CdA_liner(
            T3_des_K,
            psi_to_pa(des_cb['P3_design']),
            lbm_s_to_kg_s(des_cb['W']),
        )

        # ── Fixed dP/P sweep ─────────────────────────────────────────────
        fixed_by_fn = {}
        for fn_frac in cfg['fn_fractions']:
            fixed_by_fn[fn_frac] = run_fixed_dPqP_sweep(
                prob_cb, mp_cb, des_cb, fn_frac, cfg, mode)

        # ── Re-anchor CdA from 100% Fn, A4=1.0 ───────────────────────────
        if 1.00 in fixed_by_fn:
            anc = min(fixed_by_fn[1.00], key=lambda r: abs(r['a4_scalar'] - 1.0))
            CdA = calc_CdA_liner(
                rankine_to_kelvin(anc['T3']),
                psi_to_pa(anc['P3']),
                lbm_s_to_kg_s(anc['W']))
            des_cb['CdA_liner'] = CdA
            print(f"  CdA (re-anchored) = {CdA*1e4:.4f} cm²")

        # ── Physics dP/P sweep ───────────────────────────────────────────
        physics_by_fn = {}
        for fn_frac in cfg['fn_fractions']:
            physics_by_fn[fn_frac] = run_physics_dPqP_sweep(
                prob_cb, mp_cb, des_cb, fn_frac, cfg, mode)

        # ── Blade temperature at each operating point ─────────────────────
        # T_metal = Tt4 - eta_cool * frac_W * (Tt4 - T3)
        for fn_frac in cfg['fn_fractions']:
            for r in physics_by_fn[fn_frac]:
                Tt4_K = r['T4'] * RANKINE_TO_K
                T3_K  = r['T3'] * RANKINE_TO_K
                r['T_metal'] = Tt4_K - ETA_COOL * TOTAL_COOL_FRAC * (Tt4_K - T3_K)

        all_results[label] = {
            'des':         des_cb,
            'frac_W':      TOTAL_COOL_FRAC,
            'T_metal_des': T_metal_des,
            'fixed_dpqp':  fixed_by_fn,
            'phys_dpqp':   physics_by_fn,
        }

    # ══════════════════════════════════════════════════════════════
    #  FIGURE 1 — THERMAL EFFICIENCY
    # ══════════════════════════════════════════════════════════════

    def _style_subplot(ax, fn_frac, ylabel):
        ax.axvline(1.0, color='gray', ls=':', lw=1.2, alpha=0.7)
        ax.set_title(f'{fn_frac*100:.0f}% Fₙ', fontsize=11, fontweight='bold')
        ax.set_xlabel('A₄ scalar  (1.0 = design)', fontsize=10)
        ax.set_ylabel(ylabel, fontsize=10)
        ax.legend(fontsize=7)
        ax.grid(True, alpha=0.25)
        ax.spines['top'].set_visible(False)
        ax.spines['right'].set_visible(False)

    fn_fracs = BASE_CFG['fn_fractions']
    ncols    = len(fn_fracs)

    fig1, axes1 = plt.subplots(1, ncols, figsize=(6*ncols, 5), sharey=False)
    if ncols == 1:
        axes1 = [axes1]
    fig1.suptitle('Fixed vs Variable Geometry Turbine — Thermal Efficiency',
                  fontsize=12, fontweight='bold')

    for col, fn_frac in enumerate(fn_fracs):
        ax = axes1[col]

        eta_fix_f = np.mean([r['eta_th'] for r in
                             all_results['fixed']['fixed_dpqp'][fn_frac]]) * 100
        eta_fix_p = np.mean([r['eta_th'] for r in
                             all_results['fixed']['phys_dpqp'][fn_frac]]) * 100

        ax.axhline(eta_fix_f, color='steelblue', ls='--', lw=2,
                   label='Fixed — fixed dP/P')
        ax.axhline(eta_fix_p, color='steelblue', ls='-',  lw=2,
                   label='Fixed — physics dP/P')

        vgt_f = all_results['vgt']['fixed_dpqp'][fn_frac]
        vgt_p = all_results['vgt']['phys_dpqp'][fn_frac]
        s_f   = np.array([r['a4_scalar'] for r in vgt_f])
        s_p   = np.array([r['a4_scalar'] for r in vgt_p])
        ax.plot(s_f, np.array([r['eta_th'] for r in vgt_f])*100,
                'o--', color='firebrick', lw=2, ms=5, label='VGT — fixed dP/P')
        ax.plot(s_p, np.array([r['eta_th'] for r in vgt_p])*100,
                'o-',  color='firebrick', lw=2, ms=5, label='VGT — physics dP/P')

        _style_subplot(ax, fn_frac, 'η_th (%)')

    fig1.tight_layout()
    fig1.savefig('fixed_vs_vgt_eta_th.png', dpi=150, bbox_inches='tight')

    # ══════════════════════════════════════════════════════════════
    #  FIGURE 2 — ΔT_METAL vs A4 SCALAR
    #  Primary trace: ΔT = T_metal(VGT, A4) − T_metal(fixed)
    #  Zero line = fixed geometry baseline; negative = VGT cooler
    # ══════════════════════════════════════════════════════════════

    fig2, axes2 = plt.subplots(1, ncols, figsize=(6*ncols, 5),
                                sharey=True if ncols > 1 else False)
    if ncols == 1:
        axes2 = [axes2]
    fig2.suptitle(
        'Variable Geometry Turbine — Blade Metal Temperature Change vs Fixed\n'
        f'Cooling: NGV={NGV_COOL_FRAC*100:.0f}%  blade={BLD_COOL_FRAC*100:.0f}%'
        f'  η_cool={ETA_COOL}  (Horlock 2001)',
        fontsize=11, fontweight='bold')

    for col, fn_frac in enumerate(fn_fracs):
        ax = axes2[col]

        T_metal_fix = np.mean([r['T_metal'] for r in
                               all_results['fixed']['phys_dpqp'][fn_frac]])

        vgt_p       = all_results['vgt']['phys_dpqp'][fn_frac]
        s_p         = np.array([r['a4_scalar'] for r in vgt_p])
        T_metal_vgt = np.array([r['T_metal']   for r in vgt_p])
        dT          = T_metal_vgt - T_metal_fix   # negative = VGT cooler than fixed

        ax.axhline(0.0, color='steelblue', ls='-', lw=1.8,
                   label=f'Fixed baseline  ({T_metal_fix:.0f} K)')
        ax.axhline(T_METAL_MAX - T_metal_fix, color='k', ls='--', lw=1.3,
                   alpha=0.6, label=f'Material limit ({T_METAL_MAX:.0f} K)')

        ax.plot(s_p, dT, 'o-', color='firebrick', lw=2, ms=5,
                label='VGT − Fixed')
        ax.fill_between(s_p, 0, dT,
                        where=(dT <= 0), alpha=0.15, color='steelblue',
                        label='VGT cooler')
        ax.fill_between(s_p, 0, dT,
                        where=(dT > 0),  alpha=0.15, color='firebrick',
                        label='VGT hotter')

        # Annotate at A4=1.0 (unscaled VGT) and at optimum-η A4
        idx_unit = int(np.argmin(np.abs(s_p - 1.0)))
        ax.annotate(f'A₄=1.0\nΔT={dT[idx_unit]:+.1f}K',
                    xy=(s_p[idx_unit], dT[idx_unit]),
                    xytext=(s_p[idx_unit] + 0.03, dT[idx_unit] - 3),
                    fontsize=8, color='gray',
                    arrowprops=dict(arrowstyle='->', color='gray', lw=0.7))

        opt_idx = int(np.argmin(dT))   # A4 that minimises T_metal
        ax.annotate(f'Min ΔT: A₄={s_p[opt_idx]:.2f}\nΔT={dT[opt_idx]:+.1f}K',
                    xy=(s_p[opt_idx], dT[opt_idx]),
                    xytext=(s_p[opt_idx] + 0.03, dT[opt_idx] + 3),
                    fontsize=8, color='steelblue',
                    bbox=dict(boxstyle='round,pad=0.3', fc='white',
                              ec='steelblue', alpha=0.9),
                    arrowprops=dict(arrowstyle='->', color='steelblue', lw=0.8))

        _style_subplot(ax, fn_frac, 'ΔT_metal  (K)  [VGT − Fixed]')

    fig2.tight_layout()
    fig2.savefig('fixed_vs_vgt_delta_Tmetal.png', dpi=150, bbox_inches='tight')
    plt.show()

    # ── Raw data table ─────────────────────────────────────────────────────
    HDR = (f"  {'Fn%':>4}  {'Config':>5}  {'A4':>6}  {'T4 (K)':>8}  "
           f"{'Nmech':>7}  {'OPR':>6}  {'TSFC':>9}  {'η_th%':>7}  "
           f"{'T_metal':>8}  {'dPqP%':>6}")
    SEP = "  " + "-" * (len(HDR) - 2)

    print("\n" + "=" * len(HDR))
    print("  RAW DATA — physics dP/P sweep")
    print("=" * len(HDR))
    print(HDR)
    print(SEP)

    for fn_frac in fn_fracs:
        fix_pts = all_results['fixed']['phys_dpqp'][fn_frac]
        vgt_pts = all_results['vgt']['phys_dpqp'][fn_frac]

        # Fixed is a single A4=1.0 point; repeat label for alignment
        for r in fix_pts:
            print(f"  {int(fn_frac*100):4d}  {'fixed':>5}  {r['a4_scalar']:6.3f}"
                  f"  {r['T4']*RANKINE_TO_K:8.1f}  {r['Nmech']:7.1f}"
                  f"  {r['comp_PR']:6.3f}  {r['TSFC']:9.5f}"
                  f"  {r['eta_th']*100:7.4f}  {r['T_metal']:8.1f}"
                  f"  {r['dPqP']*100:6.3f}")

        print(SEP)

        for r in vgt_pts:
            print(f"  {int(fn_frac*100):4d}  {'vgt':>5}  {r['a4_scalar']:6.3f}"
                  f"  {r['T4']*RANKINE_TO_K:8.1f}  {r['Nmech']:7.1f}"
                  f"  {r['comp_PR']:6.3f}  {r['TSFC']:9.5f}"
                  f"  {r['eta_th']*100:7.4f}  {r['T_metal']:8.1f}"
                  f"  {r['dPqP']*100:6.3f}")

        print(SEP)

    # ── Summary table ──────────────────────────────────────────────────────
    print("\n" + "=" * len(HDR))
    print("  SUMMARY — Fixed vs VGT at optimal A4 (physics dP/P)")
    print("=" * len(HDR))
    print(f"  {'Fn (%)':>7}  {'η_th fixed':>12}  {'η_th VGT':>10}"
          f"  {'Δη_th':>8}  {'T_metal fix':>12}  {'T_metal VGT':>12}  {'ΔT (K)':>8}")
    print("  " + "-" * (len(HDR) - 2))
    for fn_frac in fn_fracs:
        eta_f   = np.mean([r['eta_th']  for r in
                           all_results['fixed']['phys_dpqp'][fn_frac]]) * 100
        T_f     = np.mean([r['T_metal'] for r in
                           all_results['fixed']['phys_dpqp'][fn_frac]])
        vgt_res = all_results['vgt']['phys_dpqp'][fn_frac]
        opt_idx = int(np.argmin([r['T_metal'] for r in vgt_res]))
        eta_v   = vgt_res[opt_idx]['eta_th'] * 100
        T_v     = vgt_res[opt_idx]['T_metal']
        a4_opt  = vgt_res[opt_idx]['a4_scalar']
        print(f"  {int(fn_frac*100):7d}  {eta_f:12.4f}  {eta_v:10.4f}"
              f"  {eta_v-eta_f:+8.4f}  {T_f:12.1f}  {T_v:12.1f}  {T_v-T_f:+8.1f}"
              f"  (A4_opt={a4_opt:.3f})")
    
    
